### ISSUE TITLE
CTD on the xpl , x-plane 11.50 , Vulkan enabled

### ISSUE THREAD

**Issue by dbarnea** [mSparks43/747-400#100]
Faulting application name: X-Plane.exe, version: 11.0.51.1, time stamp: 0x5fbe75cf
[Log.txt](https://github.com/mSparks43/747-400/files/5616511/Log.txt)

Faulting module name: win.xpl, version: 0.0.0.0, time stamp: 0x5f6bc051
Exception code: 0xc0000409
Fault offset: 0x000000000010c33d
Faulting process id: 0x8ac
Faulting application start time: 0x01d6c71790c65d75
Faulting application path: E:\Games\X-Plane 11\X-Plane.exe
Faulting module path: E:\Games\X-Plane 11\Aircraft\Sparky744\plugins\xtlua\64\win.xpl
Report Id: 1c999590-8cfe-4633-ab1b-bb853d5e05e5
Faulting package full name: 
Faulting package-relative application ID:

**Comment by mSparks43** [comment]
Did the console that opens up when you start the plane give any further information?
Did you install the windows installers linked in the readme?

**Comment by dbarnea** [comment]
I did install the VC runtime although I'm pretty sure I had it before ...
I didn't see any additional info in the console , I think it closed before I had a chance to look.

I will try to reproduce and pay more attention. Is there any way I can pipe the output to a file ?

**Comment by mSparks43** [comment]
> Is there any way I can pipe the output to a file

Linux and macos yes really easily, windows I dont think so, but a command line pipe might work now it has a console to write to.

**Comment by crazytimtimtim** [comment]
Do you still have this problem @dbarnea ?

**Comment by mSparks43** [comment]
probably an xp/xtlua beta issue that has since been resolved, or maybe the faulty PNGs in the plane version this was reported on. closing with cant recreate.
