### ISSUE TITLE
Problem with reverse

### ISSUE THREAD

**Issue by Brovns** [mSparks43/747-400#102]
After landing on runway I set max reverse, but thrust go to max thrust.
Thrust levers first show max reverse and immediately switch to max thrust.

**Comment by mSparks43** [comment]
This looks like an engines script issue. Any kind of bounce that disconnects the wheels from the ground is disabling the thrust reverse and switching to forward thrust.

**Comment by mSparks43** [comment]
proposed fix in ddc0c74217532b64c53cabfd82ff1047695650b8
