### ISSUE TITLE
MCP ALT not being reached (VNAV)

### ISSUE THREAD

**Issue by flfy** [mSparks43/747-400#103]
Expected: FL290 is reach by VNAV

What happened: Aircraft climbed to FL283 and stopped climbing.

![image](https://user-images.githubusercontent.com/24484463/101086209-264e2280-3576-11eb-86c0-4d39f2720f2a.png)

**Comment by mSparks43** [comment]
This is going to need a few test flights to confirm its fixed. Issue appears to arise from changing to cruise speed before cruise altitude is actually reached from early versions of the VNAV overhaul, this is now obsolete and has been removed in d6a5ef5ed80e01a927a3215c5a63342f5fc2f861
