### ISSUE TITLE
Incorrect fuel calculations

### ISSUE THREAD

**Issue by flfy** [mSparks43/747-400#104]
Total Fuel is being calculated incorrectly somewhere.

EDIT: In my testing, the fuel calculation seems to be off by 2.4 kgs * 1000

EDIT2: Fuel differences seem to vary, it's not always 2.4 kgs * 1000

![image](https://user-images.githubusercontent.com/24484463/101086314-4da4ef80-3576-11eb-8900-a5c5a25f1dfa.png)

**Comment by mSparks43** [comment]
Can't recreate this
![image](https://user-images.githubusercontent.com/6773686/148660282-4d514c77-1259-499a-bc7e-549931c54c19.png)
So either fixed since this issue was created, or there is some other bug that isn't described how it got into this state.
