### ISSUE TITLE
TCAS OFF warning displayed when TA/RA on and EFIS TFC off

### ISSUE THREAD

**Issue by flfy** [mSparks43/747-400#107]
TCAS OFF should only be displayed when TA/RA is not on.

FCOM:

![chrome_5xgXJl1fAe](https://user-images.githubusercontent.com/24484463/101178935-349c4d00-360f-11eb-9c84-9d2bb11b16aa.png)
![chrome_eFR8WCqe0d](https://user-images.githubusercontent.com/24484463/101178938-3534e380-360f-11eb-9458-6a77d13a1700.png)

**Comment by mSparks43** [comment]
more info also in https://github.com/mSparks43/747-400/pull/106

**Comment by mSparks43** [comment]
eicas message should only be inhibited in takeoff to 400 feet.
shows on the ground otherwise
