### ISSUE TITLE
Captain ND items go through FO ND and waypoint sometimes not displayed

### ISSUE THREAD

**Issue by MCCVeen** [mSparks43/747-400#108]
So I did a little test flight tonight around Schiphol routing BERGI1S direct to REDFA and after that ILS 18R with the RIVER transition, and just before reaching REDFA I changed that to the REDFA1A arrival with the SUGOL transition for the ILS 18R. The ND updated the magenta (or well, white in this case) line for the route but the old waypoints stayed.

Also on the FO ND there were no waypoints displayed at all and sometimes items from the Captain ND go through the FO ND.

![747-400 Captain ND items go through FO ND](https://user-images.githubusercontent.com/75425109/101217162-2e46b900-3681-11eb-8dd0-e13e8c068576.png)
![747-400 Old waypoints stay displayed on the ND while not being in the FMC at all and the new waypoints aren't shown](https://user-images.githubusercontent.com/75425109/101218555-926a7c80-3683-11eb-82b9-874e70027c94.png)

**Comment by MCCVeen** [comment]
![747-400 Old waypoints stay displayed on the ND while not being in the FMC at all and the new waypoints aren't shown](https://user-images.githubusercontent.com/75425109/101218318-2556e700-3683-11eb-9954-c9bcf7833249.png)

**Comment by mSparks43** [comment]
See #245
