### ISSUE TITLE
Heat Blur from engines in cabin

### ISSUE THREAD

**Issue by jmsantafe** [mSparks43/747-400#11]
<img width="2048" alt="Screen Shot 2020-06-25 at 1 49 31 PM" src="https://user-images.githubusercontent.com/67196086/85782350-235c2580-b6ec-11ea-8538-36d1314ea7c3.png">
You can see the heat blur on the top of the seats.

**Comment by mSparks43** [comment]
And this pic, the wheels through the floor - at least that one was fixed, not sure if the heat blur can be

**Comment by Juppie902** [comment]
Looks like something to be solved together with #78 and similar 3D model issues.
