### ISSUE TITLE
FMA showing modes with FDs off

### ISSUE THREAD

**Issue by MCCVeen** [mSparks43/747-400#110]
While shutting down after an ILS landing I turned off the FDs but the LOC and APP buttons stayed lit (tiny little bug that only APP should've been lit in the first place since they're seperate modes) and on the FMA only LOC was armed while G/S was not
![747-400 AFDS problem](https://user-images.githubusercontent.com/75425109/101218108-c3967d00-3682-11eb-9d55-9eac09adf150.png)

**Comment by mSparks43** [comment]
![image](https://user-images.githubusercontent.com/6773686/116379083-f9dfbf00-a812-11eb-80bc-31303d9d5b8e.png)
