### ISSUE TITLE
">SPEEDBRAKE EXT" CAS advisory

### ISSUE THREAD

**Issue by MCCVeen** [mSparks43/747-400#111]
So often on touchdown when the Speedbrakes go to UP as usual I get a CAS advisory of ">SPEEDBRAKE UP". In this stage of flight, speedbrakes up would be totally normal. Inflight if I give thrust and my speedbrakes are in flight detend I get a Take Off Config warning for the spoilers. In this case I would get a >SPEEDBRAKE UP advisory and not a TO Config warning
![image](https://user-images.githubusercontent.com/75425109/101219588-87641c00-3684-11eb-95d5-b2a03f5b81af.png)

**Comment by flfy** [comment]
fixed in #149
