### ISSUE TITLE
SPEEDBRAKE ARMED memo missing

### ISSUE THREAD

**Issue by MCCVeen** [mSparks43/747-400#112]
So I noticed that once I arm the speedbrakes the memo is missing. It's very simple, as long as your speedbrakes are armed this memo will pop up in all stages of flight with no restrictions.
![image](https://user-images.githubusercontent.com/75425109/101220895-d27f2e80-3686-11eb-8b47-5c5671c97f25.png)

**Comment by flfy** [comment]
fixed in mentioned PR above ^
