### ISSUE TITLE
Main 1 and 4 can't feed Eng 2 and Eng 3

### ISSUE THREAD

**Issue by MCCVeen** [mSparks43/747-400#113]
I had a fuel imbalance where the inner tanks were above 1100 kgs less than the outer tanks so I turned all the crossfeeds on and the 2 and 3 pumps off which should get Tank 1 and 4 to feed Engine 2 and 3 as well, but they didn't in the mod.
![Crossfeed issue 2](https://user-images.githubusercontent.com/75425109/101223256-f1cc8a80-368b-11eb-8c33-0377c6eaee2a.png)
![Crossfeed issue 1](https://user-images.githubusercontent.com/75425109/101223258-f2fdb780-368b-11eb-9aab-913454c17896.png)

**Comment by mSparks43** [comment]
To feed 2 & 3 from Tanks 1 & 4 you have to turn on the gravity feed on the overhead panel.
