### ISSUE TITLE
Groundeffect

### ISSUE THREAD

**Issue by MCCVeen** [mSparks43/747-400#114]
The groundeffect in the mod is very exaggerated. Normal pitch on flare with VREF+5 knots is 4-5 degrees Nose Up, while in the mod it's often 2-4 degrees because you don't need to flare to get a normal landing rate. See this video here for reference: https://www.youtube.com/watch?v=rBL7Hjjf4II&t=99s

**Comment by crazytimtimtim** [comment]
@MCCVeen Are you using the Experimental Flight Model? If so, try turning it off.

**Comment by MCCVeen** [comment]
> @MCCVeen Are you using the Experimental Flight Model? If so, try turning it off.

No I'm not.

**Comment by Matt726-S** [comment]
i feel like its the opposite. whenever i try to land this plane it starts falling out of the sky
https://youtu.be/uk2t-0Q366w 3:03

**Comment by MCCVeen** [comment]
> i feel like its the opposite. whenever i try to land this plane it starts falling out of the sky
> https://youtu.be/uk2t-0Q366w 3:03

you're very unstable there, having your nose way too low causing a sudden rapid rate of descend whichyou notice and try to correct, but since you corrected a bit too late your vertical speed is diving down well below -1000 fpm amd also because your speed was decreasing. it takes a lot of time to get your aircraft back on where you wanna be. Also, groundeffect is air that gets trapped between the plane and the ground which doesn't have enough time to escape, therefor pushing the plane up. That's very normal, but on the mod this is very exaggurated. Normal pitch on final approach is 2.5 degrees with VREF+5, and on flare your pitch should be 5 degrees. In the mod normal pitch on final is 2.5 with VREG+5, so that's coded correctly, but the pitch on flare can not be more than 3 degrees or you'll float the plane. I made a video showing the exact issue (Note that I use TOPCAT for take off and landing performance calculations. Topcat came up with a slightly higher VREF than the aircraft came up with so that's why you see about a 10 knot difference on the PFD between the (V)REF annunciator and the selected VAPP speed) https://youtu.be/GJ14INDpUIw?t=103

**Comment by Matt726-S** [comment]
why is the vertical speed below -1000 at times even with a positive pitch? is that supposed to happen?

**Comment by crazytimtimtim** [comment]
> 
> 
> why is the vertical speed below -1000 at times even with a positive pitch? is that supposed to happen?

Lower airspeed = less lift

**Comment by mSparks43** [comment]
This should be fixed in https://github.com/mSparks43/747-400/commit/01b8286dfa19c4a9adc872da1e2dc2dfa85a824d
