### ISSUE TITLE
APU Bleed Valve

### ISSUE THREAD

**Issue by MCCVeen** [mSparks43/747-400#115]
When the APU Bleed Valve is on and the APU is off the VALVE light shouldn't light up, the VALVE light nly lights up when the VALVE is in the wrong position.
![image](https://user-images.githubusercontent.com/75425109/101224213-4f61d680-368e-11eb-9bf0-885cf01d8c12.png)
![image](https://user-images.githubusercontent.com/75425109/101224226-57ba1180-368e-11eb-858a-00a6c4d96608.png)

**Comment by mSparks43** [comment]
Need to check the apu isolation valve can actuate with the APU off - not sure it can

**Comment by MCCVeen** [comment]
It can't, but the thing is that when the isolation valve is in one position (open or closed) the valve light will extinguish since the valve is not in the transition from open to close or vice versa

**Comment by mSparks43** [comment]
that fcom page says if the light is on when the valve position disagrees with the switch position.
so if you press the switch in with the apu off, the switch is commanding it open but it cant open because the apu is off so stays lit.
surely?

**Comment by MCCVeen** [comment]
> that fcom page says the light is on when the valve position disagrees with the switch position.
> so if you press the switch in with the apu off, the switch is commanding it open but it cant open because the apu is off so stays lit.
> surely?
> You get a momentary light when the apu is on and switching the valve on (and off?) because the valve takes some time to actuate and until it does they disagree.

no, the switch will not make it try to open. It is stuck in one locked position. With the APU Bleed switch on you will not get a VALVE light untill the valve is somewhere between open and closed

**Comment by mSparks43** [comment]
This may well be yet another bad explanation in the fcom, but without further documentation/supporting evidence can't really spend time on it. the fcom says if the switch and valve do not agree the switch illuminates amber. with the APU off, valve disabled and switch in the switch and valve do not agree.

Possibly some inhibit, but without knowing what that is I can't code the logic for it.

**Comment by MCCVeen** [comment]
> This may well be yet another bad explanation in the fcom, but without further documentation/supporting evidence can't really spend time on it. the fcom says if the switch and valve do not agree the switch illuminates amber. with the APU off, valve disabled and switch in the switch and valve do not agree.
> 
> Possibly some inhibit, but without knowing what that is I can't code the logic for it.

Hi! First of all, I haven't checked out the 747 or the hub in a long long time and the progress you and the others are making is incredible!!

The VALVE fault light will only show up when the apu is running and the valve is not in the desired position. When the APU is off this gets disregarded, just like with engine bleeds. You can see it here on the photos of actual 747 overheads

![image](https://user-images.githubusercontent.com/75425109/148665652-b7d5bbf1-7e06-4c9f-98fe-ebfa3a29e20f.png)
![image](https://user-images.githubusercontent.com/75425109/148665656-c2990c27-5476-4696-bd8f-d5774860e838.png)
![image](https://user-images.githubusercontent.com/75425109/148665654-49741bc0-3c80-46ba-a983-bec2996d7bc7.png)

**Comment by mSparks43** [comment]
> Hi! First of all, I haven't checked out the 747 or the hub in a long long time and the progress you and the others are making is incredible!!

It still took a while to get to these. I'm giving you special thanks in the next release for all the effort you put into documenting these.
