### ISSUE TITLE
FMA TOGA modes

### ISSUE THREAD

**Issue by MCCVeen** [mSparks43/747-400#116]
When you're on the ground and you turn the FDs on with no additional modes, TOGA will become the active mode for roll and pitch. In the mod it's armed untill the TOGA button is pushed.
![image](https://user-images.githubusercontent.com/75425109/101224412-cd25e200-368e-11eb-8df1-43f2e777ab91.png)

**Comment by MCCVeen** [comment]
![image](https://user-images.githubusercontent.com/75425109/103445965-8cfc5400-4c7a-11eb-8444-b5f1e405e7c0.png)
![image](https://user-images.githubusercontent.com/75425109/103445970-971e5280-4c7a-11eb-9772-1fa95acbd8b4.png)

**Comment by oMrSmith** [comment]
I agree. And: Since TO/GA is currently not green and active right away
when engaging the FDs, you can't see
on the PFD when you arm LNAV or VNAV.

**Comment by oMrSmith** [comment]
Hey @mSparks43 just for your info: This issue may be closed as you fixed it.
