### ISSUE TITLE
Main gear bounces too much

### ISSUE THREAD

**Issue by MCCVeen** [mSparks43/747-400#117]
I noticed that the main gear bounces a lot, even on smooth -100 fpm landings. In the real 747 it only bounces on hard landings, say  -600 fpm. Compare it to these landings: https://www.youtube.com/watch?v=9fGQL7rBH8Q where you can see the landing gear just settles it down without bouncing.

**Comment by mSparks43** [comment]
This "should" be fixed with the removal of the metal skids that ship with default.
