### ISSUE TITLE
Autoland

### ISSUE THREAD

**Issue by MCCVeen** [mSparks43/747-400#119]
When in the 747 on final approach established on the ILS with at least 2 autopilots in command the Autoland feature will become active not earlier than passing 1500 feet AGL. This is also the moment where FLARE and ROLLOUT mode are armed. In the mod autoland will be enabled asap despite the altitude, so even before 1500 ft AGL. LAND 2 or LAND 3 are also annunciated in the mod even when ILS and 2 autopilots are selected below 1500 feet agl but despite it saying land 2 or land 3 flare and rollout mode are not armed. In this case NO AUTOLAND would be annunciated. See https://www.youtube.com/watch?v=rBL7Hjjf4II as reference for a normal autoland

Also Rollout mode should follow the centerline by using rudder. This is currently not simulated yet as of build 12/04 00:45 

Here I explain a bit more on what goes wrong in the mod with the autoland: https://www.youtube.com/watch?v=uOm2Hh08ZyA

**Comment by mSparks43** [comment]
2.57 in
https://github.com/mSparks43/747-400/issues/656

![image](https://user-images.githubusercontent.com/6773686/147718739-8a24fea5-7dc3-4e30-ba10-db4628a982b1.png)

![image](https://user-images.githubusercontent.com/6773686/147718756-83de5116-f009-401c-972b-06af55ffad49.png)

**Comment by mSparks43** [comment]
fixed in 2.2RC
