### ISSUE TITLE
Landing gear showing though cabin floor

### ISSUE THREAD

**Issue by jmsantafe** [mSparks43/747-400#12]
<img width="2048" alt="Screen Shot 2020-06-25 at 1 49 31 PM" src="https://user-images.githubusercontent.com/67196086/85782607-4dade300-b6ec-11ea-9b6f-ad482e0534e0.png">
The tires are showing up though the floor. gear is retracted.

**Comment by mSparks43** [comment]
Fixed in commit https://github.com/mSparks43/747-400/commit/d068a77074d757270ab755c4923c2a06a2eacaac

![image](https://user-images.githubusercontent.com/6773686/86284852-eb6d4a80-bbe3-11ea-8856-f1299520d55f.png)
