### ISSUE TITLE
Autobrake Disarm on rollout

### ISSUE THREAD

**Issue by MCCVeen** [mSparks43/747-400#121]
When you are in your rollout phase and are using autobrakes, once you put manual braking pressure in you will disarm the autobrake (which is what happens now in the mod as well, good so far). But, the switch will turn itself from Autobrake (whichever is selected; RTO, 1, 2, 3 , 4 or MAX) to the Disarm position, and a CAS advisory will be displayed with "AUTOBRAKES"
![image](https://user-images.githubusercontent.com/75425109/101227308-af10af80-3697-11eb-9451-0a2b69178fa2.png)

**Comment by mSparks43** [comment]
Fixed in current version
