### ISSUE TITLE
Disengaging A/P gets rid of FD guidance

### ISSUE THREAD

**Issue by MCCVeen** [mSparks43/747-400#122]
So whenever I disengage the autopilot, it also gets rid of all the Flight Director guidance (including the autothrottle for some reason, which is odd because the autothrottle is a completely different system to the autopilot and Flight Directors). This doesn't happen in real life and is really annoying when you're on an ILS on short final

**Comment by oMrSmith** [comment]
I agree. Getting this issue fixed soon, would be a huge step forward with the AP
which has already gained several significant improvements recently.
