### ISSUE TITLE
Autopilot reacts too slow

### ISSUE THREAD

**Issue by MCCVeen** [mSparks43/747-400#124]
The autopilot reacts to slow to roll and pitch modes, making turns very easy to overshoot. It often also tries to get back to the magenta line but reacts too late and goes through the path having to return again. Also when accelerating at FL100 from 250 to, let's say 320 knots, both FlightLevel Change mode and VNAV are too late pitching up again when reaching 320 knots, making it overshoot often by 20 knots.

**Comment by oMrSmith** [comment]
I agree on the pitch modes: FLC and VNAV SPD could pitch more eagerly to avoid overspeeds...

**Comment by mSparks43** [comment]
Turns "hopefully" fixed by the new ailerons.
Pitch rate is limited by approach (any faster and it is more likely to lose the glideslope), but improved with the new ECC code.
Can revisit this if it still persists, last tuned 2021-03-22
