### ISSUE TITLE
Small VNAV issue

### ISSUE THREAD

**Issue by MCCVeen** [mSparks43/747-400#125]
Not really an issue or a bug, more something that's slightly wrong. VNAV Descend Speed Transitition on the 747-400 is 250/10000, but in the mod it's 240/10000. Maybe you've seen 240/10000 in the zibo but the 74 actually uses 250 :) 
![image](https://user-images.githubusercontent.com/75425109/101228715-2dbc1b80-369d-11eb-87de-65f4bfcaa9db.png)

**Comment by flfy** [comment]
wrong FCOM reference, but fixed in #149

https://downloadoc.com/v/50378/download-747-flight-crew-operations-manual.html

pg. 908
![image](https://user-images.githubusercontent.com/24484463/101302582-97edd100-3801-11eb-8d27-de347b901503.png)

**Comment by MCCVeen** [comment]
> wrong FCOM reference, the one provided is for ENG OUT on T/O but fixed in #149
> 
> https://downloadoc.com/v/50378/download-747-flight-crew-operations-manual.html
> 
> pg. 908
> ![image](https://user-images.githubusercontent.com/24484463/101302582-97edd100-3801-11eb-8d27-de347b901503.png)

Yes I know, I couldn't find the one I was looking for at the time but did find that Engine Out reference. Thanks anyway :)
