### ISSUE TITLE
Autobrake RTO memo on EICAS not displaying untill TOGA

### ISSUE THREAD

**Issue by MCCVeen** [mSparks43/747-400#131]
So when I set the AB switch to RTO the memo isn't displayed. Photo was taken after start, and found out on take-off roll that once I hit the TOGA button the memo appeared
https://www.youtube.com/watch?v=fhszA2oog6Q
![image](https://user-images.githubusercontent.com/75425109/101266779-96190480-3752-11eb-96fa-86cf4376c1e1.png)

**Comment by flfy** [comment]
fixed in https://github.com/mSparks43/747-400/pull/147 (merged)

**Comment by MCCVeen** [comment]
> fixed in #147 (merged)

Thanks!
