### ISSUE TITLE
Range Arcs not actually on the display but rather an object(?)

### ISSUE THREAD

**Issue by MCCVeen** [mSparks43/747-400#133]
I noticed the range arcs actually aren't part of the screen and looks to be an object, as it changes lightning with the cockpit once it gets dark
![747-400 ND keeps displaying range arcs](https://user-images.githubusercontent.com/75425109/101267015-bea1fe00-3754-11eb-89de-6244a1deb009.png)
![747-400 ND keeps displaying range arcs 1](https://user-images.githubusercontent.com/75425109/101267016-bfd32b00-3754-11eb-96d1-8ce5fd69f441.png)
![747-400 ND keeps displaying range arcs 2](https://user-images.githubusercontent.com/75425109/101267019-c06bc180-3754-11eb-8799-34a9c2f57c4d.png)
![747-400 ND keeps displaying range arcs 3](https://user-images.githubusercontent.com/75425109/101267020-c1045800-3754-11eb-901b-c1cd64c79948.png)
![747-400 ND keeps displaying range arcs 4](https://user-images.githubusercontent.com/75425109/101267021-c19cee80-3754-11eb-91ab-f68f4ba94677.png)
![747-400 ND keeps displaying range arcs 5](https://user-images.githubusercontent.com/75425109/101267022-c2358500-3754-11eb-9f7f-ae59d2bc6727.png)
![747-400 ND not actually part of the display](https://user-images.githubusercontent.com/75425109/101267104-a1216400-3755-11eb-8441-322b62afbe5c.png)

**Comment by Marauder2882** [comment]
The range arcs are not part of the this 747-400 mod.  It has been found that they come from the 3rd party plugin TerrainRadar.  Please configure that plugin according to the developer's guidelines or remove it.  The range arcs can be turned off via the plugin menu.

**Comment by DrGluck** [comment]
It looks like my plugin draws these arches. Disable this option for 747.
It seems to me that in the future, this should be drawn by the plane itself.

**Comment by crazytimtimtim** [comment]
@Matt726-S Do you think you can make a texture for this?

**Comment by mSparks43** [comment]
Fixed by terrain radar update, huge thanks @DrGluck
