### ISSUE TITLE
ND PLN to MAP causes center function on

### ISSUE THREAD

**Issue by MCCVeen** [mSparks43/747-400#137]
When you switch from PLN to MAP on the ND, the center function is automatically turned on even if it wasn't before turning to PLN. In the real thing when switching from PLN to ND (and the center function wasn't turned on) it would have the ctr function off.

**Comment by Marauder2882** [comment]
This is likely due to only having one EFIS in the default plane (i.e. not a separate one for CAPT & FO).  Thus, the switches on the two sides fight with each other on what should be displayed.

**Comment by mSparks43** [comment]
See #245
