### ISSUE TITLE
Mach numbers with a third decimal not selectable

### ISSUE THREAD

**Issue by MCCVeen** [mSparks43/747-400#144]
Only mach numbers with a second decimal are available in the mod. In real life you can also select third decimals. See this picture for reference: 
![image](https://user-images.githubusercontent.com/75425109/101268120-0a0dd980-3760-11eb-83e1-ba54b4398e1f.png)

**Comment by mSparks43** [comment]
Select it via page 2 of VNAV
![image](https://user-images.githubusercontent.com/6773686/102047457-90b85b80-3ddd-11eb-92d8-4d0c4442ce32.png)
the MCP only has 3 digits, one of which is a decimal point when showing mach
