### ISSUE TITLE
Clock Timer

### ISSUE THREAD

**Issue by MCCVeen** [mSparks43/747-400#146]
The Timer on the clock should be blanked when no time has been recorded
![image](https://user-images.githubusercontent.com/75425109/101270935-5d8f2000-377e-11eb-8894-6e65dd5cb09e.png)

![image](https://user-images.githubusercontent.com/75425109/101270931-4ea86d80-377e-11eb-8a94-8874be9fd1e7.png)

**Comment by crazytimtimtim** [comment]
ET or CHR?

**Comment by MCCVeen** [comment]
> ET or CHR?

What do you mean? When absolutely no time is displayed, the ET/CHR window should be blank instead of showing 00:00

**Comment by crazytimtimtim** [comment]
Ok. I think I understand.

**Comment by MCCVeen** [comment]
> Ok. I think I understand.

Here's an example of what it should look like:
![image](https://user-images.githubusercontent.com/75425109/116771557-bcff0c80-aa4c-11eb-9db8-5a45e662443f.png)

**Comment by MCCVeen** [comment]
@mSparks43 Still there in the latest version

![image](https://user-images.githubusercontent.com/75425109/120087317-16f40000-c0e7-11eb-9554-120b24d05dd5.png)

**Comment by MCCVeen** [comment]
@crazytimtimtim ^

**Comment by crazytimtimtim** [comment]
Yeah, that pull request doesn't fix it. I have a "part 2" coming soon that will, I just need to figure out something first.

Basically, look at line 146852 and 147084. The FO clock uses `SHOW_EQUAL` while the captain's uses `SHOW_LESS` (meaning it will show the digits if a dataref = something or is < something respectively.) I guess it works the way it is, but I'd like to figure out which to use and use it for both.
