### ISSUE TITLE
X-plane stops responding when i select 744?

### ISSUE THREAD

**Issue by A-trainNezar** [mSparks43/747-400#153]
So, whenever I try to load into this new plane, the prompt opens as usual, but x-plane immediately freezes and stops responding until I restart it. I believe I have the aircraft and its necessary software installed correctly.

**Comment by MehdiAzz450** [comment]
> So, whenever I try to load into this new plane, the prompt opens as usual, but x-plane immediately freezes and stops responding until I restart it. I believe I have the aircraft and its necessary software installed correctly.

Which version of X-plane do u have?

**Comment by A-trainNezar** [comment]
@MehdiAzz450 sorry I should have said 11.5

**Comment by MehdiAzz450** [comment]
> @MehdiAzz450 sorry I should have said 11.5

When the black window opens do u close it

**Comment by MehdiAzz450** [comment]
If not try to redownload the plane

**Comment by A-trainNezar** [comment]
I haven't closed it, I'll reinstall the aircraft now

**Comment by MehdiAzz450** [comment]
> > So, whenever I try to load into this new plane, the prompt opens as usual, but x-plane immediately freezes and stops responding until I restart it. I believe I have the aircraft and its necessary software installed correctly.
> 
> Which version of X-plane do u have?

Do u close the black window that pops up, if not try downloading the plane again

**Comment by A-trainNezar** [comment]
just tried again and still not working... always occurs when X-plane tries to load the .acf for the aircraft

**Comment by crazytimtimtim** [comment]
Do you still have the problem @A-trainNezar ?

**Comment by A-trainNezar** [comment]
No, it works like a dream now!

**Comment by crazytimtimtim** [comment]
@A-trainNezar 
> No, it works like a dream now!

Ok! You can close this issue then.

**Comment by crazytimtimtim** [comment]
wanna close this @mSparks43 ?

**Comment by crazytimtimtim** [comment]
@mSparks43 Is this gonna be closed?
