### ISSUE TITLE
SSB not working

### ISSUE THREAD

**Issue by MCCVeen** [mSparks43/747-400#156]
It looks like the SSB is not working. On some stands/gates only 1 external power is available (so that would be External Power #1) so I turned on EXT PWR 1 which should give complete power to all 4 buses because the SSB will automatically connected, yet it didn't. See images below for reference
![747-400 SSB 1](https://user-images.githubusercontent.com/75425109/101417187-9698d300-38eb-11eb-83e1-65a7a9291ce6.png)
![747-400 SSB 2](https://user-images.githubusercontent.com/75425109/101417189-97ca0000-38eb-11eb-925a-421ffef80616.png)
![747-400 SSB 3](https://user-images.githubusercontent.com/75425109/101417191-98629680-38eb-11eb-805e-ad4d80976d78.png)
![747-400 SSB 4](https://user-images.githubusercontent.com/75425109/101417193-98fb2d00-38eb-11eb-8c9e-91d01401d788.PNG)
![747-400 SSB 5](https://user-images.githubusercontent.com/75425109/101417194-98fb2d00-38eb-11eb-882f-7ace589df7b4.PNG)

**Comment by mSparks43** [comment]
not 100% sure about this. tutorial videos say the ssb is only closed when running on engines.
For gates with only one external you probably need to start the apu to get power to both sides.

**Comment by MCCVeen** [comment]
> not 100% sure about this. tutorial videos say the ssb is only closed when running on engines.
> For gates with only one external you probably need to start the apu to get power to both sides.

Can you send me that video? Because that's not how it is irl. I mean think about it. How would you power both sides when the APU is unavailable due to a failure or something? Also on most big airports use of APU is forbidden till a few minutes before start and a few minutes after shutdown so you have to use the gpu

**Comment by mSparks43** [comment]
better source

https://www.slideshare.net/mobile/theoryce/b747-electrical-power

ssb needs to close if one side is powered
