### ISSUE TITLE
Random AC power to bus 3

### ISSUE THREAD

**Issue by MCCVeen** [mSparks43/747-400#157]
So I just reported that the SSB isn't working, and I showed that with EXT PWR 1 on and the battery and standby power off. When I turned the Battery and Stby pwr back on I noticed that the rest of the screens on the FO side came back on, which should be impossible given that the SSB doesn't work. So I checked the ELEC synoptic and it said that even tho the SSB was closed some random power that doesn't lead to anything is providing ac power to bus 3. See pictures below

![747-400 SSB bug 1](https://user-images.githubusercontent.com/75425109/101418216-9ef20d80-38ed-11eb-9dc9-78300b601f86.png)
![747-400 SSB bug 2](https://user-images.githubusercontent.com/75425109/101418221-9f8aa400-38ed-11eb-97c4-37e00ba0f24d.png)
![747-400 SSB bug 3](https://user-images.githubusercontent.com/75425109/101418223-a0bbd100-38ed-11eb-8ba4-647ebafb6882.png)

**Comment by mSparks43** [comment]
With the CBT offline the best visual guide I have is
https://youtu.be/3aFwevsnhLo
and the doc donaldson videos.
aiui
Capt screens are powered with just the battery on. default bus 3, standby bus one.

FO screens are powered by bus 2 fallback bus one

fallback only if standby power is selected.

The green on 3 came in from adding the capt displays on with just battery power and also selective displays update.

Need to revisit the documents and tutorial videos and make sure everything now agrees and tune exactly where its out.

**Comment by MCCVeen** [comment]
> With the CBT offline the best visual guide I have is
> https://youtu.be/3aFwevsnhLo
> and the doc donaldson videos.
> aiui
> Capt screens are powered with just the battery on. default bus 3, standby bus one.
> 
> FO screens are powered by bus 2 fallback bus one
> 
> fallback only if standby power is selected.
> 
> The green on 3 came in from adding the capt displays on with just battery power and also selective displays update.
> 
> Need to revisit the documents and tutorial videos and make sure everything now agrees and tune exactly where its out.

I'll discuss this tomorrow with my dad. I gave him these screenshots and he confirmed that this is an impossible situation

**Comment by mSparks43** [comment]
https://youtu.be/7gx0PVJ1nWg
