### ISSUE TITLE
Engine cuts out during long hauls.

### ISSUE THREAD

**Issue by zak001-h** [mSparks43/747-400#158]
I was doing a flight from EHAM-KSFO, when i hit North A merica eng.3 cuts out and i can't restart it, then it doesnt use all the fuel , i usually have to add fuel in every 4 hrs during a long haul which is preety annoying. Then after 8hrs of flying my autopilot start pitching up and stalling then crashes. Hope you can fix the fuel and engine problems.

**Comment by mSparks43** [comment]
do you have a video of the flight?
did you go direct to engine fuel when indicated to do so by the CAS?

**Comment by MCCVeen** [comment]
Saw the same happening here on a livestream: https://www.twitch.tv/videos/810753647?filter=archives&sort=time

**Comment by zak001-h** [comment]
i don't have a vid but one engine always cuts off during every long haul i
did and the fuel usually runs out only after 4-5hrs of flight time so i
have to keep adding fuel.

**Comment by mSparks43** [comment]
> Saw the same happening here on a livestream: https://www.twitch.tv/videos/810753647?filter=archives&sort=time

Thats MSFS....

> did and the fuel usually runs out only after 4-5hrs

8 hour test flight:
https://www.youtube.com/watch?v=Nl0MBW18byE

**Comment by mSparks43** [comment]
> Saw the same happening here on a livestream: https://www.twitch.tv/videos/810753647?filter=archives&sort=time

fuel imbalance 1-4
looks like he ran out of fuel in the tanks selected to feed the engines.

**Comment by zak001-h** [comment]
it's something with the aircraft cause when i check the fuel page it says
all engines have fuel including the central tank and yet an engine still
cuts off mid flight.

**Comment by mSparks43** [comment]
> cause when i check the fuel page it says

with the cas page free of warnings of impending death?

**Comment by zak001-h** [comment]
Yes the Cas page is free of all warnings and doesn't say low fuel, there
are no warnings but the engine just shuts off mid flight and cant restart
whatsoever.

**Comment by mSparks43** [comment]
never seen this, if it doesn't say low fuel why are you adding more?

**Comment by zak001-h** [comment]
Because from pass experiences it usually would cut off two engines at
around 123.00 kg of fuel so i add fuel so that the engines dont cut off.In
september i was doing a flight KBOS-EHAM and after 7hrs of flight time all
the engines cut off.

**Comment by mSparks43** [comment]
running out of fuel in two engines happens if you ignore cas messages and dont go direct to engine fuelling. The fuel system in the 744 is not fully automated - you have to monitor it and manually manage it during the flight according to the fcom.

This isnt to say something else isnt happening, lots of things can go wrong.
But things described in the fcom actually happening aren't aircraft issues.
