### ISSUE TITLE
ELEC syn fonts and colors

### ISSUE THREAD

**Issue by MCCVeen** [mSparks43/747-400#159]
Can the font of "Utility" and "Galley" be corrected? They have the same height as the other font on the display and they're both the same size, so galley is not as big as utility while being a shorter word. Also "BUS _" on the display has a green or amber color depending on if the bus is powered or not. The outside box for the buses already have this method but the "BUS _" in it doesn't yet. Also the other boxes (BUS TIE ISLN, GEN CONT OFF and DRIVE TEMP/PRESS) are missing the amber and green colors around them and DRIVE TEMP/PRESS is a bit too big for the box and therefor has to be reduced in size. 

![747-400 Elec Syn](https://user-images.githubusercontent.com/75425109/101420060-bd5a0800-38f1-11eb-87f8-c694f6b810df.png)
![747-400 SSB 4](https://user-images.githubusercontent.com/75425109/101420069-c1862580-38f1-11eb-9496-93b5a120dfca.PNG)

**Comment by mSparks43** [comment]
https://github.com/mSparks43/747-400/blob/master/cockpit_3d/generic/CRT%20Displays/EICAS%20Lower/ELEC/busgreenl-1.png
https://github.com/mSparks43/747-400/blob/master/cockpit_3d/generic/CRT%20Displays/EICAS%20Lower/ELEC/busgreenr-1.png
https://github.com/mSparks43/747-400/blob/master/cockpit_3d/generic/CRT%20Displays/EICAS%20Lower/ELEC/busamberl-1.png
https://github.com/mSparks43/747-400/blob/master/cockpit_3d/generic/CRT%20Displays/EICAS%20Lower/ELEC/busamberl-1.png

src image
https://github.com/mSparks43/747-400/blob/master/cockpit_3d/generic/CRT%20Displays/EICAS%20Lower/ELEC/display.xcf

**Comment by Matt726-S** [comment]
forgot to say this was fixed a few weeks back
