### ISSUE TITLE
Speedbrakes go to Flight Detent on touchdown

### ISSUE THREAD

**Issue by MCCVeen** [mSparks43/747-400#162]
Upon touchdown with the speedbrakes armed the lever often deploys to flight detent, but the actual speedbrakes go fully up. The speedbrake lever should go to the UP position. If it would actually be in Flight Detent, the speedbrakes would only be deployed half way as is seen in-flight.
![747-400 speedbrakes go to flt dtnt instd of up](https://user-images.githubusercontent.com/75425109/101566700-b73a5900-39cf-11eb-92b6-99319976c287.png)
![747-400 speedbrakes go to flt dtnt instd of up 1](https://user-images.githubusercontent.com/75425109/101566703-b9041c80-39cf-11eb-954e-396e65ee66a8.png)
![747-400 speedbrakes go to flt dtnt instd of up 2](https://user-images.githubusercontent.com/75425109/101566708-bb667680-39cf-11eb-8373-761f43609597.png)

**Comment by flfy** [comment]
duplicate https://github.com/mSparks43/747-400/issues/118
