### ISSUE TITLE
Master Caution sound keeps repeating itself

### ISSUE THREAD

**Issue by MCCVeen** [mSparks43/747-400#163]
The master caution sound keeps repeating itself every 5 seconds. In the 747 it would only sound once
![image](https://user-images.githubusercontent.com/75425109/101568440-df778700-39d2-11eb-9b1f-3ea8cf127a43.png)

**Comment by mSparks43** [comment]
love a good source for this, its gone back and forth a couple of times.
It started only sounding once and then watching start up videos it seemed to repeat until the reset switch was pressed.

**Comment by MCCVeen** [comment]
> love a good source for this, its gone back and forth a couple of times.
> It started only sounding once and then watching start up videos it seemed to repeat until the reset switch was pressed. someone also said the sound is wrong

nope it sounds only once :)

**Comment by mSparks43** [comment]
got it.
master warning loops, master caution once. sounds look good.
obetmaz videos airspeed low warning and master warning on takeoff
