### ISSUE TITLE
Flight plan coruption when using 124thATC

### ISSUE THREAD

**Issue by Errandil85** [mSparks43/747-400#170]
When I try to fly with 124thATC it corrupts the flight plan.

Before filing flight plan
 
![image](https://user-images.githubusercontent.com/30469177/101992322-aa10b900-3cb2-11eb-95c9-9f732e3d6f5d.png)

![image](https://user-images.githubusercontent.com/30469177/101992333-b85ed500-3cb2-11eb-959a-a4b3175cd2b5.png)

After submitting the flight plan

![image](https://user-images.githubusercontent.com/30469177/101992356-e3492900-3cb2-11eb-9b37-d0b681aec775.png)

![image](https://user-images.githubusercontent.com/30469177/101992360-e6441980-3cb2-11eb-9d31-798cc63528d0.png)

**Comment by mSparks43** [comment]
need to file this with 124thATC, LNAV is xplane default.
