### ISSUE TITLE
Stabilizer trim issues at low TOW

### ISSUE THREAD

**Issue by MCCVeen** [mSparks43/747-400#174]
On take offs with a low gross weight I get stabilizer config warnings with the stabilizer trim in the green band and the calculated take-off trim is too low
![747-400 config stab 1](https://user-images.githubusercontent.com/75425109/102042610-8e9ccf80-3dd2-11eb-9e35-89dcc8c45ea4.png)
![747-400 config stab 2](https://user-images.githubusercontent.com/75425109/102042611-8fcdfc80-3dd2-11eb-94be-711a5f0ce1b3.png)
![747-400 config stab 3](https://user-images.githubusercontent.com/75425109/102042613-90ff2980-3dd2-11eb-8d1d-b4ab5568d2ae.png)

https://drive.google.com/file/d/1A4c_qlGOgjI9hTZ1TEH9WbHSu-ELFUgQ/view?usp=sharing

**Comment by Marauder2882** [comment]
This should be resolved in the current MASTER branch if the plane is loaded via the FMC and the Gross Weight is entered in the PERF INIT page.
