### ISSUE TITLE
Vmc still too high at MTOW

### ISSUE THREAD

**Issue by MCCVeen** [mSparks43/747-400#175]
Taking off with a GW of 412 tonnes
![747-400 vmc too high at mtow](https://user-images.githubusercontent.com/75425109/102043018-a3c62e00-3dd3-11eb-9607-fd15907a06e0.png)

**Comment by mSparks43** [comment]
This looks right to me. PSX has
![image](https://user-images.githubusercontent.com/6773686/102044469-269cb800-3dd7-11eb-8200-b5285c8fe91c.png)

**Comment by MCCVeen** [comment]
Gross Weight there is 396, mine is 412 which is the MTOW of the X-Plane 747 according to the W&B menu

> This looks right to me. PSX has
> ![image](https://user-images.githubusercontent.com/6773686/102044469-269cb800-3dd7-11eb-8200-b5285c8fe91c.png)

**Comment by MCCVeen** [comment]
Just recreated this scenario in X-Plane, seems like Vs, Vmc, Flap 10 speeds, Flap 20 speeds and most notably pitch attitude all needs some work
![747-400 psx comparison](https://user-images.githubusercontent.com/75425109/102047296-4b942980-3ddd-11eb-9d3d-b5f33eb6b6eb.png)

**Comment by mSparks43** [comment]
a heavier weight has a higher Vmc

**Comment by MCCVeen** [comment]
> a heavier weight has a higher Vmc the others have been confirmed against published numbers.
> 
> now, when it actually does stall is a different story, flights tests on that are still to do.
> your V2 in the first screenshot is 183, so at worst its a couple of knots out at 184.
> 
> ill add a min function -2 below 1500 feet to make sure vmc is always less than v2 at takeoff.

Have a look here at a MTOW departure at 412 tonnes: https://www.youtube.com/watch?v=2hzSGN19v8U

**Comment by mSparks43** [comment]
> Have a look here at a MTOW departure at 412 tonnes

that has red tape to at least 180kts, yellow looks like 185?

**Comment by mSparks43** [comment]
also, mtow in the 400 is 397 tons, thats probably an ER

**Comment by MCCVeen** [comment]
> > Have a look here at a MTOW departure at 412 tonnes
> 
> that has red tape to at least 180kts, yellow looks like 185?

It looks like there's no Vmc tape at all

**Comment by MCCVeen** [comment]
> also, mtow in the 400 is 397 tons, thats probably an ER

Yeah it's an 400ER just like the mod

**Comment by mSparks43** [comment]
> Yeah it's an 400ER just like the mod

current version is targeting the 400GE (General Electric CF6 engines).
Early plan was ER, but dont have any of the numbers for that

**Comment by MCCVeen** [comment]
> > Yeah it's an 400ER just like the mod
> 
> current version is targeting the 400GE (General Electric CF6 engines).
> Early plan was ER, but dont have any of the numbers for that
> also the air china ones are unique with lots of 777 parts

the CF6s also support the 400ER, just the RR engines aren't compatible. In the case you want to change it from an ER to a normal 400 you gotta change the weights, only ERs have a TOW of 412 tonnes

**Comment by mSparks43** [comment]
> > > Yeah it's an 400ER just like the mod
> > 
> > 
> > current version is targeting the 400GE (General Electric CF6 engines).
> > Early plan was ER, but dont have any of the numbers for that
> > also the air china ones are unique with lots of 777 parts
> 
> the CF6s also support the 400ER, just the RR engines aren't compatible. In the case you want to change it from an ER to a normal 400 you gotta change the weights, only ERs have a TOW of 412 tonnes

little more to it than that.
the data tables used for things like the V speeds are only valid to 397t for example.

Breaking out into variants is definitely wanted, but doing so means duplicating effort - see this now with the LCF which is always lagging well behind the main acf in master.

That is also why the CF6 was picked, its easier to go to the other variants from when its done. Still hoping to do them by livery after the next release once core issues are sorted. So I might create a new milestone "version 2" and add this one to it

**Comment by mSparks43** [comment]
Ibelieve this is now fixed

**Comment by MCCVeen** [comment]
> Ibelieve this is now fixed

Take a look at this, Boeing made a simple fix for this to prevent unnecessary AIRSPEED LOW warnings after taking off: #584

**Comment by crazytimtimtim** [comment]
> This looks right to me. PSX has

PSX?

**Comment by mSparks43** [comment]
> > This looks right to me. PSX has
> 
> PSX?

https://aerowinx.com/
