### ISSUE TITLE
FMC error

### ISSUE THREAD

**Issue by aeroboss13** [mSparks43/747-400#176]
On-board computer problem
When the plane starts, 0 is displayed on the FMC and I cannot enter the flight plan settings. Required libraries installed and C ++ too
help to solve the problem
![sikMYY62jS8](https://user-images.githubusercontent.com/61287279/102081403-3a6d0c00-3e21-11eb-9a01-93767d40d5f9.jpg)
![sXdjTFUPJbk](https://user-images.githubusercontent.com/61287279/102081406-3c36cf80-3e21-11eb-8fe4-56a1853b0ae1.jpg)

**Comment by mSparks43** [comment]
did the "why is my fmc blank" in troubleshooting of
https://github.com/mSparks43/747-400/blob/master/README.md
not help?

**Comment by aeroboss13** [comment]
> сделал ли вопрос "почему мой fmc пуст" в устранении неполадок
> https://github.com/mSparks43/747-400/blob/master/README.md
> не поможет?

The fact is that the FMC is working and power is supplied to it, but I cannot insert my flight plan because when I press the fmc, my screen turns black. I can record video if necessary

**Comment by mSparks43** [comment]
> > сделал ли вопрос "почему мой fmc пуст" в устранении неполадок
> > https://github.com/mSparks43/747-400/blob/master/README.md
> > не поможет?
> 
> The fact is that the FMC is working and power is supplied to it, but I cannot insert my flight plan because when I press the fmc, my screen turns black. I can record video if necessary

please, video would really help recreate it

**Comment by aeroboss13** [comment]
> > > сделал ли вопрос "почему мой fmc пуст" в устранении неполадок
> > > https://github.com/mSparks43/747-400/blob/master/README.md
> > > не поможет?
> > 
> > 
> > Дело в том, что FMC работает, и к нему подается питание, но я не могу вставить свой план полета, потому что, когда я нажимаю fmc, мой экран становится черным. Я могу записать видео, если это необходимо
> 
> пожалуйста, видео действительно помогло бы воссоздать его





https://drive.google.com/file/d/1ecrg-ePMSC7lZISUUZARnOyEm1J4JTEV/view?usp=sharing

**Comment by mSparks43** [comment]
This looks like some kind of strange install issue, is this release or master? did it give you an error when you clicked and it went black in the black console window that pops up when it starts?

**Comment by mSparks43** [comment]
And possibly, which version of X-Plane are you using? I think the FMC API might be an 11.40 or 11.50 thing.

**Comment by aeroboss13** [comment]
> And possibly, which version of X-Plane are you using? I think the FMC API might be an 11.40 or 11.50 thing.

I think that the problem is that I have 11.53b and I need to find a version that fits the model

**Comment by aeroboss13** [comment]
And it's master version

**Comment by crazytimtimtim** [comment]
Are you still having the problem?

**Comment by crazytimtimtim** [comment]
😕 I haven't seem this anywhere else and @aeroboss13 hasn't responded. Maybe close this @mSparks43?
