### ISSUE TITLE
ILS autotuning

### ISSUE THREAD

**Issue by MCCVeen** [mSparks43/747-400#180]
I noticed that the ILS is autotuning random ILS frequencies, while the NAV RAD page displays PARK. Normal behaviour when the ILS is autotuned is that it autotunes the ILS for the arrival runway selected in the FMC if there is an ILS/LOC frequency available for it. When an ILS is autotuned, this is displayed on the NAV RAD page in the FMC
![747-400 autotuning ILS but NAV RAD saying nothing is active](https://user-images.githubusercontent.com/75425109/102263558-c2800e00-3f14-11eb-87d4-94d729876721.png)

**Comment by mSparks43** [comment]
not clear which ils indicator is being referred to here, assuming this means the gs and loc pointers on the pfd closing as fixed in https://github.com/mSparks43/747-400/commit/e5ccd4a9aeb5d9ea3ae0b0ed0a7811963c77494c

plse reopen if it referred to something else.
