### ISSUE TITLE
QNH always preselected

### ISSUE THREAD

**Issue by MCCVeen** [mSparks43/747-400#182]
The QNH is always preset on the PFD. Normally when you set standard altimeter the PFD would only say STD with nothing below it. Once you start cycling the altimeter on the EFIS panel it will show you your preset altimeter which if you press STD again will be set as your altimeter
![747-400 showing VS bug when VS not selected and QNH when not prematurily set](https://user-images.githubusercontent.com/75425109/102266764-30c6cf80-3f19-11eb-8576-b4be99110a5d.png)
![image](https://user-images.githubusercontent.com/75425109/102268915-3245c700-3f1c-11eb-848f-283841d57276.png)
![image](https://user-images.githubusercontent.com/75425109/102268934-38d43e80-3f1c-11eb-9b6c-40521d287f83.png)

**Comment by mSparks43** [comment]
![image](https://user-images.githubusercontent.com/6773686/114324165-f1a43600-9b28-11eb-9315-a66628c2b646.png)

**Comment by mSparks43** [comment]
![image](https://user-images.githubusercontent.com/6773686/114324202-3039f080-9b29-11eb-841a-1cd38fa2c79a.png)
