### ISSUE TITLE
No ELEC GEN OFF _ caution

### ISSUE THREAD

**Issue by MCCVeen** [mSparks43/747-400#183]
For some unknown reason, generator 3 is off. Here I didn't get an ELEC GEN OFF 3 caution with a beeper sound.
![747-400 no ELEC GEN OFF _ caution](https://user-images.githubusercontent.com/75425109/102274105-9fa92600-3f23-11eb-9bdd-0b76020f066e.png)
![747-400 no ELEC GEN OFF _ caution 1](https://user-images.githubusercontent.com/75425109/102274111-a172e980-3f23-11eb-85ac-bbb553239778.png)

**Comment by mSparks43** [comment]
fixed in https://github.com/mSparks43/747-400/commit/c6f322fc45fb5eb0758bc171af2f75ba7465f402
