### ISSUE TITLE
Waypoint missing in FMC

### ISSUE THREAD

**Issue by MCCVeen** [mSparks43/747-400#186]
Waypoints all the way at the top in the legs page are missing due to current position being there for some reason? 
![747-400 waypoint missing in FMC](https://user-images.githubusercontent.com/75425109/102424865-61d3fc80-400c-11eb-9154-babdac96dff9.png)

**Comment by mSparks43** [comment]
Hmmm, can't recreate this
Page 1
![image](https://user-images.githubusercontent.com/6773686/102700269-3d666300-424c-11eb-852f-79c67e271064.png)
Page 2
![image](https://user-images.githubusercontent.com/6773686/102700276-4ce5ac00-424c-11eb-8959-2ead56f2cbfb.png)

might be the double digits of page numbers, if you can attach the .FMS for this I can take another look

**Comment by mSparks43** [comment]
More detail in #724
