### ISSUE TITLE
Bank Limit FD

### ISSUE THREAD

**Issue by MCCVeen** [mSparks43/747-400#188]
The Bank Limit for the FD is completely off. Once you start a turn it just goes to the left or right without limit, instead of following the bank limit which the autopilot seems to follow (although very basic). Even if the bank limit is currently a placeholder, can this already be integrated for the FD? So that we don't screw up when flying her manually :P
![747-400 Autopilot and FD bank angle 1](https://user-images.githubusercontent.com/75425109/102445436-c5b9ed80-402b-11eb-9f05-33b3a101d404.png)
![747-400 Autopilot and FD bank angle](https://user-images.githubusercontent.com/75425109/102445438-c6eb1a80-402b-11eb-9726-6e02e4d9b7e1.png)
![747-400 Lateral FD bank angle](https://user-images.githubusercontent.com/75425109/102445442-c81c4780-402b-11eb-87ae-a11c6d72ef4f.png)

**Comment by mSparks43** [comment]
bit of extra logic on this should be achievable
