### ISSUE TITLE
STAT page flight control errors

### ISSUE THREAD

**Issue by Pizzamanje** [mSparks43/747-400#19]
The elevator reaches outside of the line
![R6peZHt](https://user-images.githubusercontent.com/57843032/86292905-e616fc80-bbf1-11ea-886f-58e60011530d.png)

And the spoilers only move while I move the ailerons on the left side 
LEFT:
![DWqw3YD](https://user-images.githubusercontent.com/57843032/86292980-0646bb80-bbf2-11ea-8d2d-d2b33bbf36b1.png)
RIGHT:
![Ebc4wbr](https://user-images.githubusercontent.com/57843032/86292998-11015080-bbf2-11ea-8d16-d403a26b8124.png)

**Comment by mSparks43** [comment]
fixed
