### ISSUE TITLE
COM Radio ATIS not playing

### ISSUE THREAD

**Issue by vipt26** [mSparks43/747-400#194]
Cannot get any sound for ATIS when tuned into the ATIS frequency.  Tried at EGKK.

**Comment by mSparks43** [comment]
xplane atis audio or from a plugin like autoatc?

**Comment by vipt26** [comment]
I was using pilot2atc and there is a tick box in there to use pilot2atc for atis, if I click this then it gives me atis.  But on tutorial video I watched someone keep that unchecked and used the xplane radio to hear aria.  Granted this was in a Cessna or something but I assumed it would be possible to tune the com in the plane to atis and hear it without a plugin.

I hope this makes sense.

On 19 Dec 2020 20:59, mSparks <notifications@github.com> wrote:

xplane atis audio or from a plugin like autoatc?

**Comment by mSparks43** [comment]
settings, sound for xplane:
![image](https://user-images.githubusercontent.com/6773686/102700697-19a51c00-4250-11eb-88e9-32e2eb1b2bdd.png)

**Comment by vipt26** [comment]
Yes I thought that was the issue as pilot2atc recommends clearing those boxes, but even after ticking them both I could not get get atis.  Or are you saying I should not have enable verbal ATC messages ticked?

I will try again in the morning, double check the settings and also before I load up pilot2atc just incase.

On 19 Dec 2020 22:15, mSparks <notifications@github.com> wrote:

settings, sound for xplane:
[image]<https://user-images.githubusercontent.com/6773686/102700697-19a51c00-4250-11eb-88e9-32e2eb1b2bdd.png>

**Comment by vipt26** [comment]
Looking at the xplane ATC, it seems that all frequencies are for the current phase (was Tower when I checked) so regardless of the frequency tuned, it was all from Tower.  Therefore I cannot hear the ATIS but I hear the tower comms when the 'Enable Verbal ATC messages' is ticked.  Not sure if there is a way to change this.  In X plane ATC I disabled autotune but this does not resolve this either.

**Comment by mSparks43** [comment]
Looks like a pilot2atc bug, not having it with default or AutoATC
