### ISSUE TITLE
LEGS page; stuck on ACT DIRECT-TO page after doubleclick on LEGS button (FMC)

### ISSUE THREAD

**Issue by izzphil** [mSparks43/747-400#195]
Hi everyone, after doubleclicking the LEGS button on the FMC, it switches to the ACT DIRECT-TO page. I can use the FMC anyways, but even if I switch to another page, as soon as I press the LEGS button it brings me back to the ACT DIRECT-TO page.

**Comment by mSparks43** [comment]
Its a work around to bring it closer to the real one without much work.
In the air its ~default ACT DIRECT-TO, because there is no INT_C button on the FMC, direct to is done via IRL legs
You can access the legs page in the air if you need it via RTE->RTE 2
On the ground its ~default LEGS
