### ISSUE TITLE
Something is bleeding into the clock

### ISSUE THREAD

**Issue by rKsanu2MMYvypWePtQWM** [mSparks43/747-400#196]
![Screenshot_20201220_182701](https://user-images.githubusercontent.com/35463654/102718509-2463bd80-42f1-11eb-8fa7-caa951e91175.png)
this is the captains clock. this does not happen with the other clock.

**Comment by crazytimtimtim** [comment]
Found the issue, seems to be the airspeed barber pole from the pfd.
