### ISSUE TITLE
Few issues from newbie

### ISSUE THREAD

**Issue by mrshiljo** [mSparks43/747-400#199]
Hi! 

Been in sim for a decades, on all sims, and now hooked on XP11 and this magnificent work of yours. I dont have any programing expirience, but i will help you no matter what to make this plane even better, just name it i will learn all ;) 

This is all observations now, on IVAO onoline flight from LIPE to OTHH
Now, few bugs, maybe allready discussed but im too old too search here hehe. So, 

- angle bug for roll on stby horison isnt moving, eg, isnt fixed to moving sky part of stby horizon, rather is fixed to cage. 
<img width="1280" alt="X-Plane Screenshot 2020 12 22 - 12 42 03 67" src="https://user-images.githubusercontent.com/76166015/102885124-28a7ec00-4453-11eb-9ef1-aa5c6e576704.png">

- VNAV speed must be achieved with FADECs and VS together, in this case plane only trying to catch the speed by VS wich is not correct, engines must slow down and climb speed should be smooth, not 7000fpm. Try to make this little bit more slowly, by cutting the power off...
- stall protection must be available, eg, when approaching stall, wich is on this ac quite easy, toga must be applied automatically to thrust, no matter what
- separate engine levers, idont knwo why all designers make all levers on one click, must be separated, to control if wish each engine separately...in case of engine loss
- when select IAS on FCU, and arm it on GND power levers move in forward direction and engines are off, that not the case normally, power levers should not move
- TCAS icons on ND should be rombs with proper indication of relative altitude in 1000s from aircraft, and with TA/RA colors depending on closure, and starting from +/- 3000 inside 40nm
 <img width="1280" alt="X-Plane Screenshot 2020 12 22 - 12 38 32 96" src="https://user-images.githubusercontent.com/76166015/102884909-c222ce00-4452-11eb-802f-c95f555478dd.png">

These 3 are correctly positioned but far from me to been shown on TCAS, all 4000+ ft from my height, and inproper indications on ND

- in cruise , N1 too much vary, i think it should be way more stable, with less oscillations . I never flew in 747 cockpit, but usually it is...
- bank in SIDs is not alligned with projected trajectory...its too small, should be greater maybe...
- EFB screen connected to navigraph also can be achievable, and i think its not an issue, at least option for NAVIGRAPH or chart in local folder...
- no fuel predictions on CRZ page, and it should be, overall FMC needs more work, but on CRZ page should be arrival airport estimated time and fuel remaining...
<img width="1280" alt="X-Plane Screenshot 2020 12 22 - 14 01 12 56" src="https://user-images.githubusercontent.com/76166015/102891264-2dbe6880-445e-11eb-9158-a4b087acf16a.png">
Here is writtern KATL, which is only texture ok...but also parametar to change, and calculated time and fuel remaining should be added

- When you put plan on ND CP to check approach and to manage waypoints,  STEP option should be appeared on last RLSK to go thru every point step by step, here there isnt option...you can just scroll with next page which goes thru several waypoints, also WAYPOINT ID should be present on PLAN on ND and DATA of managed APPR
<img width="1280" alt="X-Plane Screenshot 2020 12 22 - 14 14 52 78" src="https://user-images.githubusercontent.com/76166015/102892410-1da78880-4460-11eb-8afc-4977fbe71cdb.png">
In addition to this, holding pattern must be in different color, lets say cyan and dashed if possible...i dont know correct indication in RL but assuming...

- page number on legs doesnt correspond to real page number, it goes out of range when arrival selected
<img width="1280" alt="X-Plane Screenshot 2020 12 22 - 14 27 44 72" src="https://user-images.githubusercontent.com/76166015/102893536-0d90a880-4462-11eb-97c0-d9a47644e766.png">

- Overall, flight was great...ILS is unstable, ENG thrust is to lazy, when you put finall APPR speed of 145 while it decreas speed it overshoot it and by the time engines reach that speed again it goes to stall, its not real...so AP disconnects in last phase of flight. Also LOC capture is bad...you have to be exactly on it for APPR to capture it, its not ok, regarding position, if u are on ILS beam, LOC must be captured with APPR , and while capture it, it must hold it not have lot of lateral movement along it. But hey, its freeware, its magnificent...I like it...Looking forward to fzture updates and i hope ill be part of them

For all above if im mistaken pls dont judge, just want to help. Im engineer on A320 familly, different type then 747 but logic is simillar>and sim expirience on different 747s from pmdgs and ssg...so...

And off course, not to forget, Freighter model must be achieved in near future ;)

Thank you

P.S.: If u need anything, i could help, just need some pointers what and maybe how, i like to spent time searching codes and troubleshooting, and i like sims, specially 747. So im here...

**Comment by rKsanu2MMYvypWePtQWM** [comment]
You probably would have more success if you separated your issues, since now it would be a bit hard to track these.

**Comment by mrshiljo** [comment]
Probably, im just new in this...;) Well...will fly further so ill see 👍

**Comment by crazytimtimtim** [comment]
somebody's working on the EEC so they should address the FADEC stuff too.

**Comment by mSparks43** [comment]
Yeah, there's a lot of detail here that mrshiljo can should refer back to in separate issues if needed (can mention this issue with a hash then 199 - i.e. #199 )

Most important is the backup documentation for any claims, so probably best to use the new CBT issues for anything remaining.
