### ISSUE TITLE
SPEEDBRAKE ARMED doesn't disappear when it should

### ISSUE THREAD

**Issue by MCCVeen** [mSparks43/747-400#203]
The speedbrake armed message should only be displayed when the speedbrake lever is in the arm detent. In the mod the only way to get rid of the message is if you retract the speedbrakes with the keyboard numbers, not if it automatically goes up on touchdown or if you move it with your mouse.

![image](https://user-images.githubusercontent.com/75425109/103049742-e685c400-4592-11eb-8f8b-2c577a45b2b7.png)

**Comment by mSparks43** [comment]
fixed by https://github.com/mSparks43/747-400/commit/495fc76049d249dfcf0dec26c0ce8a9f9efdd01c
