### ISSUE TITLE
ECS Duct Pressure and Cabin Altitude Indications

### ISSUE THREAD

**Issue by MCCVeen** [mSparks43/747-400#205]
The Duct pressure and Cab alt indications should only be displayed in certain situations. Look at the FCOM references below
![image](https://user-images.githubusercontent.com/75425109/103059928-cd870e00-45a6-11eb-80e1-2268648b0685.png)
![image](https://user-images.githubusercontent.com/75425109/103059109-754f0c80-45a4-11eb-929d-e875ae8adfe5.png)

**Comment by crazytimtimtim** [comment]
Sounds easy. I'll try to implement this.

**Comment by MCCVeen** [comment]
> Sounds easy. I'll try to implement this.
> Should Cabin Vertical Speed always be visible?

No, only the Total fuel and the Fuel Temp should be displayed there.

**Comment by crazytimtimtim** [comment]
Ok.

**Comment by crazytimtimtim** [comment]
You'd think it would show that data if pressurisation is set to manual...

**Comment by MCCVeen** [comment]
> You'd think it would show that data if pressurisation is set to manual, not landing alt manual...

You mean the Outflow Valves? I mean the outflow valves' postition is displayed on the overhead, and in case the cabin pressure drops and the cabin altitude reaches a certain height (I believe 9500 feet) and becomes amber (to alert the pilots that it's getting dangerously close to low oxygen levels at 10,000 feet) the data will appear on the Eicas. Same for the cabin differential pressure, once it gets too close to the limit the indications will appear on the screen :)

**Comment by crazytimtimtim** [comment]
Weird. The code is already here, but it doesn't work. I think the problem is with landing altitude manual, but I haven't done much testing yet. I will probably try to fix landing alt, or just bypass that requirement for now.

**Comment by crazytimtimtim** [comment]
This is like #587... The code is there, but I guess it doesn't work? I have an idea though, and I think it's related to the requirement of landing alt manual, but I haven't looked into it much yet. We'll need to fix all the landing alt stuff to get this to work, but might be able to do a simple workaround for now.

**Comment by crazytimtimtim** [comment]
Issue found and fixed. Will upload after some testing.
