### ISSUE TITLE
No FUEL PRESS CTR R/L caution

### ISSUE THREAD

**Issue by MCCVeen** [mSparks43/747-400#207]
![image](https://user-images.githubusercontent.com/75425109/103060582-e690be80-45a8-11eb-9605-fda19f222a90.png)
![image](https://user-images.githubusercontent.com/75425109/103060585-eee8f980-45a8-11eb-976d-b250106e3fb5.png)

**Comment by mSparks43** [comment]
this should now be fixed in https://github.com/mSparks43/747-400/commit/ff8a27e7a3c00ffca846fe53b6dce2dc089e7676
