### ISSUE TITLE
Outer main landing gear leave the ground too early

### ISSUE THREAD

**Issue by MCCVeen** [mSparks43/747-400#210]
Outer main gear always leave the ground way too early. This is also the reason why reverse thrust can't be enabled at touchdown in the mod, while it should be irl. Take a look here at 2:05 https://www.youtube.com/watch?v=6Du513WwUmg and then here https://www.youtube.com/watch?v=RjZa0-3nrOc

**Comment by mSparks43** [comment]
Fixed in e8fc32dae86a21dd45ebf3c6e8d956fbdc7a57b9

![image](https://user-images.githubusercontent.com/6773686/148684270-45cbdad5-e232-491e-8b79-f99467763a7d.png)
![image](https://user-images.githubusercontent.com/6773686/148684277-002fee1d-ec98-4f61-8edd-bc363c653f59.png)
