### ISSUE TITLE
VREF always selected to 30

### ISSUE THREAD

**Issue by MCCVeen** [mSparks43/747-400#213]
The VREF indication on the speed tape should be set to the speed that the pilot has selected in the FLAP/SPEED in the FMC on the approach page. This can manually be tweaked, say the pilot enters 25/190, the VREF will be set to 190 even tho it would be wrong.

![image](https://user-images.githubusercontent.com/75425109/103065280-8143ca00-45b6-11eb-9887-da8ad6cddb23.png)
![image](https://user-images.githubusercontent.com/75425109/103065304-9587c700-45b6-11eb-86da-206e0fc28620.png)

**Comment by mSparks43** [comment]
Fixed, select it on the approach page
R1 or R2
then
R4
![image](https://user-images.githubusercontent.com/6773686/148664599-66116bb2-a40b-4c5d-a943-d417b794fb06.png)
