### ISSUE TITLE
ACARS LSK works with no provider available

### ISSUE THREAD

**Issue by MCCVeen** [mSparks43/747-400#214]
ACARS should be displayed on the main menu of the CDU. While it isn't displayed in the mod, you are able to get into the ACARS menu when clicking LSK2.

![image](https://user-images.githubusercontent.com/75425109/103066353-fca67b00-45b8-11eb-95b4-4a7049e15099.png)
![image](https://user-images.githubusercontent.com/75425109/103066417-23fd4800-45b9-11eb-8493-e7e772e5a464.png)

**Comment by mSparks43** [comment]
ACARS is currently simulated in a failed state:
![image](https://user-images.githubusercontent.com/6773686/103182931-6d96ad00-48af-11eb-8f8f-56037c97babb.png)
when an acars provider is installed the center radio goes from inop to
![image](https://user-images.githubusercontent.com/6773686/103183051-720f9580-48b0-11eb-87c4-9633af9e3915.png)
public beta should start in January.

**Comment by MCCVeen** [comment]
> ACARS is currently simulated in a failed state:
> ![image](https://user-images.githubusercontent.com/6773686/103182931-6d96ad00-48af-11eb-8f8f-56037c97babb.png)
> when an acars provider is installed the center radio goes from inop to
> ![image](https://user-images.githubusercontent.com/6773686/103183051-720f9580-48b0-11eb-87c4-9633af9e3915.png)
> public beta should start in January.

I noticed that the mod uses a different model to the KLM and PMDG ones, sorry I got confused

**Comment by MCCVeen** [comment]
Was this supposed to be an answer to issue #215 ? If so, you're right. The KLM and PMDG communication panels are different models to the mod. Sorry for the confusion

**Comment by mSparks43** [comment]
Bit of both. its there when "not failed"
![image](https://user-images.githubusercontent.com/6773686/103416804-7ece0b00-4b88-11eb-87db-afa122044d30.png)
and the "ACARS NO COMM" EICAS message can be cleared by turning the center radio off when it is
![image](https://user-images.githubusercontent.com/6773686/103416869-bfc61f80-4b88-11eb-86c5-d5a9aee688f8.png)

**Comment by MCCVeen** [comment]
> Bit of both. its there when "not failed"
> 
> and the "ACARS NO COMM" EICAS message can be cleared by turning the center radio off when it is
> 
> EDIT:The actual "bug" here is the LSK working to take you to acars when the service isn't installed.

Ah yeah I see now, thanks!
