### ISSUE TITLE
Active and Requesting CDU Controller indications missing

### ISSUE THREAD

**Issue by MCCVeen** [mSparks43/747-400#215]
![image](https://user-images.githubusercontent.com/75425109/103066767-d208f200-45b9-11eb-805c-f87c6db54a86.png)
![image](https://user-images.githubusercontent.com/75425109/103066787-dfbe7780-45b9-11eb-9374-4441f2e37bc1.png)
![image](https://user-images.githubusercontent.com/75425109/103066856-febd0980-45b9-11eb-89ce-de4db7b74773.png)

**Comment by mSparks43** [comment]
![image](https://user-images.githubusercontent.com/6773686/148685013-ba8f13a1-622d-4e3a-b6f9-6e1247c975b3.png)
