### ISSUE TITLE
Long haul management - auto adjustment for TANK/ENG CAS on request.

### ISSUE THREAD

**Issue by almarine91** [mSparks43/747-400#220]
Just as pause at TOD, auto management of fuel tanks and pumps is essential to long hauls.
Currently, it is not possible to do long hauls staying AFK, since arrangements are required for fuel setup.
Last night did AMS PEK, went to bed, when awake i found engines 2&3 off due to empty tanks.
Ideal would be an option (off by default) thru FMC, auto cruise fuel management or something

**Comment by mSparks43** [comment]
There is now a FWL script for this linked in the discord
https://discord.com/channels/713625220568842260/713625220568842263/844535310745731112
