### ISSUE TITLE
localizer and glideslope indicators don’t disappear when ILS is not tuned

### ISSUE THREAD

**Issue by MisterFahrenhiet** [mSparks43/747-400#225]
the localizer and glideslope indicators don’t go away, even when the frequency isn’t tuned to an ILS. the orange bar under the localizer indicator should also disappear after frequency is changed into not an ILS frequency, so that there is more room at the bottom of the PFD
![608FCA2C-6038-4C2D-9BBF-677C025F53A9](https://user-images.githubusercontent.com/62818033/103370805-c165e980-4a9b-11eb-820a-fc339ab8a7e2.jpeg)

**Comment by mSparks43** [comment]
dupe of #143
