### ISSUE TITLE
ACT RTE LEGS page - progressive numbers missing

### ISSUE THREAD

**Issue by almarine91** [mSparks43/747-400#226]
![image](https://user-images.githubusercontent.com/76728534/103384983-c5742480-4af8-11eb-8f79-2a986464d96c.png)

no progressive page number for legs in fmc top right corner ( 2/6)

**Comment by mSparks43** [comment]
do you mean the 2/6 ?

**Comment by almarine91** [comment]
Correct. In flight the number is shown(even if legs becomes direct to), but on ground nothing.

Scarica Outlook per iOS<https://aka.ms/o0ukef>
________________________________
