### ISSUE TITLE
STEP scrolling in LEGS

### ISSUE THREAD

**Issue by almarine91** [mSparks43/747-400#232]
When scrolling between WP in LEGS PAGE, 
fmc doesnt automatically switch to the page containing the displayed wp centered.

Example: centered in last wp of page 1/2
press step; next wp is centered but fmc LEGS PAGE remains in page 1 (need to click NEXT PAGE)

**Comment by crazytimtimtim** [comment]
I'll look into this.

**Comment by mSparks43** [comment]
More detail in #724
