### ISSUE TITLE
FLAPS/SPEED on PFD during approach

### ISSUE THREAD

**Issue by almarine91** [mSparks43/747-400#235]
The real thing shall show flaps/speed on approach on PFD, as below
![image](https://user-images.githubusercontent.com/76728534/103431593-d1ccb000-4bd2-11eb-97a2-eff8442d8d74.png)

![image](https://user-images.githubusercontent.com/76728534/103431596-dabd8180-4bd2-11eb-9d54-3e413656b922.png)

**Comment by mSparks43** [comment]
This is an unimplemented option that depends on the avionics installed.
Also, select approach ref/speed from the FMC
![image](https://user-images.githubusercontent.com/6773686/148685383-ad0ab287-0eb9-43e0-92fd-f68a6a5a403b.png)
