### ISSUE TITLE
ND - Course white line

### ISSUE THREAD

**Issue by almarine91** [mSparks43/747-400#236]
in ND, course white line shall be present according to APP ILS CRS.
![image](https://user-images.githubusercontent.com/76728534/103431658-fbd2a200-4bd3-11eb-9b12-d2860e514a8f.png)

Instead the line is present but costantly pointing head up.

**Comment by Stratocruizer** [comment]
it can be both, if the ND and the small compass rose is programmed for HDG up or TRK up. Thats up to the airline to configure.

**Comment by mSparks43** [comment]
please reopen with fcom references.

**Comment by almarine91** [comment]
done, see new one
