### ISSUE TITLE
APU Eicas caution shown when it shouldn't be

### ISSUE THREAD

**Issue by MCCVeen** [mSparks43/747-400#240]
The APU Eicas message should only be shown in case the APU has automatically been shutdown or N1 is above 95% with the selector in OFF and the apu is not in cooldown phase.
![image](https://user-images.githubusercontent.com/75425109/103471235-16487f00-4d7e-11eb-99c5-da506ed1aee1.png)
![image](https://user-images.githubusercontent.com/75425109/103471239-1c3e6000-4d7e-11eb-87f4-f3c92b084643.png)

**Comment by mSparks43** [comment]
Is the APU selector off? because APU N1 is 100% in that SS, in which case "APU N1 RPM >95% and APU selector off" is true.

**Comment by MCCVeen** [comment]
yes

**Comment by Matt726-S** [comment]
i remember that when you turn the apu selector to off, the n1 stays at 100, and then it shutdowns a minute or two later. is that supposed to happen?

**Comment by MCCVeen** [comment]
> i remember that when you turn the apu selector to off, the n1 stays at 100, and then it shutdowns a minute or two later. is that supposed to happen?

![image](https://user-images.githubusercontent.com/75425109/105188951-bb13dc00-5b34-11eb-9176-6a18d86d0bd5.png)

**Comment by MCCVeen** [comment]
> > i remember that when you turn the apu selector to off, the n1 stays at 100, and then it shutdowns a minute or two later. is that supposed to happen?
> 
> ![image](https://user-images.githubusercontent.com/75425109/105188951-bb13dc00-5b34-11eb-9176-6a18d86d0bd5.png)

Hi! First of all, I haven't checked out the 747 or the hub in a long long time and the progress you and the others are making is incredible!!

The VALVE fault light will only show up when the apu is running and the valve is not in the desired position. When the APU is off this gets disregarded. You can see it here on the photos of actual 747 overheads

![image](https://user-images.githubusercontent.com/75425109/148665486-263adc98-bce1-4c6c-af81-6e6daba3d0c1.png)
![image](https://user-images.githubusercontent.com/75425109/148665493-9abf2cfc-e4cd-452b-ad27-9cf373a8fec6.png)
![image](https://user-images.githubusercontent.com/75425109/148665529-2ee51837-9a14-478d-8a37-a75848c04b3e.png)
