### ISSUE TITLE
ILS autotuning

### ISSUE THREAD

**Issue by MCCVeen** [mSparks43/747-400#246]
not clear which ils indicator is being referred to here, assuming this means the gs and loc pointers on the pfd closing as fixed in https://github.com/mSparks43/747-400/commit/e5ccd4a9aeb5d9ea3ae0b0ed0a7811963c77494c

plse reopen if it referred to something else.

_Originally posted by @mSparks43 in https://github.com/mSparks43/747-400/issues/180#issuecomment-753770160_

What I meant, was that an ILS frequency is picked up (as you can see on the DME indicator on the PFD) while the FMC says PARK

**Comment by mSparks43** [comment]
confirming white text on PFD

**Comment by MCCVeen** [comment]
Exactly, it's tuned to IWUE while the fmc says nothing's been tuned.
