### ISSUE TITLE
FMC RTE page - no RWY entry

### ISSUE THREAD

**Issue by almarine91** [mSparks43/747-400#247]
![image](https://user-images.githubusercontent.com/76728534/103549279-64a56d00-4ea7-11eb-9102-35e55827e9ea.png)

![image](https://user-images.githubusercontent.com/76728534/103549309-6e2ed500-4ea7-11eb-923d-65f18633fad0.png)

**Comment by rKsanu2MMYvypWePtQWM** [comment]
the whole thing is just recolored default FMC
