### ISSUE TITLE
HDG TRK display PFD - CRS white line

### ISSUE THREAD

**Issue by almarine91** [mSparks43/747-400#249]
in ND, course white line shall be present according to APP ILS CRS.
image

Instead the line is present but costantly pointing head up.

![image](https://user-images.githubusercontent.com/76728534/103715251-6c0c6980-4fc0-11eb-8cbc-d36d4b4bdce0.png)

**Comment by mSparks43** [comment]
can't recreate this, the track line seems to be correctly pointing to ground track at all times and always has, with the track indicator bound to
DATAREF sim/cockpit2/gauges/indicators/ground_track_mag_pilot
and
DATAREF sim/cockpit2/gauges/indicators/ground_track_mag_copilot
