### ISSUE TITLE
V1 VR speed bugs show up on touchdown

### ISSUE THREAD

**Issue by almarine91** [mSparks43/747-400#250]
![image](https://user-images.githubusercontent.com/76728534/103715348-aece4180-4fc0-11eb-8b1d-81a9c56a3861.png)

**Comment by mSparks43** [comment]
what makes you think they shouldnt be? what should show in their place?

**Comment by almarine91** [comment]
Vref should just remain there after shutdown

[Image.jpeg]

https://www.youtube.com/watch?v=5JbD_Y8VSJs&app=desktop&persist_app=1


I
Scarica Outlook per iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mSparks43** [comment]
what would happen on a go around?

**Comment by almarine91** [comment]
Nice question.
Gotta check fcom, I can guess on toga press the v1 ve will populate again

Scarica Outlook per iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Stratocruizer** [comment]
https://www.youtube.com/watch?v=deNfd0_b4ec might help too from 5:45 on

**Comment by Matt726-S** [comment]
it looks like the NO V SPD appears at 50 knots

**Comment by Matt726-S** [comment]
just watched some videos, and it always shows up at 50. pmdg actually didnt simulate this property lol
