### ISSUE TITLE
not working FMC cold and dark

### ISSUE THREAD

**Issue by Krasnyy222** [mSparks43/747-400#251]
![image](https://user-images.githubusercontent.com/65772598/103877329-f5698c00-50e5-11eb-86f4-733d38dfc5dd.png)
![image](https://user-images.githubusercontent.com/65772598/103877379-087c5c00-50e6-11eb-856f-94dd54c80554.png)
When I launch the plane cold and dark, FMC does not turn on. When I start the airplane on, the FMC works. 
latest version master

**Comment by almarine91** [comment]
From cold & dark you need battery on and standby power on auto.
Then from Fmc connect ground power.

**Comment by Krasnyy222** [comment]
I do this, look to screenshot

**Comment by Zodroid** [comment]
Bind a key to Avionics on

**Comment by Krasnyy222** [comment]
Thank you so much!
