### ISSUE TITLE
FMC - LEGS PAGE - page numbering.

### ISSUE THREAD

**Issue by almarine91** [mSparks43/747-400#252]
Page 10/10 is displayed as 0/10
page 11 is displayed as 1.
Page n. needs to be 2 digits

this is shown as page 9/20 but it is actually page 19/20
![image](https://user-images.githubusercontent.com/76728534/103907273-5ce10500-5101-11eb-8b0e-5c6c79df4dc3.png)

**Comment by crazytimtimtim** [comment]
Will look into this.

**Comment by mSparks43** [comment]
More detail in #724
