### ISSUE TITLE
Both Minimums displayed

### ISSUE THREAD

**Issue by Stratocruizer** [mSparks43/747-400#253]
![1](https://user-images.githubusercontent.com/75931171/103914241-6d917b00-5101-11eb-8ad6-b72481ff5486.PNG)

![2](https://user-images.githubusercontent.com/75931171/103914450-c3662300-5101-11eb-853e-e2471ead80cf.PNG)

Radio minima OR Baro minima can be displayed, not both on the same time.
[](url)

**Comment by MCCVeen** [comment]
They can both be activated on the PFD actually. I don't know what the logic is in terms of when the alert would sound in that case

**Comment by Stratocruizer** [comment]
About the alert what sounds see the Fcom manual i posted, about the rest, that seems strange and a bit confusing.

**Comment by MCCVeen** [comment]
![image](https://user-images.githubusercontent.com/75425109/104047138-72c5f700-51e1-11eb-8562-8315a4c8cfc5.png)

**Comment by mSparks43** [comment]
So. currently, the MDA is hidden if it is set to less than -100. and DH if hides set to less than 0.
It looks to me to just be an initialisation bug, where these should all be set to hidden when the aircraft first fires up until set.
