### ISSUE TITLE
Still no FUEL PRESS CTR R/L caution

### ISSUE THREAD

**Issue by MCCVeen** [mSparks43/747-400#257]
this should now be fixed in https://github.com/mSparks43/747-400/commit/ff8a27e7a3c00ffca846fe53b6dce2dc089e7676

_Originally posted by @mSparks43 in https://github.com/mSparks43/747-400/issues/207#issuecomment-755873363_

latest commit 643, waited 60 seconds
![image](https://user-images.githubusercontent.com/75425109/103975536-aa4a8a00-5174-11eb-810b-6433b08a2c35.png)

**Comment by mSparks43** [comment]
these messages need defining and logic adding for them
![image](https://user-images.githubusercontent.com/6773686/146660408-9b44ebfe-72f9-4e0a-a0f5-c6aded3c353f.png)
