### ISSUE TITLE
Autobrakes switch should go to disarm when set to 1-MAX on ground

### ISSUE THREAD

**Issue by MCCVeen** [mSparks43/747-400#258]
When the Autobrakes switch is set to 1, 2, 3, 4 or MAX on the ground the switch should automatically go to disarm. There is about a 1 second delay between selecting it to 1-MAX to Disarm as the system needs a second to recognize that the switch wants to arm one of the modes. I couldn't find this in the FCOM but this is how the system works

**Comment by crazytimtimtim** [comment]
If you're _sure_ that's how it works, I'll implement it.
