### ISSUE TITLE
>X FEED CONFIG displayed?

### ISSUE THREAD

**Issue by MCCVeen** [mSparks43/747-400#260]
My fuel panel is set up correctly, so why is x feed config displayed? Does it want the inner tanks to get to the exact same level as the outer tanks since the inner tanks have 100 kgs more fuel in them? 
![image](https://user-images.githubusercontent.com/75425109/103981405-07007180-5182-11eb-9dee-01ea2c13ddc9.png)

**Comment by jayhawk81** [comment]
See below, this is modeled correctly. You need to turn on xfeeds 1 and 4 as well as AFT AND FWD overrides 

![image](https://user-images.githubusercontent.com/76977928/104103438-1eb62380-5270-11eb-9821-137bf1962b11.jpeg)

**Comment by MCCVeen** [comment]
> See below, this is modeled correctly. You need to turn on xfeeds 1 and 4 as well as AFT AND FWD overrides
> 
> ![image](https://user-images.githubusercontent.com/76977928/104103438-1eb62380-5270-11eb-9821-137bf1962b11.jpeg)

I know how the fuel system works it's just that I didn't get a XFEED CONFIG untill a few minutes later so something's going wrong there

**Comment by MCCVeen** [comment]
nvm I already see what's wrong here
