### ISSUE TITLE
Main gear bouncing upon touchdown

### ISSUE THREAD

**Issue by MCCVeen** [mSparks43/747-400#263]
This "should" be fixed with the removal of the metal skids that ship with default.

_Originally posted by @mSparks43 in https://github.com/mSparks43/747-400/issues/117#issuecomment-755738659_

Still present in commit 645, caused the autobrake to disarm

https://user-images.githubusercontent.com/75425109/103982342-9d816280-5183-11eb-9a0c-f5b80a6c17e1.mp4

**Comment by mSparks43** [comment]
https://forums.x-plane.org/index.php?/forums/topic/61282-landing-gear-dynamics/

**Comment by MCCVeen** [comment]
You can see here that it rarely happens irl https://www.youtube.com/watch?v=9fGQL7rBH8Q

**Comment by mSparks43** [comment]
would you be able to try these constants in plane maker
![image](https://user-images.githubusercontent.com/6773686/104047778-7e65ed80-51e2-11eb-86e2-52fa6874433e.png)

Plane maker->open the 747-400.acf->standard->Landing gear->Gear Cons
Then file->save as->give it a new name

**Comment by MCCVeen** [comment]
A lot less with these settings! But I noticed the suspension is way too stiff. I can't really explain it exactly so I made a video so you can see it for yourself

https://www.youtube.com/watch?v=Hl4AuBFHokQ

**Comment by mSparks43** [comment]
How it should be
https://www.youtube.com/watch?v=zXpGVTxZSx4

Now I'm fairly confident we're thinking the same thing, I'll try a few more, my thought for making it stiffer is to increase 2,3,4 deflection at empty weight and reduce the damping constant, but I'll try a few more and compare them to this video

**Comment by MCCVeen** [comment]
That is a 747-200. The landing gear on the 747-400 was modified I believe. In these videos I don't see the same bouncing effect happening either so I'm guessing Boeing adjusted the suspension to make the plane bounce less on landings https://www.youtube.com/watch?v=o0ArwP3m47A

**Comment by mSparks43** [comment]
apologies I posted that video before clicking on yours thinking yours was an XP recording.
Agreed, we're seeing the same thing, looks like its achievable with the right balance of absorption and extension, Ill try some more soon.

**Comment by mSparks43** [comment]
How about these
![image](https://user-images.githubusercontent.com/6773686/104103054-65bc0d00-52a0-11eb-9aaa-bf801c42b655.png)

**Comment by MCCVeen** [comment]
Way better! In real life the shock absorber is even longer from what I've seen. It's a shame no one can remodel the exterior to the 744, that would be amazing

**Comment by MCCVeen** [comment]
Maybe pull back slightly, it's now impossible to bounce the aircraft. I came down with around -1400 fpm and the real aircraft with most likely around -800 fpm https://www.youtube.com/watch?v=CjuiB8JPFC4 https://www.youtube.com/watch?v=BMsJt3nV6fs
