### ISSUE TITLE
stab trim inaccurate

### ISSUE THREAD

**Issue by Matt726-S** [mSparks43/747-400#273]
there are two issues with the stab trim currently (i think, correct me if i’m wrong)

1: the master warning alarm plays even when i’m on the green band. the warning plays until i move the trim to around 3 units

2: the green band position on the texture is wrong. in the real aircraft the band is marked from 1.5 to 6 units. however on this sim model the green band is marked from 3.5 to 8 units. this is probably a texture thing i can fix tho. please refer to the photos below 

![2AA4476C-EB91-49B4-84A9-5F52A956E737](https://user-images.githubusercontent.com/62818033/104272174-9485df00-546a-11eb-80a0-48abd48823b8.jpeg)

![B8378597-D452-444A-9CA9-396D5B0E7975](https://user-images.githubusercontent.com/62818033/104272261-c008c980-546a-11eb-918a-10e20aec17c0.jpeg)

**Comment by rKsanu2MMYvypWePtQWM** [comment]
I've seen the green bar move in this mod actually. No clue how or why though.

**Comment by mSparks43** [comment]
it moves based on takeoff cg entered in the fmc. alarm is probably sounding because the max trim is actually lower than the stops.

**Comment by crazytimtimtim** [comment]
> it moves based on takeoff cg entered in the fmc. alarm is probably sounding because the max trim is actually lower than the stops.

I don't think the green bar is supposed to move...

**Comment by rKsanu2MMYvypWePtQWM** [comment]
@Matt726-S Could you explain why was it closed? Is it supposed to move like that? The part photo clearly shows it as a static part though...
