### ISSUE TITLE
Screens Blank and Can't Push anything

### ISSUE THREAD

**Issue by andrew8042** [mSparks43/747-400#274]
Hi,

Total newbie here to X Plane on the Mac. I followed the instructions to install, but when the plane loads, the engines are running but all the screens are blank, and I cant press any switches, they make a noise as if they've been switched or pushed but nothing happens. I get a strange popup message each time saying a minor problem parsing the VRCONFIG, no idea what that means or if its related.
Xplane 11.5
iMac OS Catalina 10.15.7

Thanks !

**Comment by mSparks43** [comment]
this will probably be the xtlua xpl files getting quarantined.

you need to use the xattr command when a folder is quarantined, privacy and security to unlock the xpl files
you can run xattr for everything in the xplane folder with

find . -name "mac.xpl" -exec xattr {} \;
find . -name "mac.xpl" -exec xattr -d com.apple.quarantine {} \;

**Comment by andrew8042** [comment]
Thank you! I had no idea what i was doing but somehow its worked. Much appreciated.
