### ISSUE TITLE
fmc issue

### ISSUE THREAD

**Issue by cgw44** [mSparks43/747-400#276]
Noticed that on the legs page the altitudes did not match my cruising alt of FL 360 during mid flight.

![747-400 - 2021-01-15 13 42 46](https://user-images.githubusercontent.com/77507898/104766038-e4e59100-5737-11eb-9ee3-e2338153f347.png)

**Comment by jryden2** [comment]
There seem to be several issues with VNAV in the current code.  For now, I manage cruise altitude manually.

**Comment by crazytimtimtim** [comment]
There was a bug with the legs page. Can you see if the problem is still there?

**Comment by mSparks43** [comment]
More detail in #724
