### ISSUE TITLE
exterior light switches inverted

### ISSUE THREAD

**Issue by Matt726-S** [mSparks43/747-400#278]
the exterior lights on the overhead seem inverted, you’re supposed to push the switches forward to turn on the lights, not backwards, like the current situation

**Comment by mSparks43** [comment]
![image](https://user-images.githubusercontent.com/6773686/105127348-03a1aa00-5ae1-11eb-8992-74832b018031.png)
which?

**Comment by Matt726-S** [comment]
i believe a few 747s have lig
