### ISSUE TITLE
SPEED window should not disappear when autothrottle

### ISSUE THREAD

**Issue by Matt726-S** [mSparks43/747-400#284]
when the autothrottle is off, the digits are blank and i’m unable to adjust the MCP speed window, making it impossible to set my v-speeds during preflight. when i turn on the autothrottle, the speed window opens and then i can set speeds.

**Comment by mSparks43** [comment]
I'm reasonably sure the current setting is correct. speed window only opens when A/T is armed (on or off) and not on in VNAV without intervention.

**Comment by MCCVeen** [comment]
> I'm reasonably sure the current setting is correct. speed window only opens when A/T is armed (on or off) and not on in VNAV without intervention.

no, the speed window should be available with autothrottle disarmed

**Comment by rKsanu2MMYvypWePtQWM** [comment]
I also believe the window should be blank. Do you have any proof that they shouldn't?

**Comment by Matt726-S** [comment]
sorry, i think i’m still too used to the 737, since you leave the autothrottle to off in that plane during startup

**Comment by MCCVeen** [comment]
Once again, the speed window should be available with autothrottle disarmed
![image](https://user-images.githubusercontent.com/75425109/105258954-225c7b00-5b8b-11eb-8487-16699380f1aa.png)

**Comment by rKsanu2MMYvypWePtQWM** [comment]
I've looked into the various 747 manuals and noticed that basically the auto-throttle switch never leaves ARM position. Even pressing the auto-throttle disconnect switch on the throttles, the automatic functions get cancelled, but the "autothrottle remains armed" (from the FCOM).

**Comment by MCCVeen** [comment]
> I've looked into the various 747 manuals and videos and noticed that basically the auto-throttle switch never leaves ARM position. Even pressing the auto-throttle disconnect switch on the throttles, the automatic functions get cancelled, but the "autothrottle remains armed" (from the FCOM). So the window should be blank when it's OFF, but it basically is never switched to OFF.

No, the window should not be blank when it's off. The autothrottle arm switch is never disengaged because in situation where the aircraft gets close to stall speed the autothrottle will kick in. It's unnecessary to turn it off on the ground. The speed window only goes blank when FMC controls the commanded speed as is described clearly in the FCOM. If it would blank with the autothrottle arm switch turned off then the FCOM requires to mention that, which it doesn't.

**Comment by rKsanu2MMYvypWePtQWM** [comment]
> > I've looked into the various 747 manuals and videos and noticed that basically the auto-throttle switch never leaves ARM position. Even pressing the auto-throttle disconnect switch on the throttles, the automatic functions get cancelled, but the "autothrottle remains armed" (from the FCOM). So the window should be blank when it's OFF, but it basically is never switched to OFF.
> 
> No, the window should not be blank when it's off. The autothrottle arm switch is never disengaged because in situation where the aircraft gets close to stall speed the autothrottle will kick in. It's unnecessary to turn it off on the ground. The speed window only goes blank when FMC controls the commanded speed as is described clearly in the FCOM. If it would blank with the autothrottle arm switch turned off then the FCOM requires to mention that, which it doesn't.

Well then find a photo or video where the switch can be seen in OFF and the speed window is open (preferably analog speed window, not an LCD)

**Comment by MCCVeen** [comment]
> Actually I found some images myself:
> https://www.team-bhp.com/forum/attachments/commercial-vehicles/119600d1238758107-airplane-review-boeing-747-400-pilot-first-team-bhp-b747400-cockpit.jpg
> It seems the window does not blank. There was one guy who has a relative in KLM, maybe he would tell us the whole truth about it.

that's me lol

**Comment by rKsanu2MMYvypWePtQWM** [comment]
Oh rip lol

**Comment by mSparks43** [comment]
There is two parts to it, the window should be open when A/T is disarmed, and
![image](https://user-images.githubusercontent.com/6773686/105366980-3abaad00-5c00-11eb-9038-f8d99a032a6f.png)
AUTOTHROT DISC should display on the EICAS

**Comment by MCCVeen** [comment]
> There is two parts to it, the window should be open when A/T is disarmed, and
> AUTOTHROT DISC should display on the EICAS

AUTOTHROT DISC should be displayed on the EICAS yes, but if you press the autothrottle disconnect button again on the thrust levers the eicas message will disappear

![image](https://user-images.githubusercontent.com/75425109/105371368-d9490d00-5c04-11eb-95a7-a2d93a10175c.png)
![image](https://user-images.githubusercontent.com/75425109/105371395-e0701b00-5c04-11eb-991f-e533d5cd4328.png)
