### ISSUE TITLE
Fuel and Balance not working

### ISSUE THREAD

**Issue by qAdxm** [mSparks43/747-400#286]
Hi! When I want to do a 10+ hour long haul flight on the 747, I put the fuel amount to last 11-13 hours but when I close fuel and balance after applying changes, the fuel only goes 10 hours 17 minutes flight time. I tried reloading XP11 and restarting my PC but it kept doing it.

**Comment by mSparks43** [comment]
Are you on the ground? the 747 does not have aerial refuelling capablities.

**Comment by qAdxm** [comment]
Yes, I am on the ground. At the gate specificly.

**Comment by jryden2** [comment]
The tanks hold 173K KG of fuel.  You should get about 15+ hours of flight time out of that as the plane burns an average of 10K KG of fuel per hour.   (More at departure, less at arrival).  Ignore the time estimates given by X-Plane.  They are just guesses.
