### ISSUE TITLE
Certain textures for flood lights still don't have the correct color

### ISSUE THREAD

**Issue by MCCVeen** [mSparks43/747-400#287]
You can see the upper part still has the old color on both the captain and f/o side
![image](https://user-images.githubusercontent.com/75425109/105158149-f3ec8a80-5b0d-11eb-9e0c-70e15670f9e3.png)
![image](https://user-images.githubusercontent.com/75425109/105158166-fb139880-5b0d-11eb-96cf-3917410611fc.png)

**Comment by crazytimtimtim** [comment]
What color should it be?

**Comment by mSparks43** [comment]
wont fix now, this will probably be revisited when we have
https://developer.x-plane.com/article/the-x-plane-12-material-model/
and
https://developer.x-plane.com/2021/11/photometric-lighting-what-is-it-and-why-do-we-need-it/
