### ISSUE TITLE
Overhead Panel Lights

### ISSUE THREAD

**Issue by MCCVeen** [mSparks43/747-400#288]
The entire cockpit panel lights should not be dimmed without electrical power. Also on the overhead when you turn on the battery, only the electrical panel lights should come to live. When standby power is turned on the hydraulic demand sys 4 "SYS FAULT" light, the IRS panel lights, the ignition panel lights, the anti ice panel lights and the outflow valves panel lights will be powered. The rest will be powered when electrical power is turned on

![image](https://user-images.githubusercontent.com/75425109/105185751-370c2500-5b31-11eb-80bf-3ff80e1626a0.png)
![image](https://user-images.githubusercontent.com/75425109/105185768-3bd0d900-5b31-11eb-8884-7114a93a4f9c.png)
![image](https://user-images.githubusercontent.com/75425109/105185779-40958d00-5b31-11eb-8d18-d70711497683.png)

**Comment by mSparks43** [comment]
see #287
