### ISSUE TITLE
Easier way to open doors

### ISSUE THREAD

**Issue by jmsantafe** [mSparks43/747-400#29]
You can open the doors, but if is very hard to do. You need to bind a key to open a door, and another to close it. To add to that, the doors are randomly numbered. An easier way to open and close doors would be very nice.

**Comment by crazytimtimtim** [comment]
@mSparks43 I'll see if I can make a page on the FMS to control doors. Probably won't be functional, but the entries will be there.

**Comment by crazytimtimtim** [comment]
FMC page is in progress.

**Comment by crazytimtimtim** [comment]
Finished, @mSparks43 you can close the issue.
