### ISSUE TITLE
MCDU error on STAR SERFR4 for KSFO

### ISSUE THREAD

**Issue by Callero** [mSparks43/747-400#290]
SERFR4 is a valid STAR for ILS 28R on KSFO, but the MCDU throws an error selecting it:
![image](https://user-images.githubusercontent.com/10278391/105483021-807f8000-5ca9-11eb-832d-30c93fee04bf.png)

![2021 01 22-12 01](https://user-images.githubusercontent.com/10278391/105483139-ad339780-5ca9-11eb-87b1-5946a7eb2ed2.png)

**Comment by airfightergr** [comment]
Since it is based on the default FMC operation, you should try to select first the STAR and then the APP.

**Comment by Callero** [comment]
Got it, thanks!
Huge thanks for your work and generosity as well!
