### ISSUE TITLE
tips on fmod

### ISSUE THREAD

**Issue by WolfAir737** [mSparks43/747-400#298]
It looks like my old FMOD copy is still around. If you ask me, I think the FTSim one is better in every way, but there's one important thing. There are two engine sound sets overlapping inside, it's making it all weird.
So there are two options here: keep my engine sound entries, and remove entries from FTSim in .snd file or vice versa. I would go with just deleting my stuff entirely, since they are old, and nowhere near to the standards.

**Comment by Matt726-S** [comment]
i don’t think there are any sounds overlapping in-sim since msparks has changed the file name for your old fmod so the sounds shouldn’t play. also, i’m working on a new fmod, engines are still quite WIP but other features are cool

**Comment by WolfAir737** [comment]
I checked the .snd file in this pack. my entries are still written at the bottom of the file, hence why I posted this. If one of you can delete that it would be cool,

**Comment by mSparks43** [comment]
Sounds here were FTSim, where you got them from, FTSim actually gave us permission to use them,
->my entries are still written at the bottom of the file
Sorry, but if you mean
https://github.com/mSparks43/747-400/blob/0858434b625b0ccffb117a2b38439f11c733be5d/fmod/747-400.snd
You will note they were already commented out when you posted this.
