### ISSUE TITLE
Autothrottle Disconnect

### ISSUE THREAD

**Issue by MCCVeen** [mSparks43/747-400#299]
I was watching Matts stream back and I noticed that the Autothrottle disconnect function is still not correct. First off when you disconnect the autopilot, it will not disengage the autothrottle. The autothrottle can be disconnected by pushing the autothrottle disconnect buttons on the thrust levers or by switching the Autothrottle Arm switch to off. Second of all, the >AUTOTHROT DISC message only displays when the autothrottle is disconnected. So that were to be the second picture where the autopilot kicks off the autothrottle (which again is incorrect behavior but if it was then that would be where the message is displayed), and not when the Autothrottle ARM switch is turned off. The >AUTOTHROT DISC message is displayed for when the actual autothrottle mode was in control of the thrust levers and is now disconnected. Third one is that the >AUTOTHROT DISC message will stay untill the autothrottle disconnect switch on the thrust lever is pressed.

![image](https://user-images.githubusercontent.com/75425109/105846337-53e6a380-5fdc-11eb-886a-e29a59ae3989.png)
![image](https://user-images.githubusercontent.com/75425109/105846359-5ba64800-5fdc-11eb-9da0-379a6af2baf0.png)
![image](https://user-images.githubusercontent.com/75425109/105846389-67920a00-5fdc-11eb-8be0-a22e45be89e0.png)
![image](https://user-images.githubusercontent.com/75425109/105847150-8218b300-5fdd-11eb-84f1-b39728d20dfb.png)
![image](https://user-images.githubusercontent.com/75425109/105847168-893fc100-5fdd-11eb-8d42-62139ae9c1da.png)
![image](https://user-images.githubusercontent.com/75425109/105847480-f2273900-5fdd-11eb-83a1-7a162cd7351e.png)
![image](https://user-images.githubusercontent.com/75425109/105847540-023f1880-5fde-11eb-9c84-848d967490e1.png)

**Comment by crazytimtimtim** [comment]
Can you check again? I think some autothrottle stuff has changed recently iirc.

**Comment by MCCVeen** [comment]
> Can you check again? I think some autothrottle stuff has changed recently iirc.

still there

**Comment by mSparks43** [comment]
fixed in ad79a9f56ca0cc97328d68d24c07252f452f03e8
