### ISSUE TITLE
VNAV does not climb aircraft to cruise altitude

### ISSUE THREAD

**Issue by gHashFlyer** [mSparks43/747-400#318]
I set FL410 as CRZ ALT on PERF INIT page, and set 41000 on MCP, but aircraft leveled off at FL350. Oddly, on the LEGS page (ACT DIRECT-TO) I see ALT SEL of 35000.
![2021-01-26_100337](https://user-images.githubusercontent.com/77414195/105864348-d4e37200-5fbf-11eb-9d78-094cf41f25aa.jpg)

**Comment by crazytimtimtim** [comment]
Can you check again? There was a problem with the LEGS page.

**Comment by gHashFlyer** [comment]
Appears to **not** be resolved.  Currently enroute KLAX-KAFW with crz alt FL410 set on PERF INIT page, and on MCP.  Airplane leveld off and is cruising at FL390.

![2021-03-16_100929](https://user-images.githubusercontent.com/77414195/111323007-e2bc8780-863f-11eb-85e7-4694d626f36b.jpg)

**Comment by gHashFlyer** [comment]
nb., I rarely climb to FL410.  Almost all other flights I've done there has been no issue.  Also, in this most recent case, I had originally planned FL390, but changed it to FL410 on the ground as I was taxiing out.

**Comment by mSparks43** [comment]
Please retest, is this an issue climbing to FL410 or an issue climbing to cruise alt?
![image](https://user-images.githubusercontent.com/6773686/113989431-b9fb6c80-9850-11eb-90ce-80bbd6d03cc4.png)

**Comment by gHashFlyer** [comment]
I believe this issue is resolved.  However I had an issue this morning with the April 8 release.  I was unable to arm VNAV on the ground, or engage VNAV in the air.  I had entered FL420 as the cruise altitude. It simply would not engage, and the FMC message was, "VNAV/PERF UNAVAILABLE".   Time for test piloting....climbing through FL270 or so, I changed CRZ ALT on the PERF page to F320, and was then able to engage VNAV.  I then reset it again, this time to FL430, toggled FLCH/VNAV without an issue.  Takeoff weight was 258.6 tons.

**Comment by mSparks43** [comment]
My guess would be you entered a 420 feet cruise alt rather than a FL420 one? (XP FMC may interpret it differently than the custom  one)
"PERF/VNAV UNAVAILABLE" message is triggered when the is no flight plan or cruise alt is set to less than 10,000 feet

I don't think XXX or XXXX entry is supported (but that's a different issue)
![image](https://user-images.githubusercontent.com/6773686/114057734-1e3f2000-9893-11eb-8e82-5c55c09fb6ce.png)

**Comment by gHashFlyer** [comment]
I entered 420, not FL420.  But if that was the issue, then it would also have been an issue when I later entered 320, not FL320.  After entering 420, it displayed "FL420", and after entering 320 it displayed "FL320".
