### ISSUE TITLE
wrong fuel configuration

### ISSUE THREAD

**Issue by Matt726-S** [mSparks43/747-400#320]
stab fuel tank and switches do not exit for the normal -400. according to fcom it only exists for the combi
![15A7BB4F-C57D-4F07-8574-3C49BFE6D562](https://user-images.githubusercontent.com/62818033/105867529-33f6b600-5fc3-11eb-8c89-3fa12cc6eec8.jpeg)

**Comment by MCCVeen** [comment]
Second this, only the Combis had a stabilizer tank
