### ISSUE TITLE
Stabilizer trim stuck in full aft in latest version

### ISSUE THREAD

**Issue by MCCVeen** [mSparks43/747-400#321]
https://www.youtube.com/watch?v=Dx_uGxUALiw
![image](https://user-images.githubusercontent.com/75425109/105867601-9072c900-5ff5-11eb-8bdb-4856b960b8ab.png)

**Comment by gHashFlyer** [comment]
When did this happen?  Really need to be more descriptive.

**Comment by MCCVeen** [comment]
> When did this happen? Really need to be more descriptive.

see the video

**Comment by MrB0ssMan** [comment]
I am having the exact same issue with this plane it also seems to effect other planes if you load them.in after the sparks 747 aswell.

**Comment by gHashFlyer** [comment]
Just an update, because I did report this on Discord a while back.  I have ceased having this issue after recent updates.  Still watching it, but have not been able to re-create this issue in the previous 8 flights.

**Comment by MrB0ssMan** [comment]
Perhaps I have an old version I will delete and start again.

**Comment by crazytimtimtim** [comment]
> 
> 
> Perhaps I have an old version I will delete and start again.

Is it working?

**Comment by MrB0ssMan** [comment]
> > Perhaps I have an old version I will delete and start again.
> 
> Is it working?

No i just tried a flight and after a short while the trim went full and nosed the aircraft upwards.

i have reinstalled the aircraft and used the latest version.

**Comment by mSparks43** [comment]
this should be resolved in the latest ap, please retest, comment here and I'll reopen if it persists.
