### ISSUE TITLE
Selected Altitude and Speed pointers missing when out of view

### ISSUE THREAD

**Issue by MCCVeen** [mSparks43/747-400#325]
![image](https://user-images.githubusercontent.com/75425109/105874682-2827e580-5ffd-11eb-887e-1b515c0611c7.png)
![image](https://user-images.githubusercontent.com/75425109/105875410-0ed36900-5ffe-11eb-87d4-5b5ed6ed4806.png)

**Comment by airfightergr** [comment]
Same like issue #87. Require the same approach.
