### ISSUE TITLE
NO V SPD should be smaller [CRT]

### ISSUE THREAD

**Issue by MCCVeen** [mSparks43/747-400#328]
![image](https://user-images.githubusercontent.com/75425109/105876465-4ee71b80-5fff-11eb-8a19-24d17c581fc6.png)
![image](https://user-images.githubusercontent.com/75425109/105876509-560e2980-5fff-11eb-9ea8-a9d806886184.png)

**Comment by Matt726-S** [comment]
noted issue, will be fixed soon

**Comment by Matt726-S** [comment]
fixed in latest pull request

**Comment by MCCVeen** [comment]
> fixed in latest pull request

It needs to be a bit lower so that it's below the speed bug, it needs to be a bit bigger as well so that SPD is half on the same height as the end of the artificial horizon and the NO stops where the speed bug stops as well.

![image](https://user-images.githubusercontent.com/75425109/106786554-f3e0a480-664e-11eb-8f7c-40226d173b93.png)
![image](https://user-images.githubusercontent.com/75425109/106786801-3f934e00-664f-11eb-8a80-b94c34021f0d.png)

**Comment by Matt726-S** [comment]
i think you can close these two issues
