### ISSUE TITLE
NO V SPEED should be lower [LCD]

### ISSUE THREAD

**Issue by MCCVeen** [mSparks43/747-400#329]
![image](https://user-images.githubusercontent.com/75425109/105876830-a1283c80-5fff-11eb-8ef6-0d4d18120d51.png)
![image](https://user-images.githubusercontent.com/75425109/105876868-a8e7e100-5fff-11eb-9cc9-63708df8250f.png)

**Comment by Matt726-S** [comment]
fixed in latest pull request
