### ISSUE TITLE
Particle effects on touchdown

### ISSUE THREAD

**Issue by jmsantafe** [mSparks43/747-400#33]
Adding smoke when the wheels hit the ground would be awesome.

**Comment by jmsantafe** [comment]
The user who made the APU blur said that they would do this.

**Comment by mSparks43** [comment]
This is an xplane bug. The particles are there but they dont appear in replay

**Comment by jmsantafe** [comment]
Particles for the wheels are non-existent. There are particles for the APU, wings, and engines but none for the wheels. The fact that particles don't show in replay is not what I am reporting here.
