### ISSUE TITLE
FMC should spring to IDENT page

### ISSUE THREAD

**Issue by MCCVeen** [mSparks43/747-400#330]
When you select FMC in the MENU it should spring to the IDENT page. Currently it still spring to the CRJ style FMC.

![image](https://user-images.githubusercontent.com/75425109/105888479-4d245480-600d-11eb-956b-5023294d7371.png)
![image](https://user-images.githubusercontent.com/75425109/105888512-5c0b0700-600d-11eb-80e6-9a96c162cb3e.png)

**Comment by crazytimtimtim** [comment]
We're looking into a fix.

**Comment by Matt726-S** [comment]
this issue has been solved you should close it

**Comment by crazytimtimtim** [comment]
It hasn't. Remember mSparks and Marauder didn't want to change it because
we wouldn't be able to access the CO RTE page.

**Comment by Matt726-S** [comment]
> It hasn't. Remember mSparks and Marauder didn't want to change it because we wouldn't be able to access the CO RTE page.
> […](#)

then make it appear normally not some dumb default fmc page

**Comment by crazytimtimtim** [comment]
yep, I believe this has been resolved. Now we just need to get @mSparks43 to merge #462 which addresses a similar issue...
