### ISSUE TITLE
CONFIG STAB Take Off warning with Stabilizer Trim in green band

### ISSUE THREAD

**Issue by MCCVeen** [mSparks43/747-400#331]
![image](https://user-images.githubusercontent.com/75425109/105888875-d471c800-600d-11eb-90ad-d10ead3a76b9.png)
![image](https://user-images.githubusercontent.com/75425109/105888898-dd629980-600d-11eb-9e7b-e880b8310ed9.png)
![image](https://user-images.githubusercontent.com/75425109/105888970-e9e6f200-600d-11eb-83ad-345e495489bc.png)

**Comment by mSparks43** [comment]
ATM this also sounds if you haven't configured the take off CG that defines the green band.
