### ISSUE TITLE
APU gen lights do not extinguish when APU dial off

### ISSUE THREAD

**Issue by Matt726-S** [mSparks43/747-400#332]
i remember when you leave the APU gens to on, they should turn off and stop electrical power on its own when you switch the APU dial to off. on this model, you have to push the gens to OFF so they say AVAIL, and then select the dial to off. when i leave the gens to ON and then turn the APU dial to off, the gen light stays on when it should automatically go off. also, when i select the dial to off while leaving the gen buttons on, i can’t turn the gens off, they are stuck at the ON position

**Comment by mSparks43** [comment]
it takes 60 seconds for the APU to shutdown

**Comment by Matt726-S** [comment]
i know it takes 60 seconds, its just when the apu selector is moved to off while the gens are still on, the generator lights should turn off since they no longer provide electrical power, however still run unti 60 seconds

**Comment by crazytimtimtim** [comment]
Even with the cooldown, the power is lost immediately. I will add this to my list of things to fix @Matt726-S .
