### ISSUE TITLE
FD not precise 

### ISSUE THREAD

**Issue by Matt726-S** [mSparks43/747-400#333]
when autopilot is on, the aircraft should precisely follow the flight director bars, where the two bars intersect right into the center circle of the “airplane symbol”.
![986111D7-684C-4D89-84FC-FEE6933E5519](https://user-images.githubusercontent.com/62818033/106007186-07ef3980-6084-11eb-9efe-efac803f09b6.jpeg)
![007AD3A0-89A4-4F77-8E1D-73528798A5BC](https://user-images.githubusercontent.com/62818033/106007189-0887d000-6084-11eb-8dd9-72990813b949.png)

**Comment by mSparks43** [comment]
Current version is
![image](https://user-images.githubusercontent.com/6773686/151874264-fe26b08a-96ba-4494-bfd1-f2fef28cf08e.png)
