### ISSUE TITLE
PFD vspeeds and flap speeds issues

### ISSUE THREAD

**Issue by Matt726-S** [mSparks43/747-400#334]
1: Vspeeds should disappear after landing: after landing, the vpseeds on PFD should disappear and go to the NO V SPD indication

2: vpseeds and flap speeds are being displayed beyond the speed tape range

3: vpseed (and flap speeds) sizes are too big or too thick, but i will fix this for you

![4A0D881E-4951-4446-B911-C68451703C14](https://user-images.githubusercontent.com/62818033/106007782-a67b9a80-6084-11eb-9ce3-8b5e0f628e8e.jpeg)

**Comment by mSparks43** [comment]
please retest
