### ISSUE TITLE
ND heading up & track up mode disagree

### ISSUE THREAD

**Issue by gHashFlyer** [mSparks43/747-400#335]
@mSpar
![2021-01-27_115505](https://user-images.githubusercontent.com/77414195/106028385-ded9a380-6099-11eb-94de-d8f819cbaa79.jpg)
ks said, "One mode is supposed to show heading up, the other track up, one of them the track line is broken."

**Comment by Juppie902** [comment]
Hmmm maybe you've input AP to follow HDG ?
Reminds me of a HDG SEL dashed line..
Wikipedia example , no dashed line : https://en.wikipedia.org/wiki/File:Navigation_Display_(ND)_on_Boeing_747-400_(cropped).jpg
Another example with dashed line : https://www.flightsensation.com.au/wp-content/uploads/2016/03/737747777.png

**Comment by mSparks43** [comment]
The issue is the purple flight plan line and white track line should be aligned. the cause is that APP/VOR/MAP don't abide by
![image](https://user-images.githubusercontent.com/6773686/114747263-efbcbb80-9d50-11eb-8f35-b1a5063dc2fe.png)

for all elements on the display.
