### ISSUE TITLE
fire handles don’t actually shutoff engines

### ISSUE THREAD

**Issue by Matt726-S** [mSparks43/747-400#337]
when you pull the fire handles, it “closes the related engine and spar fuel valves, closes the related engine bleed air valve, trips off the related engine generator, shuts off hydraulic fluid to the related engine-driven hydraulic pump, depressurizes the related engine-driven hydraulic pump, and arms both related engine fire extinguishers” -FCOM

in this model, the fire switches don’t do anything, they don’t even shut down the engine and just seem cosmetic.

**Comment by mSparks43** [comment]
Can't recreate this, are you turning them after you pull them out?
![image](https://user-images.githubusercontent.com/6773686/106375050-088c1680-6389-11eb-9af0-b20fd9342047.png)

**Comment by Matt726-S** [comment]
when you PULL the fire handles, they should shut down the engines and stop the flow of the things i mentioned. when you TWIST the handles after pulling them, they discharge the fire extinguisher into the engine/nacelle.

(also there is a feature in the real aircraft that locks the fire bottles so you cant pull them until there is a fire warning, or the fuel control switches are moved to cutout. the circle buttons under the bottles unlock them so you can pull the fire bottles. this doesn’t have to be implemented right now but is a nice safety feature for the future)

**Comment by crazytimtimtim** [comment]
The problem with that is since it's a sim, I think it'll be difficult to do with a mouse. It's not like having hands.

**Comment by Matt726-S** [comment]
> The problem with that is since it's a sim, I think it'll be difficult to use that fire handle lock with a mouse. It's not like having hands.

i think pmdg made it so when you push it down, it’ll hold down permanently by itself until you push it.

main topic is tho, that when you pull the bottles, it should do the things that i mentioned
another thing is, when you twist the fire bottle, it should have that BTL DISCHARGE message appear immediately

**Comment by crazytimtimtim** [comment]
This sounds like an easy fix. I'll do it.

**Comment by crazytimtimtim** [comment]
I'm trying to think of the best way of doing this. I could either fail the engines using X-Plane failures, I could just shut down the engines, or I could actually close the valves and do all the stuff the switch does. (Idk if the needed datarefs exist to do the last one though)

**Comment by mSparks43** [comment]
> I'm trying to think of the best way of doing this.

I would say have the action the fuel switches control
![image](https://user-images.githubusercontent.com/6773686/117082544-de107780-ad42-11eb-93a4-832804fc4d81.png)
anded with if the fire handles are extended.

BUT, pull out the fcom reference before giving it any thought/dev time, because likely its explained quite specifically in there.

**Comment by crazytimtimtim** [comment]
Ok, I made it just flip the switches off, and in order to move them on, you need to push the fire handle back in.

**Comment by crazytimtimtim** [comment]
I could've done it more realistically, what do you think? I can have it fire a shutdown command, and make sure the engine can't be restarted until it's pushed back in.

Or, I could actually close the engine and spar fuel valves, close the engine bleed air valve, trip off the engine generator, and shut off hydraulic fluid to the engine-driven hydraulic pump. Not sure if all those datarefs/commands exist though.

**Comment by mSparks43** [comment]
last merge is very broken, undone.

**Comment by crazytimtimtim** [comment]
🤦 sorry, sorry. I thought I tested it, maybe it was different from what I posted? What was wrong?

**Comment by mSparks43** [comment]
> What was wrong?

it made the fuel switch on the pedestal flick up and down

**Comment by crazytimtimtim** [comment]
uhhh that didn't happen in testing. I must have changed something before making the pull request. Sorry.

**Comment by mSparks43** [comment]
best way to deal with this is probably in the fuel system. Find wheret it sets the shutdown cas message then trace back the logic and stick an "and not fire handle pulled" somewhere fuel flow is being set.

**Comment by crazytimtimtim** [comment]
roger
