### ISSUE TITLE
“speedbrakes extended” caution on touchdown

### ISSUE THREAD

**Issue by Matt726-S** [mSparks43/747-400#339]
when i touchdown, the EICAS message “speedbrakes extended” appears. this eicas message should only be an inflight alert, and doesn’t play on the ground

**Comment by mSparks43** [comment]
It should only appear on touchdown if you throttle up with them up

**Comment by MCCVeen** [comment]
> It should only appear on touchdown if you throttle up with them up

If the throttles are past a certain point the speedbrakes will automatically retract, the speedbrakes will not stay extended and the >SPEEDBRAKE EXT message should not be displayed. This is to avoid a go around where the pilot is distracted by putting the speedbrakes up or potentially forgetting it and having too much drag on climb out

**Comment by mSparks43** [comment]
should be fixed, please retest
