### ISSUE TITLE
autopilot disconnect eicas

### ISSUE THREAD

**Issue by Matt726-S** [mSparks43/747-400#340]
when the autopilot is disconnected, the eicas message >AUTOPILOT DISC should show in red until the alarm stops by resetting the disconnect bar to the original position or pressing the yoke button again

edit: if you could add this with datarefs and everything, i may be able to use that for the autopilot disconnect sound in FMOD, since a dataref has to be =1 for the alarm to loop, then when it is =0 it stops, but the current/default autopilot disconnect dataref automatically turns back to 0 after a few seconds

**Comment by crazytimtimtim** [comment]
hmmm, so it seems like the sparky doesn't have an autopilot disco message at all? All I see is an autopilot failure one.

**Comment by mSparks43** [comment]
> hmmm, so it seems like the sparky doesn't have an autopilot disco message at all? All I see is an autopilot failure one.

https://github.com/mSparks43/747-400/blob/7e14f14a22908b226f068e24d02861d8f516fa36/plugins/xtlua/scripts/B747.87.xt.warning/B747.87.xt.warning.lua#L75

**Comment by crazytimtimtim** [comment]
> > hmmm, so it seems like the sparky doesn't have an autopilot disco message at all? All I see is an autopilot failure one.
> 
> https://github.com/mSparks43/747-400/blob/7e14f14a22908b226f068e24d02861d8f516fa36/plugins/xtlua/scripts/B747.87.xt.warning/B747.87.xt.warning.lua#L75

BUt where's the code that triggers it? Also, how did you link it here?

**Comment by mSparks43** [comment]
> > > hmmm, so it seems like the sparky doesn't have an autopilot disco message at all? All I see is an autopilot failure one.
> > 
> > 
> > https://github.com/mSparks43/747-400/blob/7e14f14a22908b226f068e24d02861d8f516fa36/plugins/xtlua/scripts/B747.87.xt.warning/B747.87.xt.warning.lua#L75
> 
> BUt where's the code that triggers it? Also, how did you link it here?

copy perma link to link to lines in files.
the cas is all automated, just set the status of warn/caution/info you want to display to 1 and the cas system takes care of the rest such as the push that closed this issue.
