### ISSUE TITLE
Outer main gear too far back

### ISSUE THREAD

**Issue by MCCVeen** [mSparks43/747-400#345]
The outer main gear should be positioned a lot more forward, rn it collides with the inner main gear during retraction. Other screenshot is the iFly 747. For real reference see this: https://www.youtube.com/watch?v=HWDhS11BXhs

![744 landing gear](https://user-images.githubusercontent.com/75425109/106818795-18517680-6679-11eb-8f16-619e756c389d.PNG)
![sparky 744 landing gear](https://user-images.githubusercontent.com/75425109/106818800-1982a380-6679-11eb-93e0-d586fafddbe3.PNG)

**Comment by Matt726-S** [comment]
looks like a modeling issue, we cant really fix this now because we’re trying to fix systems first

**Comment by crazytimtimtim** [comment]
I believe some work is being started on remodeling the fuselage. This will be fixed too, but it will take a while to do. A lot of stuff needs to be remodeled.

**Comment by mSparks43** [comment]
I would say this is before the wheels through the floor was fixed looking at the angles, but there is still a second or so of collision with both the doors if someone wants to take this on they are free to do so, the main issue is the wheels dont fit inside the compartment
![image](https://user-images.githubusercontent.com/6773686/114745944-7d97a700-9d4f-11eb-905c-1b97f276db72.png)
