### ISSUE TITLE
IRS off PFD ND

### ISSUE THREAD

**Issue by MCCVeen** [mSparks43/747-400#346]
The Radio Altitude, airplane symbol, DH, MDA, white and amber boxes around TRK/HDG and should be displayed even with IRSs off.

![image](https://user-images.githubusercontent.com/75425109/106823343-112e6680-6681-11eb-97cd-0726a8d505a6.png)
![image](https://user-images.githubusercontent.com/75425109/106823391-2b684480-6681-11eb-903d-6da927b3022b.png)
![image](https://user-images.githubusercontent.com/75425109/106826804-f14e7100-6687-11eb-8220-838335e674f4.png)
![image](https://user-images.githubusercontent.com/75425109/106826822-f7dce880-6687-11eb-901f-71f94ec10520.png)

**Comment by Matt726-S** [comment]
also, i believe the ILS indicators, FD, CMD, stuff like that is also shown on PFD even with irs off

**Comment by crazytimtimtim** [comment]
Fixing.
