### ISSUE TITLE
AS tape under 30 kts IAS should always be 30

### ISSUE THREAD

**Issue by MCCVeen** [mSparks43/747-400#347]
It should always be 30, currently the second digit still changes.

![image](https://user-images.githubusercontent.com/75425109/106827765-50f94c00-6689-11eb-861f-bb0f09040ca3.png)
![image](https://user-images.githubusercontent.com/75425109/106827874-84d47180-6689-11eb-8d1a-cbb153ba6402.png)

**Comment by crazytimtimtim** [comment]
I imagine this could be fixed by making the displayed airspeed always equal 30 if the indicated airspeed from the pitot is less than thirty. Something like this : 
`lua
if IAS_dataref  < 30 then
displayed_IAS_dataref = 30
else
displayed_IAS_dataref = IAS_dataref
end
`
