### ISSUE TITLE
Lower Yaw Damper button triggers Upper Yaw Damper

### ISSUE THREAD

**Issue by MCCVeen** [mSparks43/747-400#348]
Just like the title says. Also sometimes when you quickly turn the Upper button off and the Lower on the upper will go back on.

https://user-images.githubusercontent.com/75425109/106828626-dc271180-668a-11eb-83fe-e5635ef03098.mp4

**Comment by crazytimtimtim** [comment]
I don't see what's wrong here.

**Comment by MCCVeen** [comment]
> I don't see what's wrong here.

focus on the left yaw damper button as I turn on the right yaw damper button

**Comment by crazytimtimtim** [comment]
Weird bug. I can't find anything that could be causing it.

**Comment by mSparks43** [comment]
This was almost certainly related to there being only one yaw damper switched on and off, now there are two independent yaw dampers for upper and lower rudder simulated it should be resolved.
