### ISSUE TITLE
Aggressive flare with autoland

### ISSUE THREAD

**Issue by jmsantafe** [mSparks43/747-400#35]
The flat when on auto land is very aggressive, quick, and in my opinion, a bit late.

**Comment by mSparks43** [comment]
Id agree. the code/parameters for this are all in plugins/xtlua/scripts/autopilot/autoland.lua

there has already been a bit more tuning done on the one on navigation systems, recently added some code to grab the stable approach pitch which helped a lot, probably a little more todo to get it just right
