### ISSUE TITLE
ND "MAP" annunciator should be lower for range readout

### ISSUE THREAD

**Issue by MCCVeen** [mSparks43/747-400#352]
It should be repositioned to about 3/8 range in map mode, so that the range readout can be displayed. The range readout does not disappear with IRS off

![image](https://user-images.githubusercontent.com/75425109/106833870-a0914500-6694-11eb-8563-25ced6e69add.png)
![image](https://user-images.githubusercontent.com/75425109/106833830-91aa9280-6694-11eb-8394-606232cfb5da.png)

**Comment by crazytimtimtim** [comment]
Fix incoming.

**Comment by crazytimtimtim** [comment]
Shouldn't those white bands also be there when not aligned?

**Comment by MCCVeen** [comment]
> Shouldn't those white bands also be there when not aligned?

I believe it appears on the first example screenshot because TFC is selected on the EFIS, as shown by the TCAS FAIL. Not too sure tho

**Comment by crazytimtimtim** [comment]
Sorry I haven't one this yet, will be included in my next pull request. 

After some learning I found those range arcs are an aircraft option; some have them and some don't. The Sparky doesn't come with them, rather those are from the TerrainRadar plugin. I'd like to create a custom texture and make a simconfig option for it, but we're still waiting on DrGluck's custom version with no range arcs.
