### ISSUE TITLE
Autothrottle can not be armed with 2 engines inop

### ISSUE THREAD

**Issue by MCCVeen** [mSparks43/747-400#357]
With 2 or more engines off, the Autothrottle system will not work. 

![image](https://user-images.githubusercontent.com/75425109/106983165-bb7fba00-6765-11eb-9895-976dfac712f3.png)
![image](https://user-images.githubusercontent.com/75425109/106983213-cd615d00-6765-11eb-839d-5d62e04164d0.png)

**Comment by mSparks43** [comment]
Should be fixed, please retest
