### ISSUE TITLE
PLugin does not reinitialize when reloading  aircraft - glass panels stay blank - must restart XP

### ISSUE THREAD

**Issue by dkhawkeye** [mSparks43/747-400#358]
This occurs when the aircraft is set to start up with engines running.
Mac OS Mojave XP 11.51. Version 1.0 of 747.
First time loading aircraft works fine with engines running.  Trying to reload aircraft either through developer menu or changing out aircraft for another and then reloading aircraft will not initialize glass panels.  They are blank. I have to restart XP to get the aircraft to fully load.
PLugin must not be reinitializing under this circumstance.
This is important for faster testing - dont want to spend time starting from cold and dark just to test a Planemaker change.

**Comment by Matt726-S** [comment]
i have a similar issue, except none of my buttons work property when i reload

**Comment by ivq001** [comment]
I have experienced the same problem under Catalina 10.15.7, XP 11.50/51, no idea what version of 747 (how can you tell?), have to restart XP if I want to do a second flight.

IanQ

**Comment by mSparks43** [comment]
Please retest.

**Comment by crazytimtimtim** [comment]
I have all kinds of problems like this when reloading aircraft, including
random spool-down sounds.
