### ISSUE TITLE
Wing anti-ice cannot be turned on, VALVE light stays illuminated

### ISSUE THREAD

**Issue by rKsanu2MMYvypWePtQWM** [mSparks43/747-400#359]
This is how the approach looks like when you can't de-ice your wings
![Screenshot_20210206_173820](https://user-images.githubusercontent.com/35463654/107122741-2df5b480-68a2-11eb-8b08-651c1c6d440f.png)

**Comment by andrewjj20** [comment]
I was looking into this after experiencing a similar issue. at least on older 747 models, wing anti-ice is only available with flaps and slats up.
When looking into the problem of icing in general I cam across this advice: https://www.flightliteracy.com/icing-operations/ 
To summarize, keep the aircraft in a configuration for the anti-ice systems to work as long as possible and increase approach speed. The article suggests a 25% increase.

**Comment by rKsanu2MMYvypWePtQWM** [comment]
In the FCOM it says that Anti-ice with LE flaps extended is ineffective. Does it mean that the VALVE light should still extinguish?

**Comment by andrewjj20** [comment]
I was under the impression that Anti-ice is disabled with flaps extended. That would create a disagreement between the button configuration and the actual configuration and so the VALVE light would be illuminated to show this disagreement.

**Comment by mSparks43** [comment]
agreed

**Comment by mSparks43** [comment]
seems to work as described in
![image](https://user-images.githubusercontent.com/6773686/116376034-2514df00-a810-11eb-9bd8-00c2438c8fdc.png)
