### ISSUE TITLE
airplane symbol on pfd disappears when irs off

### ISSUE THREAD

**Issue by Matt726-S** [mSparks43/747-400#365]
whenever the irs is off or not aligned, the airplane symbol disappears
![8628B595-F784-4F5F-8218-02B54CE0C05D](https://user-images.githubusercontent.com/62818033/107160306-775a0880-6963-11eb-99ad-ccaf753d6612.jpeg)

**Comment by MCCVeen** [comment]
You can close this, I already opened an issue about this :)
