### ISSUE TITLE
“gps irs” on ND doesn’t sync with light knob

### ISSUE THREAD

**Issue by Matt726-S** [mSparks43/747-400#366]
if you turn the ND knob to lower the lights, this indication doesn’t follow with the rest of the display
![97BC60D9-C541-49CD-8EDF-56EDE4FB693D](https://user-images.githubusercontent.com/62818033/107160351-b720f000-6963-11eb-8223-5b61704cece5.jpeg)

**Comment by crazytimtimtim** [comment]
Found the cause, looks like somebody screwed up the lighting knobs. Fix coming soon.
