### ISSUE TITLE
Librain Not Working

### ISSUE THREAD

**Issue by crazytimtimtim** [mSparks43/747-400#374]
Librian just doesn't work on 11.51r1 and openGL. It still works in the Zibo.

**Comment by crazytimtimtim** [comment]
Also, the Zibo has a different mode for Vulkan. It doesn't look as good as normal librain, but it's better than nothing, and it works in Vulkan.

**Comment by mSparks43** [comment]
I can't use openGL for performance reasons, Librain on openGL was even worse.
Looking forward to an updated Librain for Vulkan, but until then there is not much to say or do.

**Comment by crazytimtimtim** [comment]
Don't you think we can try to still get it running for OpenGL? I sometimes must use OpenGL and I see almost no performance difference between ogl and Vulkan. I don't know anything about Librain but it would be nice to get it working in ogl at least.

**Comment by mSparks43** [comment]
https://github.com/skiselkov/librain/issues/23
https://github.com/skiselkov/librain/issues/24

**Comment by crazytimtimtim** [comment]
?  It works in all the other aircraft in OpenGL that have librain, so it must be a Sparky problem.
