### ISSUE TITLE
Throttle Lever Sounds

### ISSUE THREAD

**Issue by crazytimtimtim** [mSparks43/747-400#375]
This is a request: Add sounds for the throttle levers when they are pushed to idle or maximum - like a little click 
as they hit the edge of their housing. I also would like some sort of click for the reverse levers. 
     For example, Try pushing the throttle and pulling it back all the way in the Zibo mod, you'll hear a little click once it gets to idle.
     I will explain further if you can't figure out what I'm trying to say, I don't think I wrote it well :)

**Comment by Matt726-S** [comment]
interesting, i actually don’t think the zibo has a click sound at the top of reverse thrust and you may have confused it with the automatic spoiler deploy, but i will look into adding something like that, as well as full power.

**Comment by crazytimtimtim** [comment]
> 
> 
> interesting, i actually don’t think the zibo has a click sound at the top of reverse thrust and you may have confused it with the automatic spoiler deploy, but i will look into adding something like that, as well as full power.

Yeah, the Zibo only has a sound when closing the throttle levers, and it would be nice to also have it for the full power position and reverser levers. It's especially helpful for me because I don't have physical throttle levers, so the sound allows me to tell if it's in idle without having to look at the display or down at the throttle levers.
