### ISSUE TITLE
active thrust mode, although A/T is disarmed 

### ISSUE THREAD

**Issue by oMrSmith** [mSparks43/747-400#377]
_No_ thrust-mode can be active
as long as the A/T is _disarmed_,
hence the left column for the FMA of the active thrust mode
should always be _blank_
as long as the A/T is _disarmed_. 

![FMA](https://user-images.githubusercontent.com/78870770/107629069-dd93a380-6c61-11eb-89ba-8b54a0fb5652.jpg)

**Comment by mSparks43** [comment]
Please retest, should be fixed.

**Comment by oMrSmith** [comment]
Retest:
![747-400 - 2021-04-08 12 28 30](https://user-images.githubusercontent.com/78870770/114192853-3de74e80-994e-11eb-90b5-eccfa16e0afd.png)

**Comment by mSparks43** [comment]
should be fixed with https://github.com/mSparks43/747-400/commit/4b802ea6622d29fb91495c4cd01104d0b2d76360

**Comment by oMrSmith** [comment]
Retest with VNAV:
Disarming A/T will blank out the thrust mode: Great!
Rearming the A/T will bring back the FMA for the appropriate thrust mode: Great!

Remaining Problem:
Rearming the A/T will bring back the FMA for the appropriate thrust mode THR REF
but the thrust mode itself will not actually work.

I tested like this:
THR REF | LNAV | VNAV SPD
disarm A/T
decrease throttle
rearm A/T showing:
THR REF | LNAV | VNAV SPD
without throttles going back to N1

**Comment by mSparks43** [comment]
remaining sounds like #473
