### ISSUE TITLE
PFD: The FMA "CMD" must change to "FD" when disengaging the AP

### ISSUE THREAD

**Issue by oMrSmith** [mSparks43/747-400#378]
... which it doesn't:

![DISC](https://user-images.githubusercontent.com/78870770/107630000-36b00700-6c63-11eb-975a-d0e5d46962ee.jpg)

What matters are the FMAs rather than the lights of the MCP buttons.
So I'd be glad if this issue could be fixed. It's quite scaring ;):

_The PFD tells you that CMD would be engaged even though it's not_.

It should look more like this:

![SSG FD](https://user-images.githubusercontent.com/78870770/108791087-8bfee900-757e-11eb-9d68-6d9ac7cd09a1.png)

**Comment by Matt726-S** [comment]
i think if you push the “yoke button disconnect”, then it’ll say command. however this is still an issue that should be fixed

**Comment by mSparks43** [comment]
Pretty sure this is fixed now. please retest.

**Comment by oMrSmith** [comment]
Yes disengaging CMD will now switch to FD.
Only problem which remains
is that pitch-, roll- and thrust-mode
get ereased when disconnecting the AP.
I reported this in another issue though.
