### ISSUE TITLE
"[ ][ ]/" instead of "00/" for flaps setting on TAKEOFF REF 

### ISSUE THREAD

**Issue by oMrSmith** [mSparks43/747-400#382]
For more consistency I want to propose
the following design of the the TAKEOFF REF page 
which I have adjusted just slightly 
using paint ;).

![TO Ref](https://user-images.githubusercontent.com/78870770/107696741-a00b3680-6cb2-11eb-9e32-61f288f58f74.png)

This also complies more 
with what I found in the manual:

![Takeoff Page](https://user-images.githubusercontent.com/78870770/107696930-dba60080-6cb2-11eb-95ad-485715f7cb3a.png)

**Comment by crazytimtimtim** [comment]
So you have already made this change? Make a pull request!

**Comment by oMrSmith** [comment]
Thank you for the fix!
