### ISSUE TITLE
Turn-around TOGA

### ISSUE THREAD

**Issue by gHashFlyer** [mSparks43/747-400#388]
On turn-around flights (e.g., KMEM-KEWR, followed by KEWR-KMEM without re-starting the sim or reloading the aircraft), when VNAV is armed, the speed is no longer displayed on the mode control panel (see image) At the same time, the console displays an unending pair of messages: "updated speed simDR_onGround", and "below 10000 on ground".

Disarming VNAV halts this pair of messages.

Associated with this issue, after pressing TOGA, the PFD displays "THR REF" on the left side of the display, not "TOGA | TOGA | TOGA" across the entire display as usual.  

![2021-02-15_142037](https://user-images.githubusercontent.com/77414195/107987315-c4f5f700-6f9b-11eb-86b1-f0757c52617c.jpg)

![2021-02-15_142329](https://user-images.githubusercontent.com/77414195/107987339-cf17f580-6f9b-11eb-963b-76ef60b2acf7.jpg)

**Comment by gHashFlyer** [comment]
This issue appears to be resolved.

**Comment by crazytimtimtim** [comment]
@mSparks43 you can close if resolved

**Comment by gHashFlyer** [comment]
Update....this is not resolved.  When VNAV is armed, the speed is no longer displayed on the mode control panel (see image)

**Comment by Matt726-S** [comment]
> Update....this is not resolved. When VNAV is armed, the speed is no longer displayed on the mode control panel (see image)

i remember when vnav is active, the speed window will close. it seems like vnav cant distinguish armed and active, since when its armed the speed window should show

**Comment by mSparks43** [comment]
Cant recreate this
![image](https://user-images.githubusercontent.com/6773686/114236803-71dc6700-9982-11eb-90d9-47f82ee7bad8.png)

**Comment by gHashFlyer** [comment]
You can close it as I believe this issue has been resolved.
