### ISSUE TITLE
Rudder authority

### ISSUE THREAD

**Issue by kudosi** [mSparks43/747-400#394]
When doing a flight test it was hard do perform flat turns, which means to do turns with bank angle zero. Obviously, the rudder has insufficient effectivity.

**Comment by crazytimtimtim** [comment]
I don't think an airliner can do a flat turn like that.

**Comment by kudosi** [comment]
They can, it is required by the certification specifications. They must Show this evem with two engines inoperative, See FAR 25.147

**Comment by crazytimtimtim** [comment]
Interesting, I didn't know that!

**Comment by mSparks43** [comment]
is this definitely rudder authority and not rather aileron authority?
if I go hard over on the rudder there doesn't seem to be enough aileron authority to keep the aircraft level

**Comment by kudosi** [comment]
I tested this with two engines on Idle. So a large part of the yawing moment from the rudder is required to overcome the asymmetric thrust moment. However, even in this case there must be sufficient authority to yaw into the operative engines without banking.
I admit that this is a special condition and surely not the top priority.

**Comment by mSparks43** [comment]
please retesr

**Comment by kudosi** [comment]
Test accomplished. Rudder still has too low authority. Normally with rudder half deflected, you would get 5-6 degree sideslip (side slip indicator bar on PFD shifted to the left/right (bank controlled with ailerons to obtain constant heading). In the sim, you cannot simulate steady heading sideslip, obviously the ailerons overcompensate the yawing moment from the rudder. Don't know whether the rudder is the problem or the ailerons. Will do more tests.

**Comment by mSparks43** [comment]
just a thought on this. In the helos at least the XP11 slipskid dataref is bugged (shows slipskid when there is none, doesnt show slipskid when there is)

Could this be a slip indicator issue rather than a flight control issue?
