### ISSUE TITLE
Time-to-time Engine Shutdown Upon Spawning In With Engines Started

### ISSUE THREAD

**Issue by THEONEANDONLYPLANE** [mSparks43/747-400#40]
From time-to-time, engines will shut-down for no-apparent-reason, despite just spawning in with engines started.

**Comment by mSparks43** [comment]
This is likely a xtlua issue in the old windows build.
There is an updated xtlua that has better initialisation for windows on
https://github.com/mSparks43/XLua/blob/master/deploy/xtlua/64/win.xpl

but based on a build that has had multiple reports of total systems failure on windows. (plugin starts, but lua scripts dont)
I'll probably move this onto navigation systems to make diagnosing the problem easier
