### ISSUE TITLE
APPROACH REF: Missing Spacebar after 2. VREF Speed

### ISSUE THREAD

**Issue by oMrSmith** [mSparks43/747-400#405]
... Just wanted to report this little "beauty-mistake"
which should be easy to fix:

![APPROACH REF](https://user-images.githubusercontent.com/78870770/108713936-30e6db00-7519-11eb-9749-04e81b92c340.png)

**Comment by mSparks43** [comment]
![image](https://user-images.githubusercontent.com/6773686/114235106-fa0d3d00-997f-11eb-8949-776a6366e568.png)

Fixed in https://github.com/mSparks43/747-400/commit/8288882f6374935ef618954af41a9d84b4c4b2f6
