### ISSUE TITLE
parking brake lever/rudder pedal braking

### ISSUE THREAD

**Issue by Matt726-S** [mSparks43/747-400#406]
when parking brake is set, you should be able to push your toe braking to full or push b to release the parking brakes. when this happens, the parking brake lever in the 3d cockpit should go down

when parking brake is not set, you should be able to hold your rudder pedal toe braking down and then pull the lever up while the toe braking is on. 

when you push the letter v or whichever key is used to set parking brakes or “brakes max” or something, then the parking brake lever in the 3d cockpit should go up or down.

**Comment by mSparks43** [comment]
![image](https://user-images.githubusercontent.com/6773686/116302152-1f33e500-a7a1-11eb-871a-c2973932ae93.png)

**Comment by crazytimtimtim** [comment]
yeah...That's what Matt said.
