### ISSUE TITLE
aircraft name incorrect

### ISSUE THREAD

**Issue by Matt726-S** [mSparks43/747-400#408]
the name for the msparks 747 in the x plane menu/map says something like “Boeing 747-400 GE”. the “GE” part is inaccurate since the fmod uses PW engines and the default EICAS configuration with the engine rate indicators matches the PW. i think the the name should just  “Boeing 747-400” for generality. should be a simple fix in planemaker/acf file

**Comment by crazytimtimtim** [comment]
Shouldn't it just be Sparky 747-400 or Sparky 744?

**Comment by Matt726-S** [comment]
i think it should just be Boeing 747-400

**Comment by Juppie902** [comment]
I think its a minor change in the .acf with Plane Maker
