### ISSUE TITLE
master caution light should not appear during startup

### ISSUE THREAD

**Issue by Matt726-S** [mSparks43/747-400#410]
when you turn on ac power for the first time, the master caution light should not illuminate. it should illuminate only when a new caution message shows up.
observe here: no master caution lights illuminate, even though the eicas messages exist: 
https://youtu.be/ja21HBs0vh8

edit: the master caution alert sound should also not play during first startup

**Comment by Juppie902** [comment]
I see that what triggers the MASTER CAUTION light is >AUTOTHROTTLE DISC and when you arm the rocker A/T ARM on the MCP, it goes away. Is this realistic behavior ? IMHO >AUTOTHROTTLE DISC should only show at much later stages in flight if you disconnect A/T ARM rocker switch, would be happy if someone with an FCOM could point us in the right behavior so we can work on a fix!

**Comment by Matt726-S** [comment]
there are some fcoms in the discord

**Comment by mSparks43** [comment]
the startup videos ive seen do have the mc sound a few seconds after the avionics get power.

**Comment by mSparks43** [comment]
Are we happy with the current behaviour now / please retest.
