### ISSUE TITLE
Landing Gear Lever

### ISSUE THREAD

**Issue by crazytimtimtim** [mSparks43/747-400#416]
When I press G to raise the gear, the lever moves to the off position rather than up. It should go straight to up, and then I can manually bring it down to off later.

**Comment by Matt726-S** [comment]
it goes straight up when you’re not on the ground lol

**Comment by crazytimtimtim** [comment]
> it goes straight up when you’re not on the ground lol
Nope, I have to press G twice. 1st time goes to off and second time goes up.

**Comment by Juppie902** [comment]
Ok tried recreating this, this is weird behavior:
pressing G works ok - lever toggles from DN to UP and gear changes pos ok
using my X-55 throttle binding 'raise gear up' and 'lower gear down' (these are stock xplane control assignments):
gear goes DN ok, in cockpit EICAS says gear DN green light , lever is still up position. when raising gear - works ok.
also the following behavior needs fixing: using only mouse, can't move gear handle in cockpit from UP to OFF, it goes only UP --> DN --> OFF --> UP again.
