### ISSUE TITLE
APU starts with battery OFF

### ISSUE THREAD

**Issue by Juppie902** [mSparks43/747-400#421]
fixes #423
 lol no electrical power but APU manages to start if SEL SW set to START position

**Comment by Juppie902** [comment]
![747-400 - 2021-02-26 16 20 45](https://user-images.githubusercontent.com/73952335/109311549-a1119b80-784e-11eb-85b9-3163b1e5c049.png)

**Comment by Matt726-S** [comment]
i think you need to set the apu switch position to ON

**Comment by Juppie902** [comment]
1 ) it should spring back to ON from START
2 ) the issue is that there is no electrical power feeding the aircraft.. how can the APU supply itself with fuel and power the ignition without even battery power ?

**Comment by crazytimtimtim** [comment]
If you fixed this you should make a pull request.

**Comment by Juppie902** [comment]
> If you fixed this you should make a pull request.

Yes, I am having trouble with modifying the commit comment using git hub for desktop, need to switch a client. This is my first fix ever, and in lua, and on a public open source project, bear with me!
I left home atm, will close with PR ASAP.

**Comment by crazytimtimtim** [comment]
> > If you fixed this you should make a pull request.
> 
> Yes, I am having trouble with modifying the commit comment using git hub for desktop, need to switch a client. This is my first fix ever, and in lua, and on a public open source project, bear with me!
> I left home atm, will close with PR ASAP.

OK! I think the website would be easiest.
