### ISSUE TITLE
Oxygen mask panel unreadable

### ISSUE THREAD

**Issue by Juppie902** [mSparks43/747-400#428]
This hurts to look at, even though the 3d model is not that bad, but could do with a refurbishment..
![747-400 - 2021-02-28 7 03 48 PM](https://user-images.githubusercontent.com/73952335/109427925-49fdf900-79fd-11eb-94de-db98c4e87d74.png)

**Comment by Matt726-S** [comment]
a little bit is the texture settings on your end, but yes the texture is horrible. however were not focusing on panel texture/model improvements at the moment and are prioritizing on fixing systems

**Comment by crazytimtimtim** [comment]
There are a few others like that, including the clock (which I think is even more important). Check #401
