### ISSUE TITLE
HDG SEL does not work

### ISSUE THREAD

**Issue by Juppie902** [mSparks43/747-400#429]
AP on , ALT hold on, SPD hold is on, HDG sel does not make aircraft bank to follow selected heading...
from 1:17
https://youtu.be/qQBylYr6tdE

**Comment by mSparks43** [comment]
This is one of the AP switching bugs I'm still working on. In this case the AP isn't even armed (FD displayed on the PFD)
![image](https://user-images.githubusercontent.com/6773686/110129270-0e31ad80-7dc8-11eb-9a24-98cf548bea57.png)
