### ISSUE TITLE
Autopilot C engaged / selected light not working on MCP

### ISSUE THREAD

**Issue by Juppie902** [mSparks43/747-400#431]
autopilot C engaged annunciator light not working without engaging autopilot L or R
from 0:28
https://youtu.be/qQBylYr6tdE

**Comment by oMrSmith** [comment]
I noticed this as well and regard this as one of the most important issues... However in your
video the disconnect actually works and instead engaging CMD does not work
with the FMA remaining "FD" eventhough the CMD MCP light shining...
