### ISSUE TITLE
VNAV: Plane should not climb out in VNAV PTH

### ISSUE THREAD

**Issue by oMrSmith** [mSparks43/747-400#435]
Leading to insufficiant climbrate and overspeed.
It should climb in VNAV SPD...

![747-400 - 2021-03-01 14 36 18](https://user-images.githubusercontent.com/78870770/109505510-f4792900-7a9c-11eb-9113-c8fd4fb38628.png)

**Comment by mSparks43** [comment]
Please retest.

**Comment by oMrSmith** [comment]
Did a quick test. Result:
VNAV climbs in VNAV SPD - great.

One issue:
I think TO/GA pitch / roll modes should
stay active until next/armed modes engage.
Currently there is a short gap between TOGA and VNAV SPD
as well as TOGA and LNAV.
