### ISSUE TITLE
ILS/Localizer not captured

### ISSUE THREAD

**Issue by Pythonjunkies** [mSparks43/747-400#436]
The B747 does not capture the localizer. As soon as the APP button is pressed, the AC turns directly in runway direction. By doing so, it flies parallel to the runway but the Localizer is not captured.

Example EDDF: Tuned ILS frequency and Course  RWY 07R via FMC NAV Page. Flying HDG 040 to capture ILS 07. As soon APP button is pressed, AC turns directly to HDG 070 and flys parallel to the runway, but not aligned with the runway. And when APP button is pressed, the HDG window changes its value from HDG 040 to the runway course.

Thank you btw for this great AC!!! :)

**Comment by mSparks43** [comment]
You should already be on the intercept heading before pressing APP
![image](https://user-images.githubusercontent.com/6773686/110124939-04597b80-7dc3-11eb-95fb-6608809e6c50.png)
