### ISSUE TITLE
PACK sounds play even when no bleed air source selected

### ISSUE THREAD

**Issue by crazytimtimtim** [mSparks43/747-400#442]
PACK sounds play when I turn on any PACK, even if I have all the bleeds off. Even if all engines are shut down and APU not running, I still hear PACKS.

**Comment by crazytimtimtim** [comment]
Should be relatively simple to fix, just make the starting condition for the pack sounds require a bleed air source, and make it end if bleed source is lost.

**Comment by Matt726-S** [comment]
> Should be relatively simple to fix, just make the starting condition for the pack sounds require a bleed air source, and make it end if bleed source is lost.

not as easy as you think, there’s no total bleed air dataref

**Comment by crazytimtimtim** [comment]
> > 
> not as easy as you think, there’s no total bleed air dataref

We can make one...

**Comment by crazytimtimtim** [comment]
I believe this is fixed, you can close @Matt726-S

**Comment by crazytimtimtim** [comment]
No Idea why I closed this, I need to check if fixed first.

**Comment by Matt726-S** [comment]
i’m pretty sure i’ve fixed this
