### ISSUE TITLE
waypoint “LATLON”

### ISSUE THREAD

**Issue by Matt726-S** [mSparks43/747-400#443]
as i fly and see photos of the plane, the ND always likes to say “LATLON” as a waypoint. i don’t think real boeings have this on the ND. what does it mean? it sounds like “latitude, longitude”. Is there a way to remove it?

**Comment by crazytimtimtim** [comment]
I think this has been fixed. Can you check again?

**Comment by Matt726-S** [comment]
try flying with a route

**Comment by crazytimtimtim** [comment]
Are you implying it hasn't been fixed?

https://github.com/mSparks43/747-400/commit/04ead2007a207fee5f8939bcc6e0d2e86c5939e2

**Comment by mSparks43** [comment]
please retest, there was an issue with texting being both latlong and LATLON, both should now be hidden.
