### ISSUE TITLE
APU does not start.

### ISSUE THREAD

**Issue by gHashFlyer** [mSparks43/747-400#445]
After selecting APU START, (and waiting as long as 10 minutes) the APU GEN lights do not illuminate. Consequently the APU does not provide power to align the IRS, even though fuel burn suggests it is on.

On Discord a work-around was advised: re-select APU START a few times. I was able to confirm this did eventually start the apu.

**Comment by gHashFlyer** [comment]
**This issue is resolved.**

@Juppie explained how it now works:  from "off" you need to turn to "ON" for about 15 seconds, and when the APU DOOR text appears on EICAS, switch to START, it should return to RUN position after about 5 seconds. APU spool up time is 74-75 secs, after which APU GEN 1 & 2 should be available.

**Comment by crazytimtimtim** [comment]
You can close the issue. I'll edit the readme, because I see this being a popular question.
