### ISSUE TITLE
no sound

### ISSUE THREAD

**Issue by DemonRem** [mSparks43/747-400#454]
hey @mSparks43 
there is no apu or engine sound is that a bug or something
or something with the game?

**Comment by crazytimtimtim** [comment]
There is a whole bunch of stuff going on with the APU right now. Maybe just wait a week or 2 and it will all be fixed. :)

**Comment by DemonRem** [comment]
its all the aircraft as i understand i check all of it

**Comment by crazytimtimtim** [comment]
It must be something with your simulator. I haven't seen anybody else with this issue.

**Comment by Matt726-S** [comment]
try loading another plane with fmod (try the zibo 737) does the sound work there? also, you sure try with the old fmod, so download from the release and see if sound works there

**Comment by DemonRem** [comment]
zibo 737 work just fine

**Comment by Matt726-S** [comment]
> zibo 737 work just fine

download the 747 again from master branch, see if its any different

**Comment by DemonRem** [comment]
ok

**Comment by DemonRem** [comment]
i downloaded the new version but still no sound at alll

**Comment by crazytimtimtim** [comment]
Nobody else is having this problem, it's just you. If other aircraft still have sound then I really don't know what's wrong.

**Comment by mSparks43** [comment]
Closing this as not reproducible. Jump on the discord if you need help getting your sound working.

**Comment by omarmilesi2004** [comment]
i have the same problem
