### ISSUE TITLE
no “>AUTOTHROTTLE DISC” when using throttle disconnect buttons

### ISSUE THREAD

**Issue by Matt726-S** [mSparks43/747-400#464]
when you push the autothrottle disconnect for either of the buttons on the throttles, and eicas message that says >AUTOTHROTTLE DISC should appear, and disengage the autothrottle. when you push one of the buttons again, the eicas message will disappear (it disappears 5 seconds after pushing the button the second time). the autothrottle still stays armed, until you disarm it with the switch on the MCP

**Comment by MCCVeen** [comment]
Duplicate of issue #299
