### ISSUE TITLE
Odd Slat Movement During Pitch-Up

### ISSUE THREAD

**Issue by THEONEANDONLYPLANE** [mSparks43/747-400#465]
Odd behavior exhibited by the slats, when the aircraft is pitched up.

https://streamable.com/xcdejp

**Comment by mSparks43** [comment]
So I can't recreate this at all, what flight settings/speed etc were you at when this is happening?
https://youtu.be/__0j_2GbrB0

**Comment by mSparks43** [comment]
Got it.
