### ISSUE TITLE
Texture issue on Fuel Page

### ISSUE THREAD

**Issue by JoshXPM** [mSparks43/747-400#469]
I'm seeing a slight issue with a pink/magenta line on the fuel page as follows. 
![image](https://user-images.githubusercontent.com/65257518/111880493-592ff100-8982-11eb-9e0c-e312b15edefd.png)

**Comment by Juppie902** [comment]
What
This screenshot looks like a vatsim map or something of that nature

**Comment by JoshXPM** [comment]
I edited the post to have the correct image 30 seconds after posting, see as follows.........

![image](https://user-images.githubusercontent.com/65257518/111886509-6cec4f00-89a4-11eb-95bf-7e74c5ce078e.png)

**Comment by Matt726-S** [comment]
not sure, most of the fuel textures have to be redone with different triggers.
the green pump should have a green fill to it when fuel is being used from them. green ones should also be blank when fuel is not used from them but the tank switch is on. some of the fuel synoptic symbols have smaller boxes. @mSparks43 maybe we should add these so its not confusing if the tank is using fuel or not

**Comment by mSparks43** [comment]
I think this may be fixed by
https://github.com/mSparks43/747-400/commit/1455bcacb84eb2bbe0a0226b6ccd505e1975e320

Can't recreate it anyway.
the pink is B747.fuel.main3_tank.ovrd_jett_pump_fwd.on and aft related
If we get a recreate on updated versions I can look at it again.
