### ISSUE TITLE
THR switch inoperative

### ISSUE THREAD

**Issue by mSparks43** [mSparks43/747-400#473]
![image](https://user-images.githubusercontent.com/6773686/112079222-0de33180-8b80-11eb-994e-81b4ccb9030f.png)

**Comment by mSparks43** [comment]
More detail in FCOM 4.20.4

**Comment by oMrSmith** [comment]
Arming VNAV on ground, 
will now engage thrust mode SPD.

**Comment by mSparks43** [comment]
@oMrSmith could you give more detail? the only change related to this is far is the logic behind the illumination of the switch (it was previously illuminating without pressing the switch).

**Comment by mSparks43** [comment]
More
![image](https://user-images.githubusercontent.com/6773686/114463275-81f38100-9be4-11eb-9025-af77266c374a.png)
