### ISSUE TITLE
A/T switch is defective

### ISSUE THREAD

**Issue by mSparks43** [mSparks43/747-400#474]
![image](https://user-images.githubusercontent.com/6773686/112163735-9815af00-8bed-11eb-831f-935130e6003f.png)

**Comment by rKsanu2MMYvypWePtQWM** [comment]
Disconnected A/T to make sure the engines don't throttle up when descending thru 10k, but when I hit 10k the throttles when up and down about an inch, back to idle again.

**Comment by rKsanu2MMYvypWePtQWM** [comment]
Found something - the throttles get "idled' whenever the speed bug is below the current speed, even with the switch OFF.
