### ISSUE TITLE
mSparks 747 disables ability to move camera

### ISSUE THREAD

**Issue by BadPlane** [mSparks43/747-400#478]
[Log.txt](https://github.com/mSparks43/747-400/files/6255712/Log.txt)

When I activate the mSparks 747, I cannot use my arrow keys or my forward-backward keys to adjust the view. This then continues in whatever other aircraft I load.

**Comment by crazytimtimtim** [comment]
hmmm. I don't know of anybody else with this problem.

**Comment by BadPlane** [comment]
Anything in the log pointing to a issue?

**Comment by crazytimtimtim** [comment]
sorry, haven't looked yet.

**Comment by crazytimtimtim** [comment]
ok, after a quick look I haven't found anthing that would be causing it. Are you on release or master?

Did your sim crash though? There is an error at the end but doesnt't seem related to the 747.

Also, try loading into something else, then loading into the sparky. Do the arrow keys work in the other aircraft before loading the sparky?

**Comment by BadPlane** [comment]
So I am on the master file. I have tried loading things before sparky and after and before the arrow keys work and after they don’t. The sim did crash in the end as well but I don’t think it was due to the 747

**Comment by crazytimtimtim** [comment]
Alright, thanks. Do you think you can properly close X-Plane and send the log again? This allows X-Plane to do it properly.

**Comment by KomPlane** [comment]
Mine also did this today (6 April 2021), it was fine yesterday, so I believe the most recent commit is causing it. (master).  It also disables the joystick hat keys.

**Comment by BadPlane** [comment]
I will get a proper log file when I get home

**Comment by BadPlane** [comment]
> Mine also did this today (6 April 2021), it was fine yesterday, so I believe the most recent commit is causing it. (master). It also disables the joystick hat keys.

Can you send a log in if you can as well

**Comment by crazytimtimtim** [comment]
Interesting. @BadPlane I think some of the errors in your log have been fixed. Are you sure you are on the latest version? Maybe try reinstalling.

**Comment by BadPlane** [comment]
I believe so. I can reinstall and try again and then send a log of that

**Comment by crazytimtimtim** [comment]
Sounds good.

**Comment by BadPlane** [comment]
Would any plugins interfere with this perhaps? What are the errors you are getting?

**Comment by crazytimtimtim** [comment]
I'll update my copy and see if I get the same problem. I just saw some sound and display texture errors, but I believe those have been fixed already, that's why I asked you to make sure it's up to date. There was also an unrelated error at the end that seemed to crash X-Plane. 
![image](https://user-images.githubusercontent.com/64425497/113742460-462e5800-96c8-11eb-873d-7b472c981fa3.png)

Also btw, you have a lot of scenery errors, but those shouldn't be affecting this.,

**Comment by BadPlane** [comment]
Yeah, all just custom scenery from the forums

I don't recognize the error that triggered the crash

Ok please do

I downloaded whatever file you find when you search "mspark 747"

**Comment by crazytimtimtim** [comment]
Alright, I am not having this problem. Download from here: https://github.com/mSparks43/747-400

Click the green "Code" button.
![image](https://user-images.githubusercontent.com/64425497/113750628-b04afb00-96d0-11eb-88ab-72c8b4c9877d.png)

Then click "Download Zip" (last option.)
![image](https://user-images.githubusercontent.com/64425497/113750737-d07aba00-96d0-11eb-98a6-5ce62c02a305.png)

**Comment by BadPlane** [comment]
Ok, Ill try a full redownlaod. I did that before but IDK what happened

**Comment by BadPlane** [comment]
Fixed, Thx
