### ISSUE TITLE
Hitting warn: xtlua time overflow!=%d

### ISSUE THREAD

**Issue by KomPlane** [mSparks43/747-400#480]
On master, my xtlua win.xpl is hitting this message, and it is displayed frequently in the console, with values of %d in the approximate range of 30~50.

I have been experiencing this issue since I transitioned from stable to master, so it isn't related to any of the recent commits. I didn't report it immediately, because I was hoping that time would resolve it.

The only reference to xtlua in Log.txt is the initial load version number: 
`Loaded: C:\Program Files (x86)/Steam/steamapps/common/X-Plane 11/Aircraft/Addon Aircraft/Sparky744/747-400/plugins/xtlua_keysystems/64/win.xpl (com.x-plane.xtlua.C:\Program Files (x86)/Steam/steamapps/common/X-Plane 11/Aircraft/Addon Aircraft/Sparky744/747-400/plugins/xtlua_keysystems/.2.0.3b1).`

My gpu only allows low framerates (plane framerate of about 10 fps, sim framerate about 20 fps) which might be a contributing factor. ... Because a 1 hour flight in the sim can take up to 2 hours in real time (because x-plane slows down due to the frame rate issue), I usually accelerate my ground speed to 2x (Alt-T by default), that may also be a contributing factor.

It seems to cause havoc with vnav (MCP panel doesn't allow SPD or ALT intervent after this happens, and both windows are blanked out no matter which MCP buttons are pressed).

It may be a suggestion to have an xtlua reset option on the plugin menu (or is there already a way to do that?)

I will try to capture a screenshot and/or the output of the console window during a relatively short test flight (without using any acceleration) ... I think that is the output that will be more relevant to analysing the issue further.

**Comment by mSparks43** [comment]
The time overflow warning is triggered when a system frame takes longer than 30 milliseconds (runs independently of xplane and the GPU on a separate thread):
https://github.com/mSparks43/XTLua/blob/ecb59da8568be3af5b2d595a741cbfffaf116a9a/XTLua/src/xlua.cpp#L419

Some of these are to be expected (especially on windows which is terrible at multithreading) - everything completed normally, but hitting that warning means the CPU was unable to complete all its tasks within the expected time frame.

There is a debug option in each of the systems (datarefs containing debug) which can be used to selectively disable systems to see if one in particular is taking the time, but at this point in time there are no known issues other than the CPU being to slow.

The only solution to this is a CPU upgrade I'm afraid, the situation is only likely to get worse as more systems are implemented and more demands are placed on the CPU.

**Comment by KomPlane** [comment]
Thank you.  I was thinking about upgrading and now I have the motivation to do so.
