### ISSUE TITLE
(reopened) QNH always preselected

### ISSUE THREAD

**Issue by MCCVeen** [mSparks43/747-400#485]
To come back to issue #182 

You can set a preset, yes that's true. But normally when switching to STD pressure, the preselect will not be there yet. It isn't until you start moving the BARO knob on the EFIS panel before the preselect appears on the PFD.  Example here: https://youtu.be/lHLfKp89_wE?t=2935

**Comment by MCCVeen** [comment]
So if you're departing, and you press STD on the BARO knob on the EFIS panel, it will switch to this: 
![image](https://user-images.githubusercontent.com/75425109/114330501-25d82080-9b42-11eb-8868-96928ff6f30e.png)

Once you cycle the BARO knob on the EFIS panel, a QNH reading will appear in smaller white text, where you can preselect your QNH. So when you press the STD again on the BARO knob on the EFIS panel, the qnh will be set to whatever QNH has been preselected. That's why it's called a preset/preselect

**Comment by MCCVeen** [comment]
And with "a QNH reading will appear in smaller white text" I mean this that we already have: 
![image](https://user-images.githubusercontent.com/75425109/114330700-90895c00-9b42-11eb-9ce4-23646c4cfc8c.png)

**Comment by mSparks43** [comment]
reopened old one with fcom references
