### ISSUE TITLE
Autopilot doesn't engage

### ISSUE THREAD

**Issue by BlackyTrains** [mSparks43/747-400#486]
![747-400 - 2021-04-12 18 29 55](https://user-images.githubusercontent.com/82400670/114428961-1cd86500-9bbd-11eb-9ff3-d1589e393ac8.png)
Hello all,
Today i tried to fly the plane on VATSIM. Takeoff was just fine, VNAV and LNAV were armed, Route, Speed and Altitude was set. I switched on the autopilot - no success. A/P Disconnect Sound, but no Master Warn / ECAM Message. At around 7000ft,i tried it again - Still the same.  I don't know what's wrong, but i guess it's my fault... But where?

![747-400 - 2021-04-12 18 13 33](https://user-images.githubusercontent.com/82400670/114428460-86a43f00-9bbc-11eb-9dd8-52803c0bbaf4.png)
![747-400 - 2021-04-12 18 13 14](https://user-images.githubusercontent.com/82400670/114428412-72604200-9bbc-11eb-90b9-1000d5df08c5.png)
![747-400 - 2021-04-12 18 13 29](https://user-images.githubusercontent.com/82400670/114428423-75f3c900-9bbc-11eb-8cad-70789950343c.png)

**Comment by Matt726-S** [comment]
thats an older version, this may have been updated in the master branch of github

**Comment by BlackyTrains** [comment]
Oh, okay. Haven't though about that yet, worked fine till today.
But, how did you spot the old version? Is there such a big diffrence to the new one?

**Comment by mSparks43** [comment]
yeah, definitely not current (PFD and ND have had an overhaul).
Autopilot is in the final stages of a complete rewrite because of issues like this:
https://github.com/mSparks43/747-400/milestone/2
