### ISSUE TITLE
Corrupted / Empty Files in Download

### ISSUE THREAD

**Issue by BlackyTrains** [mSparks43/747-400#488]
Hello all,
I'm sorry for the second issue now... Anyways. i tried to download the plane today by clicking on the green "Code" -> Download ZIP   Button. I guess that's the right way. After downloading 712MB, i wanted to unzip the file. First with Windows-Explorer, which dind't work - Error: File is empty. 7zip was able to unpack it, but still gave me errors about wrong and corrupted files. After loading in X-Plane, the game crashes with an error, which i guess are these missing and corrupt files... So, what went wrong here?

[Error Message in Log.txt](https://github.com/mSparks43/747-400/files/6303445/Error.Message.in.Log.txt)

**Comment by oMrSmith** [comment]
Maybe it was still uploading...

**Comment by BlackyTrains** [comment]
No, that can't be the cause...

**Comment by mSparks43** [comment]
![image](https://user-images.githubusercontent.com/6773686/114598584-5af38880-9c92-11eb-80fd-1a4b3b7b43fb.png)
![image](https://user-images.githubusercontent.com/6773686/114598612-621a9680-9c92-11eb-88c4-bba2e0079b00.png)

The download didn't complete.

**Comment by BlackyTrains** [comment]
That's a reason, but it seems that i can't download more than that... Download just finished with the same message.
