### ISSUE TITLE
Automatic selection of pitch mode right after takeoff, varying engine thrust during TO/GA

### ISSUE THREAD

**Issue by lukas20102004** [mSparks43/747-400#491]
**Describe the bug**

First things first; When setting TO/GA, the engines struggle to stabilize and overshoot the target thrust. They eventually stabilize
and hold as expected. So no further issues there.

Another more major problem is however, that right after take-off, a pitch mode is automatically selected by the aircraft. (In this case FL CH). This leads to the following problem:

- Thrust is decreasing to climb power right after lift-off -> pitch down moment, loss of climb rate

# Please provide documentation references:

The problems explained above are shown in: 
https://youtu.be/sYxJu84JZj4

Finding real world evidence is extremly hard, as most 747 company SOP's suggest a take-off via VNAV armed.
Taking-off via VNAV armed is however not suggested in the current msparks 747 build, as ACC/THR RED height is not implemented at this stage. 

I have however found FCOM documentation that proves my point.

4.20.9 "At lift–off: pitch command target speed is V2 + 10. If current airspeed remains above target speed for 5 seconds, target airspeed is reset to current airspeed (limited to a maximum of V2 + 25)

"at 400 feet, VNAV activates when armed. Pitch commands the current airspeed. Autothrottle sets the selected reference thrust and annunciates THR REF" -> This means, that THR REF is only active, when VNAV engages after having armed it. Only when VNAV is armed, the aircraft chooses a pitch mode automatically at 400 feet. The FCOM does not say that FL CH is automatically selected after takeoff. 

In order for the aircraft to fly in autopilot, a pitch and a roll mode have to be engaged. If a pitch mode is not already engaged, the AFDS automatically engages FL CH as it's default pitch mode. Sadly, I am unable to find FCOM information about the autopilot behavior when no pitch mode is armed prior to take-off. While this might be unnesessary information, I have been at level-D simulators before, and know the pitch mode behavior of the autopilot. 

I hope that the information listed above helps with development of the aircraft. :)

### Bug reports:

Please replace this line with a detailed description of the issue

**Comment by oMrSmith** [comment]
I bet that the pitch mode TOGA should stay active until another pitchmode has been selected
or CMD is engaged - provided that VNAV has not been armed for take off.

**Comment by mSparks43** [comment]
Please retest, changes in
https://github.com/mSparks43/747-400/commit/b1e601a7de28f2c68024d92d9ee2a86d3c5aa541

Should have gone a long way to resolve this.

It's sufficient just to let me know if it still needs attention or not, the already given fcom reference is enough to revise it further.

**Comment by oMrSmith** [comment]
Takeoff without VNAV armed:
Now TOGA swtiches to ALT HOLD:
![747-400 - 2021-04-16 17 16 55](https://user-images.githubusercontent.com/78870770/115046451-bf535980-9ed7-11eb-8f27-ee55bfbd4dd8.png)

**Comment by mSparks43** [comment]
>Now TOGA swtiches to ALT HOLD:
Hmmm, that looks like a different issue.
You have 480' set in the FMC, and alt select is also on that page at 400', looks like MCP alt is set to 11,000' So it looks like its using FMC alts rather than MCP alt - however I couldn't get a recreate on this, I can't see any code path where it would set FMC ALT on takeoff without VNAV armed, and with VNAV armed/active it will automatically switch modes.

Did you have 400 feet dialed in the MCP on takeoff?

**Comment by oMrSmith** [comment]
I'll retry with the latest master and try to capture it on video.
(I set the MCP ALT to 11.000 initially before take off. Similar issue happened
when FLC was still engaging autoamtically.)

**Comment by oMrSmith** [comment]
Issue seems gone, also pitch mode TOGA does no longer get lost.

**Comment by lukas20102004** [comment]
> 
> 
> Issue seems gone, also pitch mode TOGA does no longer get lost.

I can confirm that. Tested it out as well.
