### ISSUE TITLE
DH can invincibly be decreased below -1

### ISSUE THREAD

**Issue by oMrSmith** [mSparks43/747-400#496]
**Negative effect:**
If you lower the DH to let's say -200 by accident,
it takes sometime to dial it back in later on
which seems as though it wouldn't work
since the value doesn't increase immediately above 0.

**Proposal for simple solution:**
Limit the DH downwards to the value of -1 
as the off position.

**Comment by mSparks43** [comment]
EHAM is below MSL, with low pressure (say 980mb Qfe) DH could easily be -200 feet there, the runway would be 900feet below MSL.

**Comment by oMrSmith** [comment]
I thought: The DH is based on the Radio Altimeter and not on the barometric pressure.
Therefore it cannot be below 0. Otherwise the plane would crash.

**Comment by oMrSmith** [comment]
Thank you for the lightning-fast fix.
