### ISSUE TITLE
stall warning sound stutters

### ISSUE THREAD

**Issue by Matt726-S** [mSparks43/747-400#497]
**Describe the bug**

A clear and concise description of what the bug/issue is.

# Please provide documentation references:

Place an x to check the boxes:
- [x] Something found during a flight test
- [ ] FCOM reference included (issues are likely to be closed without this)
- [ ] checked [current](https://github.com/mSparks43/747-400/blob/master/plugins/xtlua/scripts/B747.68.xt.fms/activepages/version.lua) FMC revision ident 
- [x] Video included (where applicable)
- [ ] Screenshot included (where applicable)

### Bug reports:

the stall warning sound seems to stutter for some reason, which doesn’t seem to be an fmod issue, as it is supposed to loop the stick shaker sound when stall dataref == 1, but why would it stutter?

a video from @mSparks43 shows how the stall warning is stuttering: https://youtu.be/PDJ3pH35h7c

**Comment by Matt726-S** [comment]
why is this closed

**Comment by crazytimtimtim** [comment]
> 
> 
> why is this closed

Because it was fixed with commit c31f1e7 .
