### ISSUE TITLE
Autothrottle Keeps Throttles at takeoff power for the entire flight

### ISSUE THREAD

**Issue by jakepq** [mSparks43/747-400#498]
**Describe the bug**

A clear and concise description of what the bug/issue is.

# Please provide documentation references:

Place an x to check the boxes:
- [x] Something found during a flight test
- [ ] FCOM reference included (issues are likely to be closed without this)
- [x] checked [current](https://github.com/mSparks43/747-400/blob/master/plugins/xtlua/scripts/B747.68.xt.fms/activepages/version.lua) FMC revision ident 
- [ ] Video included (where applicable)
- [x] Screenshot included (where applicable)

### Bug reports:
![image](https://user-images.githubusercontent.com/49926232/115997924-dd5a4180-a5dc-11eb-8c9d-e417c45eea73.png)

Even when the plane is overspeeding the autothrottle system will not reduce the power.

**Comment by oMrSmith** [comment]
The A/T does not control the speed of the aircraft as long as you fly
in a pitch for speed mode like VNAV SPD or FLC
