### ISSUE TITLE
stall shaker sound stuttering

### ISSUE THREAD

**Issue by Matt726-S** [mSparks43/747-400#502]
https://youtu.be/PDJ3pH35h7c you can see here the stall shaker keeps stuttering by turning off and on, but when the “test stall” command is triggered in dataref plugin, the stall warning sounds normal.

**Comment by mSparks43** [comment]
which fmc version? this should have been fixed in https://github.com/mSparks43/747-400/commit/c31f1e7bd7482c8ade4ae92ad227367b213cd82e
