### ISSUE TITLE
AP: A/T issues when descending with FLC

### ISSUE THREAD

**Issue by oMrSmith** [mSparks43/747-400#510]
When descending with FLC with the A/T engaged

- [ ] The thrust should retard and eventually switch from THR to **HOLD**.
The idea is to allow the pilot to _manually add_ thrust in order to reduce the descend rate.

FCOM 4.10.7

![116009153-3a271d80-a618-11eb-97c9-274ca26c816c](https://user-images.githubusercontent.com/78870770/116624080-94411f00-a947-11eb-9d13-19536ba26b58.png)

PMDG:

![FLC](https://user-images.githubusercontent.com/78870770/116624123-a91db280-a947-11eb-99d6-f2f3f2fd1661.JPG)

- [ ] Bug: The thrust mode THR REF generally can't hold still. 
It will periodically move the throttle slightly up and down although 
the corresponding pitch mode FLC or VNAV SPD
is responsible to control the speed via pitch. 
Can be observed well during descend with FLC: https://youtu.be/mWaekW-qlOQ

**Comment by mSparks43** [comment]
> * the corresponding pitch mode FLC or VNAV SPD
>   is responsible to control the speed via pitch.

not directly related, but the throttle will still move in THR REF as altitude changes, because the amount of throttle needed to produce the same thrust is dependant upon altitude and speed.

**Comment by oMrSmith** [comment]
I see! But is this kind of movement the one you mean?
https://youtu.be/mWaekW-qlOQ
