### ISSUE TITLE
Request: Shortcut command for "Gear Off"

### ISSUE THREAD

**Issue by oMrSmith** [mSparks43/747-400#511]
Would it perhaps be possible to 
create a shortcut command for "Gear Off" or to 
implement a behavior like in the Zibomod where pressing
"g" _cycles through_ the three positions: up-off-down?

**Comment by mSparks43** [comment]
Already implemented.
Both as a keyboard/joystick command
![image](https://user-images.githubusercontent.com/6773686/116670394-f75ea000-a99f-11eb-9e6f-f5f91378708d.png)

And also AutoATC voice commands
https://youtu.be/Fs1k371ua-c

**Comment by oMrSmith** [comment]
Oh cool! Thanks. I was typing "gear off" in the search field
and it would not show up.
