### ISSUE TITLE
AP: Issue with the TOGA pitch FD

### ISSUE THREAD

**Issue by oMrSmith** [mSparks43/747-400#512]
This is the last major issue of my original list #463 

The TOGA pitch FD is currently not showing pitch for the right speed.
As a result it does not raise high enough, causing the plane to accelerate too early
if you follow the FD during take off.

- [ ] The TOGA _pitch flight director_ should show pitch for MCP SPD + X,
(with X = 10, I suppose in the 747).

**This is the reason why the MCP Speed 
has to be set to V2 before take off**
and _**not**_ to V2+10. 
The AP will add 10 knots to whatever speed is set in the MCP.

This has lead to many confusion.
To compare with the 737: You will not find one single video of _flight deck to sim_
where he sets the MCP Speed to V2+15.
Because if he did, the TOGA FD would in fact show 
pitch for V2+15+15, which can easily be proven by test:

(You can set the MCP speed to 180 knots in the Zibomod, 
the TOGA FD will show pitch for 195 knots.)

In the following video a real pilot sets the MCP SPD to V2 in the 747 by PMDG:
https://youtu.be/9eRJP0ge_Uw?t=1504
(What can also be seen in the video is that arming VNAV will not set the MCP SPD to V2+10.)

PS: If it would cost too much effort to program this, I think it would be helpfull 
if the TOGA pitch FD would at least show the pitch for the speed
which has been set up in the MCP panel. (Currently it's not linked to the MCP speed at all.)

**Comment by mSparks43** [comment]
I'll use
https://www.youtube.com/watch?v=j-MuS0N_0n0&t=268s
as a reference, this will need pitch mode FD ripping out and replacing with one that matches actual boeing functionality.
Might not be soon because its dependant on computing PLI #455

**Comment by oMrSmith** [comment]
Yeah. I suppose that's fairly complex to program...
I think however there is one little inaccuracy in the video:
The reference is not V2 but the MCP speed which has to be set to V2.
The difference is: In the first case it does not matter at all which speed is set 
in the MCP panel, in the second it actually does.

**Comment by mSparks43** [comment]
> I think there is one little inaccuracy in the video:

The video I just linked is an FAA computer based training vid for the 744, sooo, if it disagrees with other sims, I go with that (and it wouldn't be the first time)

I might be able to mod the toga pitch setting to keep it below B747DR_airspeed_Vs, right now its set to 8 degrees and stays there until the AP is set by VNAV or the pilot to FLCH (at which point pitch targets MCP speed)

V2 is an FCC variable, if the PFD is showing no vspd I guess it just stays in the lower of 15' or below PLI

**Comment by oMrSmith** [comment]
Those trainings as well as the FCOM have one thing in comon. 
They are good in telling you what you should do
and very bad in telling you _why_ and _how_ the system works.
But that's just my humble opinion ;).

**Comment by mSparks43** [comment]
> which has been entered in the FMC, then why would it matter
> to set up the MCP to V2?

well, a lot here is to do with climb rate rather than speed, if you need more acceleration the trade off is a slower climbrate.

Docs FMA review doesn't mention the 15' degrees section
https://www.youtube.com/watch?v=sDa1ukA3CUo&t=480s

but adds that it also varies if you lose an engine.
you want the MCP speed to be more or less equal to what it comes out of TOGA pitch mode, else target pitch will change significantly when it does.

**Comment by oMrSmith** [comment]
Maybe we do not even disagree :D.
I'll make a video soon...

(If you jump in the 737 from Zibo
set the MCP SPD to 180knots
take off with TOGA without VNAV armed
and follow the FD the resulting SPD will
be 195 knots
even if V2 in the FMC is 150 knots!)

**Comment by oMrSmith** [comment]
The transition from the pitch-mode TOGA to the pitch-mode VNAV SPD
during take off with VNAV armed
feels very flued now!
