### ISSUE TITLE
FMC: Issue with the normal LEGs page

### ISSUE THREAD

**Issue by oMrSmith** [mSparks43/747-400#515]
"_**Once in the air, the X-Plane LEGS page can be reached by pressing RTE, and then L6 (marked RTE 2)**_"

This does not work for me. Doing that will open the RTE page:
https://youtu.be/Y6d2UA6fZ4g
Am I missing something?

**Proposal/Idea:** When clicking the LEGs Button on the FMC
while the LEGs page is already open,
it will switch to the normal LEGs page and vice versa.

**Comment by crazytimtimtim** [comment]
That's exactly what I did in #462! But mSparks rejected it.

**Comment by oMrSmith** [comment]
I'm afraid you'll fix issues before I even manage to finish my report. ;)
