### ISSUE TITLE
AP: Significant issue with the speed management of VNAV during descend

### ISSUE THREAD

**Issue by oMrSmith** [mSparks43/747-400#518]
- [x] Pitch mode **VNAV PTH** 
should reduce the descend rate to around 500 fpm
_before_ reaching 10.000 feet
in order to decelerate to the SPD REST of 250knots 
below 10.000 feet.

![Unbenannt](https://user-images.githubusercontent.com/78870770/116820187-ef575980-ab73-11eb-86b9-df896885004d.JPG)

![image](https://user-images.githubusercontent.com/78870770/116820203-0ac26480-ab74-11eb-8905-4c842fe7d55d.png)

**Possible work around for the next release:**

_Temporary Level-Off:_

**VANV PTH** could simply reduce the descend rate
down to **0** fpm at 10.000 ft 
_until_ the plane has decelerated down to 250 knots
and then continue with the descend...

**IMHO this would be absolutely fine for now!**

**Comment by oMrSmith** [comment]
I think it used to do that until a while ago...

**Comment by mSparks43** [comment]
> Actually: I think it used to do that until a while ago...

Kinda, what it actually did in the last release was fire an alt hold until it had decelerated, but that didn't port over nicely to the new autopilot stuff and I knew it wasn't by the fcom.

Thanks for the fcom reference, this is next on the list.

**Comment by oMrSmith** [comment]
Cool!

**Comment by oMrSmith** [comment]
Seems like you toke the king's way. Did a quick test and the deceleration to 250 knots out quite well!

**Comment by oMrSmith** [comment]
I noticed one issue with the descend below 10.000 ft:
Before the FAF it seemed like 
the restriction of the descendrate to around 500 to 600 fpm 
was triggering again. Looks like this on the upper pictur.
However: This had the negative side effect, that the target altitude wasn'n met...

**Comment by mSparks43** [comment]
> This had the negative side effect, that the target altitude wasn'n met...

There's a separate issue related to this fix, that it is bugging for the restricted speed late, this looked like it had the effect that the autothrottle actually prevents the deceleration and prolongs 500fpm phase, should be an easy fix but I didn't have time to flight test it for not breaking something else before pushing the fix.

**Comment by oMrSmith** [comment]
I see. I'll test your second fix again today. 
It seems like the SPD REST of 250/10000
is not programmed into VNAV DESC page 
of the FMC
by default,
which I noticed too late in my last test flight.

**Comment by oMrSmith** [comment]
Retest:
Deceleration to 250 knots was spot on.
Restriction of the descendrate to around 500 to 600 fpm was not triggering again.

SPD REST 
in VNAV DESC page
was set to 180/5000
by default and had to be updated.

**Comment by mSparks43** [comment]
> was set to 180/5000

Technically it should be empty
![image](https://user-images.githubusercontent.com/6773686/116897287-6143a780-ac35-11eb-9a48-654e2b58d9a5.png)
but since the xplane LEGS page [doesn't report speed information](https://developer.x-plane.com/sdk/XPLMGetFMSEntryInfo/) its set to 180/5000 by default to provide additional speed restriction target on approach.

**Comment by oMrSmith** [comment]
Hey @mSparks43,
just for my understanding:
VNAV is now perfectly decelerating to 250 knots before descending below 10.000 ft.
However: That happens even if the SPD RST of 250/10000 is not programmed into the FMC.
Is that intended to work this way?

**Comment by mSparks43** [comment]
SPD TRANS and SPD REST give two altitude blocks during descent
![image](https://user-images.githubusercontent.com/6773686/117079546-460f8f80-ad3c-11eb-9a5e-a76d07cab548.png)
So here, it will decelerate to 270kts at BEDAK, (expected, not required)
240kts by 10,000 feet, hold it below (forced)
and 180kts below 5,000 feet and hold it below (forced)
