### ISSUE TITLE
Lnav sometimes has issues staying on track 

### ISSUE THREAD

**Issue by Pancakeking78** [mSparks43/747-400#522]
Lnav sometimes has issues staying on track 

lnav will sometimes freak out and not stay on the proper tracK

i will record and upload a video tomorrow demonstrating the issue

**Comment by gHashFlyer** [comment]
video would help, but this issue really needs too be much more descriptive

**Comment by Pancakeking78** [comment]
i figured it out, its just the default fmc being the default fmc. for now I've uninstalled the aircraft. thanks
