### ISSUE TITLE
AP: Minor issue when switching from VNAV PTH to VS (during descend)

### ISSUE THREAD

**Issue by oMrSmith** [mSparks43/747-400#523]
When switching from VNAV PTH to VS during descend:

- [x] Bug: The first click on the VS button will not switch over to VS.
Instead it will disengage VNAV, leaving the pitch mode blank.
(Second click will engage VS.)

**Comment by oMrSmith** [comment]
Seems to be similar to #520.

**Comment by mSparks43** [comment]
> Seems to be similar to #520.

was pretty much identical

**Comment by mSparks43** [comment]
obviously starting a line with # doesnt put it in the commit message
https://github.com/mSparks43/747-400/commit/27120432c64bcafec7583214864747484b2449a5

**Comment by oMrSmith** [comment]
I did a lot of testing on 
switching back and forth 
between the different modes.
You really turned the AP around in the last weeks.
The buttons work really well now!
I think the only one left for now
is the LOC button...
