### ISSUE TITLE
MFD: Graphical Glitches

### ISSUE THREAD

**Issue by oMrSmith** [mSparks43/747-400#524]
![747-400 - 2021-05-04 14 16 00](https://user-images.githubusercontent.com/78870770/117002195-8a227600-ace3-11eb-9517-0dcb7be90639.png)
![747-400 - 2021-05-04 14 16 09](https://user-images.githubusercontent.com/78870770/117002198-8b53a300-ace3-11eb-9668-fb37390785f3.png)
![747-400 - 2021-05-04 14 16 11](https://user-images.githubusercontent.com/78870770/117002201-8bec3980-ace3-11eb-88d6-1a5e942db8ce.png)

**Comment by crazytimtimtim** [comment]
There's already an issue posted for this. That's because those arcs are provided by the TerrainRadar plugin, not the aircraft. I recommend just disabling them in the TerrainRadar plugin.

I'm waiting to see if @Matt726-S can make a custom texture.

**Comment by mSparks43** [comment]
yeah, this is a TR thing, hopefully we can get a new version soon

**Comment by oMrSmith** [comment]
Ah ok!
