### ISSUE TITLE
AP: Minor issue when disengaging CMD while descending with VNAV PTH.

### ISSUE THREAD

**Issue by oMrSmith** [mSparks43/747-400#525]
- [ ] Bug: When disconnecting the AP 
while descending with VNAV PTH,
the pitch mode VNAV PTH will switch to VS.

This is problematic when flying an RNAV approach
as VNAV PTH has to be manually reengaged
in order not to lose the correct guidance.

**Comment by mSparks43** [comment]
hmmm, this isn't a switch to, when the AP is disengaged the flight directors remain in the mode they were before the AP was disengaged, which for a low speed vnav descent will be SPD and VS.

**Comment by oMrSmith** [comment]
"when the AP is disengaged the flight directors remain in the mode they were before"
Yeah that's what I was thinking too. But when your pitch mode was VNAV PTH
it will either switch to ALT HLD or VS when disconnecting the AP...

**Comment by oMrSmith** [comment]
RL footage:
VNAV won't swith over to VS
when disconnectiing the AP:
https://youtu.be/9cINY2q2JfI?t=163

**Comment by oMrSmith** [comment]
Thanks! This works fluedly now.
