### ISSUE TITLE
AP: Issue with End of Descend

### ISSUE THREAD

**Issue by oMrSmith** [mSparks43/747-400#528]
- [x] Bug: The descend path ends
with the FAF, which is too soon. It should end
afterwards - shortly before the touch down zone of the RW.

![image](https://user-images.githubusercontent.com/78870770/117892126-6ef1d080-b2b8-11eb-9f5a-308012684a54.png)

**Problem**: Non-precision instrument approaches 
like an RNAV approach
can't be flown properly.

**Reason**: VNAV will give no guidance 
on the last LEG between
the RW and the last WP before the RW.

PS: I understand that the AP has to be disengaged at some point
before landing. However: I think that VNAV PTH should still provide guidance...

**Comment by oMrSmith** [comment]
@mSparks43 Man, you're the best! I'll check it out.

**Comment by mSparks43** [comment]
> 2\. When disconnecting CMD you have to reengage VNAV as it will switch
>     to VS, which I reported in #525

now i actually understand what you mean in 525, sorry i had had a pure brain fart moment before and for some bizarre reason was thinking vnav and cmd were the same thing. 

not sure what you mean by 1. before what?

**Comment by oMrSmith** [comment]
:D no problem. 

So in my last testflight VNAV PTH would not keep on descending
after the last fix before the RW
as I had set the MCP altitude to the missed approach altitude already.
I have to test that again...

**Comment by oMrSmith** [comment]
:D No problem!

Do you think, you could fix #525 ? This would be very helpful 
to properly test, how an RNAV approach works out...
including the last part when CMD get's disconnected
and the VNAV PTH FD is followed by hand-flying

**Comment by oMrSmith** [comment]
:D No problem!

Do you think, you could fix #525 ? This would be very helpful
in order to properly test, how an RNAV approach works out...
including the last part when CMD get's disconnected
and the VNAV PTH flight director is followed via hand-flying.

Currently the VNAV descend path seems to get distorted
by the interruption of VS that happens on CMD disconnect.

**Comment by oMrSmith** [comment]
I'll retest #528 via RNAV approach in a few minutes
and close this issue if every thing goes well.

**Comment by oMrSmith** [comment]
So on my last test flight the RNAV approach worked out for the first time! Great.
I'll close this. In case further issues should occur, I'll report...
