### ISSUE TITLE
MDA and DH should be BARO and RADIO

### ISSUE THREAD

**Issue by crazytimtimtim** [mSparks43/747-400#537]
"MDA" and "DH" should be "BARO" and "RADIO" respectively, both on the EFIS control panel and on the PFD.

**Comment by crazytimtimtim** [comment]
> Not sure if that conflicts with your issue...
> 
> I believe:
> 
> * MD-_Altitude_ always refers to the _barometric pressure_.
> * D-_Height_ always refers to the _radio altimeter_.

No conflicts? MDA is barometric pressure (BARO) and DH is radio altimeter (RADIO), just as you said.

**Comment by oMrSmith** [comment]
Ah, so you mean, how these should be labeled?
