### ISSUE TITLE
AP: Issue with SPD INTV during VNAV descend

### ISSUE THREAD

**Issue by oMrSmith** [mSparks43/747-400#544]
During VNAV descend:

- [ ] When opening the SPD window,
VNAV PTH should switch to VNAV SPD
unless flaps > 0.

![image](https://user-images.githubusercontent.com/78870770/117967090-f5dc9280-b324-11eb-949d-6f133602fa65.png)

**Comment by oMrSmith** [comment]
What's written in the manual looks to me
like it works the same way as in the 737.

**Comment by mSparks43** [comment]
think this is just an fma issue, displaying pth when its actually controlling the speed with the at, but i'll test the various modes

**Comment by oMrSmith** [comment]
This might be the case. I think there's a simple way to test this.
That is to open the SPD window and select a SPD which is _much slower_
than the current speed. Then if VNAV reduces the vertical speed to 0 (level off)
it is already _pitching for speed_....

**Comment by oMrSmith** [comment]
If I could choose: This issue could be moved to the third release.
#547 seems more important to me.

**Comment by mSparks43** [comment]
This isn't just an FMA mode issue, its an actual mode change in descent dependant on whether the mach window is open during descent. The changes aren't that bad, but its going to need a lot of flight testing to make sure weird stuff doesn't happen and it complicates descent quite considerably.
