### ISSUE TITLE
Key not active error

### ISSUE THREAD

**Issue by BadPlane** [mSparks43/747-400#545]
Hey, I was wondering that the key not active error means and how to solve it. It happens whenever I try to activate the Acars system and the satcom. How should I fix this?

**Comment by oMrSmith** [comment]
In many cases this means: The function is not yet implemented.

**Comment by crazytimtimtim** [comment]
Key Not Active means either the function hasn't been implemented, or you clicked a button next to an empty space. I don't work on the ACARS, but afaik you need AuoATC for it.

Nothing you can fix, just wait for us to implement the feature.
