### ISSUE TITLE
FMC input bugs/some overhead art/system bugs

### ISSUE THREAD

**Issue by JoshXPM** [mSparks43/747-400#55]
There's quite a few bugs in the FMC when inputting data. For example (not all of them, just ones I found and can put in here concisely), Approach page, if you select one of the vref options instead of manually inputting it, it gives 3 blank boxes. if you manually input it is fine; L4 also inop on approach page; I seem to remember takeoff page is similar story. 

On VNAV 1/3, R1 is inop; 2/3, R2 R3 and R5 (eng out) are inop, along with the other cruise options near bottom of screen (I know most likely they are WIP); 3/3, L1, R1 and R4 are inop (by inop I mean it says key not active or invalid input).

I don't remember all of them, but those are from the FMC.

Another one I found was the generator circuitry: if you had them on, all but #2 would show as off when on, also showed on lower DU so I think this is a code bug...

**Comment by mSparks43** [comment]
> There's quite a few bugs in the FMC when inputting data. For example (not all of them, just ones I found and can put in here concisely), Approach page, if you select one of the vref options instead of manually inputting it, it gives 3 blank boxes. if you manually input it is fine; L4 also inop on approach page; I seem to remember takeoff page is similar story.

This should be resolved, please retest, I'll repon if something here is missing

> On VNAV 1/3, R1 is inop; 2/3, R2 R3 and R5 (eng out) are inop, along with the other cruise options near bottom of screen (I know most likely they are WIP); 3/3, L1, R1 and R4 are inop (by inop I mean it says key not active or invalid input).
> 
> I don't remember all of them, but those are from the FMC.

really need a lot more detail/fcom references for this to be useful, please create specific issues for individual buttons that are inop with fcom references for their expected behaviour.
