### ISSUE TITLE
climb is VERY slow

### ISSUE THREAD

**Issue by Matt726-S** [mSparks43/747-400#550]
i was climbing to 32000 feet and it took very long. i was flying on vatism with v1rota7e and he was flying the pmdg, and made normal climb. me using the msparks, was climbing very slow for some reason, and i dont know why. i was following VNAV and LNAV path, according to the same route v1rota7e was using.

**Comment by mSparks43** [comment]
CLB Thrust limited?

**Comment by Matt726-S** [comment]
i dont  think so. i think i left everything alone and selected TO 2 for thrust derate and 64 for the temperature but that shouldn’t be affecting the climb

**Comment by Matt726-S** [comment]
i think the reason why this is happening is because along with derate TO 2, it also derated the climb to CLB 2. i selected CLB (first one) and the climb was much faster.
