### ISSUE TITLE
speedbrake and parking brake lever animations are too slow

### ISSUE THREAD

**Issue by Matt726-S** [mSparks43/747-400#556]
1: when you deploy reverse thrust and the speedbrake lever automatically goes up, it should be much quicker. observe here: https://youtu.be/13H6dj17TdA
ALSO: the animation on the speedbrake deploying should happen when you touchdown and the speedbrake lever was armed

2: the parking brake lever animation is too slow when you push the toe braking. it should be almost instantaneous when the parking brake is released.

**Comment by crazytimtimtim** [comment]
All the switch cover animations should be significantly faster too.
