### ISSUE TITLE
thrust decrease after rotate

### ISSUE THREAD

**Issue by Matt726-S** [mSparks43/747-400#557]
watch: https://youtu.be/sYxJu84JZj4

**Comment by crazytimtimtim** [comment]
I believe it's switching from takeoff thrust to climb thrust. But that's way too soon, it should reduce thrust later, once TO/GA deactivates.

**Comment by oMrSmith** [comment]
It should not engage climb thrust until reaching the thrust reduction altitude.
I believe though, it's simply not modeled yet.
You can't change the value in the FMC either.

**Comment by Marauder2882** [comment]
> It should not reduce to climb thrust until the thrust reduction altitude has been reached.
> I believe, the thrust reduction altitude has simply not been implemented yet
> as you can't change the value in the FMC either. Would be a great feature update...

As of the latest EEC module release (for GE engines only), CLB thrust engages at a static 1500 ft AGL.  This will be further enhanced in the near future to allow this value to be set in the FMC and utilized accordingly.

**Comment by oMrSmith** [comment]
Oh, that's great to hear. Thanks for letting me know. I'll check it out soon.

**Comment by mSparks43** [comment]
![image](https://user-images.githubusercontent.com/6773686/128645014-8e636a7e-e878-4f68-8b54-a1e6ecd8e8e3.png)

**Comment by oMrSmith** [comment]
I think this issue is fixed with the N1 engines, isn't it?
