### ISSUE TITLE
Flight control movement not impacted by aux hydraulic pressure

### ISSUE THREAD

**Issue by MCCVeen** [mSparks43/747-400#559]
The flight controls move as long as the aux demand pump is turned on without regard to pressure

https://user-images.githubusercontent.com/75425109/119751364-5201f380-be9b-11eb-8c17-da5959ae913c.mp4

**Comment by crazytimtimtim** [comment]
Wait, the 744 isn't fly-by-wire, is it? If not, shouldn't it still move without hydraulics? (just slower, or maybe with a delay because it's kinda difficult to simulate pressure on the stick in a sim)

**Comment by MCCVeen** [comment]
> Wait, the 744 isn't fly-by-wire, is it? If not, shouldn't it still move without hydraulics? (just slower, or maybe with a delay because it's kinda difficult to simulate pressure on the stick in a sim)

No cause you won't be able to move the yoke or rudder pedals without hydraulics

**Comment by MCCVeen** [comment]
> > Wait, the 744 isn't fly-by-wire, is it? If not, shouldn't it still move without hydraulics? (just slower, or maybe with a delay because it's kinda difficult to simulate pressure on the stick in a sim)
> 
> No cause you won't be able to move the yoke or rudder pedals without hydraulics as far as I know

Partly true, you are able to slightly move the yoke (15 degrees left and right, not too sure on the pitch, will have to look that up). I also noticed the yoke gets pushed forward as the hydraulic pressure lowers

**Comment by crazytimtimtim** [comment]
> noticed the yoke gets pushed forward as the hydraulic pressure lowers

Interesting, makes sense. The elevators will sag or lower slightly with less hydraulic pressure, which moves the yoke forward. Explains a recent video clip I saw (will link when I find it).

**Comment by MCCVeen** [comment]
> > noticed the yoke gets pushed forward as the hydraulic pressure lowers
> 
> Interesting, makes sense. The elevators will sag or lower slightly with less hydraulic pressure, which moves the yoke forward. Explains a recent video clip I saw (will link when I find it).

Oh yeah ofcourse

**Comment by MCCVeen** [comment]
But yeah you're able to slightly move the yoke but it doesn't move anything outside. Will have to look up the logic behind that

**Comment by mSparks43** [comment]
no attention to failures yet, all the failure items on the hyd page are still to do

**Comment by MCCVeen** [comment]
> no attention to failures yet, all the failure items on the hyd page are still to do

this isn't a failure tho this is normal operation

**Comment by mSparks43** [comment]
fixed in 2.2RC (flight model hook ups later)
