### ISSUE TITLE
Flight controls need engines to operate

### ISSUE THREAD

**Issue by MCCVeen** [mSparks43/747-400#560]
The flight controls need at least one engine running to operate regardless of if a demand pump is on. Irl this isn't the case

https://www.youtube.com/watch?v=e6i0CdvmMyk

**Comment by MCCVeen** [comment]
Closed for now, need to study this topic more

**Comment by Matt726-S** [comment]
please check the pmdg or find an fcom reference and then reopen

**Comment by MCCVeen** [comment]
> please check the pmdg or find an fcom reference and then reopen

Just checked the PMDG but there's much more to the hydraulic system than what you'd think, I'll have to take a look somewhere this week
