### ISSUE TITLE
X-Plane Crashes when loading up 747

### ISSUE THREAD

**Issue by DanielR1** [mSparks43/747-400#565]
Hi. I just downloaded the latest version of the 747, but my X-Plane crashes as soon as I load it up. I'm on the latest mac OSX running metal. X-Plane version is 11.53. I've tried redownloading the plane but the same thing happens
Here's my log.txt:
[Log.txt](https://github.com/mSparks43/747-400/files/6564295/Log.txt)
Thank you

**Comment by crazytimtimtim** [comment]
Hm, the log just _ends_ when trying to load the 744 plugins... No warnings or anything. Do you get a chance to take a screenshot of the console window that appears when starting the plane? Also, is this the master or Release v1?
