### ISSUE TITLE
Autothrottle Hold mode on Take-Off not working correctly

### ISSUE THREAD

**Issue by MCCVeen** [mSparks43/747-400#572]
So I was messing around with Reject Take Offs and when my A/T was in HOLD mode I rejected just before V1 and the throttle kept trying to set Take-Off Thrust

**Comment by MCCVeen** [comment]
Thrust Ref still active while autothrottle is turned off and the FMA doesn't display THR REF

https://user-images.githubusercontent.com/75425109/120087993-c97a9180-c0ec-11eb-84f6-01fddb6811e4.mp4

**Comment by crazytimtimtim** [comment]
Noticed another issue watching that video, I think I seemed to have accidentally made the WINDSHEAR and PULL UP PFD warnings only appear when the IRS isn't aligned 🤦‍♂️ will fix soon.

**Comment by mSparks43** [comment]
which version is this? cannot recreate it, and all AT functions should be suppressed without a PFD mode at least since https://github.com/mSparks43/747-400/commit/2db08878ebb4c16c64d9afcd6b3114881f7d01eb

**Comment by MCCVeen** [comment]
> which version is this? cannot recreate it, and all AT functions should be suppressed without a PFD mode at least since [2db0887](https://github.com/mSparks43/747-400/commit/2db08878ebb4c16c64d9afcd6b3114881f7d01eb)

latest version at the time
