### ISSUE TITLE
Improved flight Model?

### ISSUE THREAD

**Issue by crazytimtimtim** [mSparks43/747-400#581]
I'm not sure if this aircraft uses the default Laminar 744 flight model, but if it does, maybe we can use MGouge's with permission?

https://forums.x-plane.org/index.php?/files/file/59740-b747-400-update/

**Comment by MCCVeen** [comment]
> I'm not sure if this aircraft uses the default Laminar 744 flight model, but if it does, maybe we can use MGouge's with permission?
> 
> https://forums.x-plane.org/index.php?/files/file/59740-b747-400-update/

I believe the mod was originally based on MGouge's flight model

**Comment by BlueAce40** [comment]
I agree, I feel that at 100% N1 a 747 weighing 350 tons should be able to maintain 37,000 feet.
