### ISSUE TITLE
>CONFIG STAB doesn't disappear when stab trim is corrected

### ISSUE THREAD

**Issue by MCCVeen** [mSparks43/747-400#582]
When you set take off thrust and get a >CONFIG STAB warning because your stab trim outside of green band, and you correct your trim and set it somewhere in the green band the >CONFIG STAB warning should disappear while atm in the mod it doesn't. All the other T/O Config warnings work correctly tho

You can see the stab trim in the green band while the >CONFIG STAB warning is still displayed
![image](https://user-images.githubusercontent.com/75425109/120495543-185e4a80-c3bd-11eb-9ac9-979e2756ef99.png)

**Comment by mSparks43** [comment]
this will be because its not configured in the fmc.
R4 on the take off page i believe.

**Comment by MCCVeen** [comment]
> this will be because its not configured in the fmc.
> R4 on the take off page i believe.

The CONFIG STAB warning only goes off when the stab trim isn't somewhere in the green band, it doesn't look at the fmc stab trim setting

**Comment by mSparks43** [comment]
> > this will be because its not configured in the fmc.
> > R4 on the take off page i believe.
> 
> The CONFIG STAB warning only goes off when the stab trim isn't somewhere in the green band, it doesn't look at the fmc stab trim setting

![image](https://user-images.githubusercontent.com/6773686/121793671-ca89e380-cc01-11eb-90c8-e3e9a77356af.png)
