### ISSUE TITLE
PAX Signs in Auto should not trigger an Eicas Indication

### ISSUE THREAD

**Issue by MCCVeen** [mSparks43/747-400#583]
When the pax signs are set to auto, they should not trigger an Eicas indication. The Eicas indications SEATBELTS ON/NO SMOKING ON/PASS SIGNS ON will only be displayed when the respective switch is set to "ON".

![image](https://user-images.githubusercontent.com/75425109/120495865-5e1b1300-c3bd-11eb-81ea-efded97bf7e4.png)
![image](https://user-images.githubusercontent.com/75425109/120495897-64a98a80-c3bd-11eb-8ca7-11c7fba6079a.png)
![image](https://user-images.githubusercontent.com/75425109/120496166-a20e1800-c3bd-11eb-9169-1a82ee4a196a.png)

**Comment by crazytimtimtim** [comment]
Will fix.

**Comment by MCCVeen** [comment]
> Will fix.

Thanks! :)

**Comment by crazytimtimtim** [comment]
If you can remind me, is the switch OFF-AUTO-ON or OFF-ON-AUTO?

**Comment by crazytimtimtim** [comment]
I think it's OFF-AUTO-ON, that's what I used in my code above.

**Comment by MCCVeen** [comment]
> I think it's OFF-AUTO-ON, that's what I used in my code above.

Yeah it's OFF-AUTO-ON

**Comment by crazytimtimtim** [comment]
According to V1ROTA7E it still shows up, as long as you're below 10k feet with flaps out.
