### ISSUE TITLE
Minimum Maneuvering Speed (Vs) inhibited during take-off

### ISSUE THREAD

**Issue by MCCVeen** [mSparks43/747-400#584]
The Vs tape should be inhibited during take-off, and will be untill first flap retraction. You can see in a PSX 747 video here, that when he selects Flap 10 from Flaps 20, as soon as the lever is in position the Vs band displays and rises from Vso to its correct speed. This also makes sure it doesn't trigger an unnecessary AIRSPEED LOW Eicas indication when lifting off at VR speed when it's below Vs.

https://youtu.be/jv1YcfQlMYk?t=455

(V2 was 164 as set on the MCP, and you can see that V2 is in the yellow Vs band)
![image](https://user-images.githubusercontent.com/75425109/120499259-337e8980-c3c0-11eb-8746-f46a1320e082.png)

**Comment by mSparks43** [comment]
parameters connected to #557
