### ISSUE TITLE
Autothrottle disconnects during AIRPSPEED LOW

### ISSUE THREAD

**Issue by MCCVeen** [mSparks43/747-400#586]
The autothrottle disconnects whenever the AIRSPEED LOW message occurs, but the FCOM doesn't say anything about the autothrottle disconnecting when the airspeed is low or when overspeeding

**Comment by mSparks43** [comment]
Can't recreate
https://youtu.be/7Q0J9y6vG1Y

please use the template for submitting issues and ensure its on the latest version and things are properly referenced, if you can't find it in the fcom a video of the real one is generally required.
