### ISSUE TITLE
Autothrottle shouldn't need FDs to be engaged

### ISSUE THREAD

**Issue by MCCVeen** [mSparks43/747-400#591]
In the sim the Autothrottle need the FDs to be engaged. When you turn the FDs off, all the FMA data disappears so it looks like the Autothrottle is disengaged while it actually is still engaged. In real life the Autothrottle works completely independant from the Flight Directors. When the Autothrottle is engaged and Flight Directors are off, the FMA should still display whatever speed mode is active as also the FMA works independant from the FDs and just displays information about it. Linked with #573 which I now closed as this explanation is easier to understand and more complete.

**Comment by mSparks43** [comment]
hmm, can you find a reference for this, because its definately not "that" independant - turning the fds off and on is required for several at states.

**Comment by mSparks43** [comment]
e.g.
![image](https://user-images.githubusercontent.com/6773686/121289688-ac607280-c8e5-11eb-95a4-61747e2dce1f.png)
![image](https://user-images.githubusercontent.com/6773686/121289744-c0a46f80-c8e5-11eb-8497-82e491276237.png)
![image](https://user-images.githubusercontent.com/6773686/121289775-cb5f0480-c8e5-11eb-8222-8b3a497f31c8.png)

**Comment by MCCVeen** [comment]
> e.g.
> ![image](https://user-images.githubusercontent.com/6773686/121289688-ac607280-c8e5-11eb-95a4-61747e2dce1f.png)
> ![image](https://user-images.githubusercontent.com/6773686/121289744-c0a46f80-c8e5-11eb-8497-82e491276237.png)
> ![image](https://user-images.githubusercontent.com/6773686/121289775-cb5f0480-c8e5-11eb-8222-8b3a497f31c8.png)
> ![image](https://user-images.githubusercontent.com/6773686/121290182-766fbe00-c8e6-11eb-8e89-a519a0c44ef0.png)

I don't see what you're trying to explain here? Those pics don't say anything about the autothrottle being connected to the FDs

**Comment by MCCVeen** [comment]
> hmm, can you find a reference for this, because its definately not "that" independant - turning both the fds off and on is required for several at states.

Turning off FLight Directors is required at times to get rid of the magenta bars on the PFD as they can distract and confuse pilots for example on a visual raw data approach. This doesn't have anything to do with the autothrottle.

**Comment by mSparks43** [comment]
> > hmm, can you find a reference for this, because its definately not "that" independant - turning both the fds off and on is required for several at states.
> 
> Turning off Flight Directors is required at times to get rid of the magenta bars on the PFD as they can distract and confuse pilots for example on a visual raw data approach. This doesn't have anything to do with the autothrottle.

it clearly says you have to reengage the autothrottle after turning both the flight directors off without touching the at arm switch and that turning off both flight directors deactivates all modes.

so any change there will need a reference that something different happens

**Comment by MCCVeen** [comment]
> > > hmm, can you find a reference for this, because its definately not "that" independant - turning both the fds off and on is required for several at states.
> > 
> > 
> > Turning off Flight Directors is required at times to get rid of the magenta bars on the PFD as they can distract and confuse pilots for example on a visual raw data approach. This doesn't have anything to do with the autothrottle.
> 
> it clearly says you have to reengage the autothrottle after turning both the flight directors off without touching the at arm switch and that turning off both flight directors deactivates all modes.
> 
> so any change there will need a reference that something different happens

where does it say that?

**Comment by MCCVeen** [comment]
Here you can see the PMDG. The Flight Directors are off, the autothrottle is working and the autopilot is engaged. On the FMA you can still see the active modes for the Autopilot and the Autothrottle. This is correct behavior confirmed by the FCOM

![image](https://user-images.githubusercontent.com/75425109/121388444-ca60be00-c94b-11eb-9bac-9dbffc0cfa05.png)

**Comment by mSparks43** [comment]
> where does it say that?

![image](https://user-images.githubusercontent.com/6773686/121464261-da13ed00-c9b3-11eb-9932-8cc28c17e3c5.png)

"all modes"

![image](https://user-images.githubusercontent.com/6773686/121464362-0891c800-c9b4-11eb-9e3b-0469e7b8c400.png)

disengaging the AP does not disconnect the AT, or change the flight mode
turning both flight directors off deactives all modes (ergo, you found a bug in PMDG, because those ADFS modes should not be on the PFD, because turning both flight directors off deactives all modes)
When the flight directors are switched back on you have to re-engage the AT, therefore it turned off when you turned both FDs off

**Comment by mSparks43** [comment]
Now, that isn't to say that just the bars go off when turning both flight directors off with the autopilot _engaged_, but again - really need a reference of some kind.

**Comment by MCCVeen** [comment]
> Now,it could be that only the bars go off when turning both flight directors off with the autopilot _engaged_, but again - really need a reference of some kind.

bars go off when FDs go off

> > where does it say that?
> 
> ![image](https://user-images.githubusercontent.com/6773686/121464261-da13ed00-c9b3-11eb-9932-8cc28c17e3c5.png)
> 
> "all modes"
> 
> ![image](https://user-images.githubusercontent.com/6773686/121464362-0891c800-c9b4-11eb-9e3b-0469e7b8c400.png)
> 
> disengaging the AP does not disconnect the AT, or change the flight mode
> turning both flight directors off deactives all modes (ergo, you found a bug in PMDG, because those ADFS modes should not be on the PFD, because turning both flight directors off deactives all modes)
> When the flight directors are switched back on you have to re-engage the AT, therefore it turned off when you turned both FDs off

By all modes, they mean all autopilot modes on the FMA and MCP like LNAV, VNAV, HDG, HDG HOLD, VS, ALT etc. THe autothrottle is not connected to that. 

Again, second pic is a procedure, not a system description, that tells the pilots to turn the FDs off and on to get into ATT and VS mode, nothing to do with the autothrottle or autopilot.

No, the PMDG is not bugged. I get what you mean but that's not the way it works. AFDS modes on the FMA are still displayed because the autopilot is engaged with those modes active, and the FMA shows that info. The FMA purely supplies info on what modes are active for both the Flight Directors and the autopilot.

Again, all modes doesn't mean what you think it does, and doesn't have anything to do with the autothrottle either.

I ask you to please take another look at this:

![image](https://user-images.githubusercontent.com/75425109/121467758-f87ce700-c9b9-11eb-9ce2-b5ccd4cdcb95.png)

**Comment by amarjotdeol** [comment]
Yeah the flight directors isnt connected to the autothrottle in any plane and shouldnt be affected by it

**Comment by mSparks43** [comment]
conclusion after much discussion

![image](https://user-images.githubusercontent.com/6773686/121464362-0891c800-c9b4-11eb-9e3b-0469e7b8c400.png)

Is wrong/worded badly. "disengage autopilot" in Boeing speak means "disengage autopilot **and autothrottle**", Boeing doesn't recommend flying with just AT.

**Comment by amarjotdeol** [comment]
Boeing doesnt recomend flying with just AT but you should be able to have the autothrottle on even with FD off, there are several video on youtube showing this and it makes no sense

**Comment by amarjotdeol** [comment]
The only job for the FD is to show a magenta flight director on your PFD guiding the pilot in HDG, LNAV, VNAV or APP etc..

**Comment by mSparks43** [comment]
> Boeing doesnt recomend flying with just AT but you should be able to have the autothrottle on even with FD off, there are several video on youtube showing this.

it currently resets all modes as per
![image](https://user-images.githubusercontent.com/6773686/121464261-da13ed00-c9b3-11eb-9932-8cc28c17e3c5.png)

All systems are being based on the fcom and cbt training videos, NOT pmdg. the fcom was wrong. it'll be fixed. Its also all open source so if you want to fix it before I get round to it feel free.

**Comment by MCCVeen** [comment]
> > Boeing doesnt recomend flying with just AT but you should be able to have the autothrottle on even with FD off, there are several video on youtube showing this.
> 
> it currently resets all modes as per
> ![image](https://user-images.githubusercontent.com/6773686/121464261-da13ed00-c9b3-11eb-9932-8cc28c17e3c5.png)
> 
> All systems are being based on the fcom and cbt training videos, NOT pmdg. the fcom was wrong. it'll be fixed. Its also all open source so if you want to fix it before I get round to it feel free.

I told you this many times before with fcom reference, all modes doesn't include autothrottle

**Comment by mSparks43** [comment]
> > > Boeing doesnt recomend flying with just AT but you should be able to have the autothrottle on even with FD off, there are several video on youtube showing this.
> > 
> > 
> > it currently resets all modes as per
> > ![image](https://user-images.githubusercontent.com/6773686/121464261-da13ed00-c9b3-11eb-9932-8cc28c17e3c5.png)
> > All systems are being based on the fcom and cbt training videos, NOT pmdg. the fcom was wrong. it'll be fixed. Its also all open source so if you want to fix it before I get round to it feel free.
> 
> I told you this many times before with fcom reference, all modes doesn't include autothrottle but only roll and pitch fma modes like VNAV PTH, VNAV SPD, LNAV, HDG, HDG HOLD, LOC, GS etc etc etc

the ils sidestep procedure in the fcom is wrong

**Comment by MCCVeen** [comment]
> > > > Boeing doesnt recomend flying with just AT but you should be able to have the autothrottle on even with FD off, there are several video on youtube showing this.
> > > 
> > > 
> > > it currently resets all modes as per
> > > ![image](https://user-images.githubusercontent.com/6773686/121464261-da13ed00-c9b3-11eb-9932-8cc28c17e3c5.png)
> > > All systems are being based on the fcom and cbt training videos, NOT pmdg. the fcom was wrong. it'll be fixed. Its also all open source so if you want to fix it before I get round to it feel free.
> > 
> > 
> > I told you this many times before with fcom reference, all modes doesn't include autothrottle but only roll and pitch fma modes like VNAV PTH, VNAV SPD, LNAV, HDG, HDG HOLD, LOC, GS etc etc etc
> 
> the ils sidestep procedure in the fcom is wrong as per 8 days ago.

What? This has nothing to do with the ils sidestep procedure? This is about you talking about "All modes"

**Comment by mSparks43** [comment]
> What? This has nothing to do with the ils sidestep procedure. This is about you talking about "All modes"

It does, because in the ils sidestep as it is written in the fcom the autothrottle is disconnected when the fd's are turned off. - which is wrong.

**Comment by MCCVeen** [comment]
> > What? This has nothing to do with the ils sidestep procedure. This is about you talking about "All modes"
> 
> It does, because in the ils sidestep as it is written in the fcom the autothrottle is disconnected when the fd's are turned off. - which is wrong.

that's not what I was talking about, you said "it currently resets all modes per *picture with fcom saying all modes deactive with fd and ap off*" so I said that with all modes the fcom meand lnav, vnav, hdg, hdg hold, alt, vs, loc, gs etc and not the autothrottle

**Comment by mSparks43** [comment]
> that's not what I was talking about, you said "it currently resets all modes per _picture with fcom saying all modes deactive with fd and ap off_" so I said that with all modes the fcom means lnav, vnav, hdg, hdg hold, alt, vs, loc, gs etc and not the autothrottle

yes. currently it resets all modes and as per the ils sidestep procedure you have to re engage both the autopilot and autothrottle after turning the fds off then on.

when this issue gets fixed it will not be possible to follow the ils sidestep procedure as it is written, but thats ok because the sidestep procedure as it is written is wrong.

the post I was replying to said doing it this way "made no sense".

**Comment by amarjotdeol** [comment]
![ab86359ca06630c1c0a4d521e6e64600](https://user-images.githubusercontent.com/21007258/122634842-f238ea00-d0e0-11eb-973a-954864c2dcc0.png)

**Comment by mSparks43** [comment]
for future reference, that still wouldnt have been enough to deternine the official 747-400 documentation is wrong.

**Comment by mSparks43** [comment]
The original issue is now fixed, everything we talked about after isn't. but since so much AT related stuff just changed its better to make them as new issues, collect them under an "AutoThrottle" milestone and deal with them for the 3rd release.
