### ISSUE TITLE
>SPEEDBRAKE EXT on ground back again

### ISSUE THREAD

**Issue by MCCVeen** [mSparks43/747-400#592]
>SPEEDBRAKE EXT is only displayed in flight. Once the plane is on the ground, the message becomes unnecessary and therefor it will not be displayed
![image](https://user-images.githubusercontent.com/75425109/121390208-70f98e80-c94d-11eb-93c5-6625afd43eee.png)

**Comment by mSparks43** [comment]
Aft of ARMED detent, Flaps in landing, throttles forward of closed = SPEEDBRAKES EXT
![image](https://user-images.githubusercontent.com/6773686/121817445-d0270e00-cc81-11eb-8b8f-cfc994c3b8d1.png)

**Comment by MCCVeen** [comment]
> Aft of ARMED detent, Flaps in landing, throttles forward of closed = SPEEDBRAKES EXT
> ![image](https://user-images.githubusercontent.com/6773686/121817445-d0270e00-cc81-11eb-8b8f-cfc994c3b8d1.png)

Flight condition

![image](https://user-images.githubusercontent.com/75425109/121822508-b5fc2880-cc9f-11eb-93a8-c39ab235705d.png)
