### ISSUE TITLE
HOLD mode doesn't get activated when turning on FLCH

### ISSUE THREAD

**Issue by MCCVeen** [mSparks43/747-400#593]
When you turn on FLCH and the MCP altitude selected is below current altitude, the Speed mode should go to IDLE, bring the thrust back and once it's in idle it'll go into HOLD mode. Currently it goes into THR REF mode on the FMA when the autothrottle is engaged, which is wrong, PLUS it doesn't even work as the thrust levers don't go to the thrust reference but instead stays in position and is still movable for the pilots as if the Speed mode is in HOLD. When the autothrottle is not engaged and you push FLCH it doesn't trigger the autothrottle.

Turning on FLCH in a descent with the autothrottle ARM switch turned on should *always* idle the thrust and then go into hold mode

![image](https://user-images.githubusercontent.com/75425109/121399997-52989080-c957-11eb-99ce-045a53d7d886.png)
![image](https://user-images.githubusercontent.com/75425109/121400119-7c51b780-c957-11eb-9ea3-a768a659218e.png)

**Comment by oMrSmith** [comment]
I think this is already on the list for release 3:
#510

**Comment by MCCVeen** [comment]
> I have already reported this issue #510 and it has been added to the third release.

Oh whoops, thanks for letting me know!
