### ISSUE TITLE
VNAV shouldn't change speed when not active

### ISSUE THREAD

**Issue by MCCVeen** [mSparks43/747-400#594]
When I arm VNAV before Take-Off, and TO/GA is active on the Flight Directors, the VNAV shouldn't change the speed which it currently does in the speed window as it's not active

**Comment by mSparks43** [comment]
you would never normally see this because it should already be set to V2+10 before you press the button.

**Comment by mSparks43** [comment]
![image](https://user-images.githubusercontent.com/6773686/121760621-08b4d380-cb2c-11eb-8d7d-1cd603ec6429.png)
