### ISSUE TITLE
weird elevator flight control indicator bug on EICAS

### ISSUE THREAD

**Issue by Matt726-S** [mSparks43/747-400#596]
**Describe the bug**

A clear and concise description of what the bug/issue is.

# Please provide documentation references:

Place an x to check the boxes:
- [x] Something found during a flight test
- [ ] FCOM reference included (issues are likely to be closed without this)
- [ ] checked [current](https://github.com/mSparks43/747-400/blob/master/plugins/xtlua/scripts/B747.68.xt.fms/activepages/version.lua) FMC revision ident 
- [x] Video included (where applicable)
- [ ] Screenshot included (where applicable)

### Bug reports:

Please replace this line with a detailed description of the issue
when i pitch up with the elevator by pulling full on my yoke, the flight control display just goes above its range

https://drive.google.com/file/d/1eS5VApT4s2mQqKRZOIm4lqchJ2mZ3VDB/view?usp=sharing

**Comment by mSparks43** [comment]
going to close this if there is no recreate

**Comment by Matt726-S** [comment]
the only way to recrate is to pitch up the yoke, i dont know why youre not having the issue
