### ISSUE TITLE
NAV DATA OUT OF DATE

### ISSUE THREAD

**Issue by crazytimtimtim** [mSparks43/747-400#613]
# Feaure Request

### Describe the feature
I don't think we have a NAV DATA OUT OF DATE message on the FMC, please correct me if I'm wrong. I _might_ be able to implement it myself.

**Comment by mSparks43** [comment]
it gets cleared on startup
https://github.com/mSparks43/747-400/blob/c4b6b7c6e2e8a67a84f2f0b9f185d3e0adfaa81e/plugins/xtlua/scripts/B747.68.xt.fms/B744.createfms.lua#L507

**Comment by crazytimtimtim** [comment]
> it gets cleared on startup

Why?

**Comment by mSparks43** [comment]
because i have no interest in selling navdata subscriptions, its a pain in the ____ to clear every flight, and technically its never out of date because it always matches the xp default scenery.
plus updating it seems to cause nothing but problems.

**Comment by MCCVeen** [comment]
> because i have no interest in selling navdata subscriptions, its a pain in the ____ to clear every flight, and technically its never out of date because it always matches the xp default scenery.
> plus updating it seems to cause nothing but problems.

It's just a simple message tho that increases the realism of the plane. It has less to do with forcing people to buy navdata, or updating it (which is really simple if done correctly), but more so a reminder to those who have a navigraph subscription or something and fly online. Can I please ask you to put it back? As it can prevent people from using outdated airacs when flying online, which could lead to trouble and people getting banned (trust me I've been there myself lol) + realism :P

**Comment by mSparks43** [comment]
> It's just a simple message tho that increases the realism of the plane.

However, it also increases the time for testing on the ground and makes flight tests starting on approach significantly more of a pain.

If you want it you can just comment out the line linked above. (add -- to the start of line 507 of createfms)

**Comment by MCCVeen** [comment]
> > It's just a simple message tho that increases the realism of the plane.
> 
> However, it also increases the time for testing on the ground and makes flight tests starting on approach significantly more of a pain.
> 
> If you want it you can just comment out the line linked above. (add -- to the start of line 507 of createfms)

What do you mean it makes flight tests significantly more of a pain? You can just clear the message, easy as that

**Comment by MCCVeen** [comment]
> > It's just a simple message tho that increases the realism of the plane.
> 
> However, it also increases the time for testing on the ground and makes flight tests starting on approach significantly more of a pain.
> 
> If you want it you can just comment out the line linked above. (add -- to the start of line 507 of createfms)

will look that up, but it would be way easier if it's just in the plane by default instead of having to mod it with every single new commit

**Comment by crazytimtimtim** [comment]
> will look that up, but it would be way easier if it's just in the plane by default instead of having to mod it with every single new commit

Agreed. And more realistic for the majority of users who aren't testing the plane.

At least comment it out for the release please, along with removing debugging.txt

**Comment by mSparks43** [comment]
> And more realistic for the majority of users who aren't testing the plane.

Except its not, because updating the data more often than not _completely_ breaks an already fairly broken XP LNAV.

**Comment by crazytimtimtim** [comment]
But won't people likely update navdata anyway? Will you enable it if we write our own LNAV?

**Comment by mSparks43** [comment]
> But won't people likely update navdata anyway?

Yep, and I'm reasonably sure a lot of the issues popping up recently are related to them doing so.

>Will you enable it if we write our own LNAV?

_when_ we write our own LNAV... however, from looking through the default navdata, the issues stem from lots of really bad data in there and not cleaning it properly, custom LNAV just on default data is going to take a very very long time to get out of beta.

**Comment by crazytimtimtim** [comment]
> always matches the xp default scenery.

Also I don’t understand this statement... Default airports are continually updated.

**Comment by mSparks43** [comment]
> > always matches the xp default scenery.
> 
> Also I don’t understand this statement... Default airports are continually updated.

But updated navdata can add new waypoints, which if it doesn't match the scenery will cause a CTD with "waypoint not found" when you get to it.

**Comment by crazytimtimtim** [comment]
By scenery you mean as in airports?

Xplane airports don’t care about navdata, that’s why sometimes there are misaligned ILSs and misnamed runways, even with default data (airports are updated, navdata is not).

**Comment by mSparks43** [comment]
I mean the global apt.dat that has the airport data in, if that doesnt match the navdata XP ctds

**Comment by crazytimtimtim** [comment]
I am 99 percent sure it updates the apt.dat when updating navdata.

**Comment by mSparks43** [comment]
> I am 99 percent sure it updates the apt.dat when updating navdata.

it is just new nav .dat files that gon in custom data, and it only breaks on planes that use default lnav (i.e. not zibo)
