### ISSUE TITLE
Trim Setting Issue

### ISSUE THREAD

**Issue by oMrSmith** [mSparks43/747-400#615]
Could it be that
number of 
initial trim setting
proposed by the FMC
is always a bit too low?

I always have to trim up the plane
after take off...

**Comment by MCCVeen** [comment]
> Could it be that
> number of
> initial trim setting
> proposed by the FMC
> is always a bit too low?
> 
> I always have to trim up the plane
> after take off...

it's probably that the stab trim calculations are correct, the flight model is just completely messed up atm

**Comment by mSparks43** [comment]
> after take off...

Stab trim is only for stopping a tail strike during take off aiui, it doesn't tell you anything about the trim you will need once airborne.

**Comment by oMrSmith** [comment]
alright, I'll close this then.

**Comment by crazytimtimtim** [comment]
> flight model is just completely messed up atm

There were a couple people working on a completely new flight model with custom airfoils (@Phillip Strydom and @Zeta), but not sure where Phillip went... Hopefully he can finish up his flight model, it’s incomplete afaik.
