### ISSUE TITLE
Aircraft pitches up violently and then starts to rapidly descend

### ISSUE THREAD

**Issue by BadPlane** [mSparks43/747-400#618]
Hey, this happeded on a overseas flight when I wasn't home. I watched the replay and it seems the aircraft pitched up to correct a sudden loss of pitch, climbed 2000 feet, then put inself in a nosedive all the way down to the ocean below. 

Video link: https://youtu.be/CmovPfYfua0
[Log.txt](https://github.com/mSparks43/747-400/files/6720665/Log.txt)

**Comment by mSparks43** [comment]
The fall is post stall, around 1 second in.
No clue why it went into a stall, real weather updates? flying over a storm? air pocket?

**Comment by BadPlane** [comment]
I had Anti ice on, and I didn't think I was in a storm

**Comment by mSparks43** [comment]
> and I didn't think I was in a storm

https://www.youtube.com/watch?v=EuLURmITq_E
https://www.youtube.com/watch?v=r5LUGaW6TyE
