### ISSUE TITLE
Always a balloon effect on approach

### ISSUE THREAD

**Issue by MCCVeen** [mSparks43/747-400#619]
Place an x to check the boxes:
- [x] Something found during a flight test
- [ ] FCOM reference included (issues are likely to be closed without this)
- [x] checked [current](https://github.com/mSparks43/747-400/blob/master/plugins/xtlua/scripts/B747.68.xt.fms/activepages/version.lua) FMC revision ident 
- [ ] Video included (where applicable)
- [ ] Screenshot included (where applicable)

Everytime I approach a runway in the latest version somewhere between 200 and 500 feet I get an instant balloon effect where the vertical speed will rise with +500 fpm and the speed will increase. This only lasts a few seconds and then the airplane suddenly drops down with negative 1000 fpm and the speed decreases again, like a microburst. It's been like this ever since I updated the plane to the latest version on every single approach. Note that I did remove the FMS NAV DATA OUT OF DATE code line.

**Comment by mSparks43** [comment]
are you getting time warn overflows on approach?

**Comment by MCCVeen** [comment]
> are you getting time warn overflows on approach?

what do you mean with time warn overflows?

**Comment by mSparks43** [comment]
> > are you getting time warn overflows on approach?
> 
> what do you mean with time warn overflows?

In the console window, it will say "WARN: XTLua time overflow = some milliseconds" when the systems are running slowly, this sort of thing would cause delayed reaction to lining the aircraft up with the touchdown spot in the last few hundred feet.

If you are talking about hand flying into final, then... well not sure what to say other than changing wind and thermals as you come into land are a real thing.

**Comment by MCCVeen** [comment]
> > > are you getting time warn overflows on approach?
> > 
> > 
> > what do you mean with time warn overflows?
> 
> In the console window, it will say "WARN: XTLua time overflow = some milliseconds" when the systems are running slowly, this sort of thing would cause delayed reaction to lining the aircraft up with the touchdown spot in the last few hundred feet.
> 
> If you are talking about hand flying into final, then... well not sure what to say other than changing wind and thermals as you come into land are a real thing.

Doesn't matter if I fly manually or do an autoland, it always happens. I set the X-Plane weather conditions to clear every time and it still happens. It's obvious that this is an issue with the mod

**Comment by mSparks43** [comment]
> Doesn't matter if I fly manually or do an autoland, it always happens.

What timestamp are you referring to?
https://www.youtube.com/watch?v=2xqKE9-tP5o
