### ISSUE TITLE
Entering the REF AIRPORT does not work.

### ISSUE THREAD

**Issue by crazytimtimtim** [mSparks43/747-400#620]
**Describe the bug**

A clear and concise description of what the bug/issue is.

# Please provide documentation references:

Place an x to check the boxes:
- [x] Something found during a flight test
- [ ] FCOM reference included (issues are likely to be closed without this)
- [x] checked [current](https://github.com/mSparks43/747-400/blob/master/plugins/xtlua/scripts/B747.68.xt.fms/activepages/version.lua) FMC revision ident 
- [ ] Video included (where applicable)
- [x] Screenshot included (where applicable)

### Bug reports:

Entering the REF AIRPORT on the POS INIT page does nothing, the entry continues to read “- - - -“, and no coords appear. It has worked for others, so I guess this is one of those difficult-to-replicate issues.

Will post a screenshot when I get the chance.

**Comment by mSparks43** [comment]
need to start with engines off.

**Comment by crazytimtimtim** [comment]
Still did not work. Please reopen.
