### ISSUE TITLE
fuel cut-off levers inop

### ISSUE THREAD

**Issue by edwar64896** [mSparks43/747-400#624]
trying to start from cold and dark. Managed to get bleed air into the engines, but for some reason - can't flick the fuel control levers on :-( anything I am missing? working from cloned repository.

**Comment by crazytimtimtim** [comment]
Please attach a video or screenshots just as the issue template asks.

Is the rest of your cockpit working?

**Comment by mSparks43** [comment]
this should have been fixed in https://github.com/mSparks43/747-400/commit/b23e04a9a63e02aba1f6bf1e2e5aa6f5e3cfbc71
