### ISSUE TITLE
DH can be invincibly increased above 1000

### ISSUE THREAD

**Issue by oMrSmith** [mSparks43/747-400#625]
Negative side-effect:

If you accidantely increase the DH above 1000
the number disappears and
dialing it back seems unfunctional
as it takes so long to decrease the value back down below 1000.

Proposal for simple solution:
Limit the internal variable for the DH upwards to the value of 1000.

**Comment by oMrSmith** [comment]
This issue had alredy been fixed the other way round in #496 496

**Comment by crazytimtimtim** [comment]
I should be able to fix this.

**Comment by crazytimtimtim** [comment]
Fixed it and reinstalled xplane, lost my changes :/ I'll redo it though, it's not too much.

**Comment by oMrSmith** [comment]
Oh! Ok. Thank you. Looking forward to upcoming changes. Hopefully sparky finds
some spare time to continue his work on the next release. Felt like it had already been so close.
