### ISSUE TITLE
No Ext power

### ISSUE THREAD

**Issue by Dreamliner887** [mSparks43/747-400#633]
Hi there, i have installed the msparks, but i can not select ext power because it is off, so i must choose the apu gen.
Do i something wrong? The plane is in the aircraft folder of X-plane 11

**Comment by mSparks43** [comment]
connect ground power from FMC ground handling

**Comment by Dreamliner887** [comment]
Thanks

**Comment by crazytimtimtim** [comment]
So no bug here?
