### ISSUE TITLE
ND uses tiny font

### ISSUE THREAD

**Issue by Juppie902** [mSparks43/747-400#70]
![747-400 - 2020-11-04 16 53 39](https://user-images.githubusercontent.com/73952335/98128267-5f846b80-1ec0-11eb-92f1-a9abe839fe09.png)
Very tiny font on the ND of both Captain and F/O, need to zoom all the way in.

Also, the waypoints have a box maximum range displayed on the ND: 
![747-400 - 2020-11-04 16 58 17](https://user-images.githubusercontent.com/73952335/98128388-8cd11980-1ec0-11eb-9040-a7d255158e5c.png)

**Comment by airfightergr** [comment]
Since it is X-Plane's default map, you can do anything to change it. The solutions are either develop a custom ND from scratch, or wait for Laminar to do something better in the future.
