### ISSUE TITLE
Avitab integreation

### ISSUE THREAD

**Issue by samiFBG** [mSparks43/747-400#704]
# Feaure Request

### Describe the feature
Hello do you can add avitab with tablet .
I think this is very good feature .
Thanks
Sami

### Visual Reference
If applicable, add screenshots or videos to help explain your request. Please upload or send a link below:

**Comment by crazytimtimtim** [comment]
It'll be a while before we do this. It will be a ton of work because there is no space left on the display texture. This may come in the distant future, but not anytime soon.
