### ISSUE TITLE
Sound loops, floating lights, and clickspots

### ISSUE THREAD

**Issue by srykho22** [mSparks43/747-400#708]
**Describe the bug**

1. When connecting the aircraft to external ground power, there is a sound loop
2. When reloading the aircraft for any reason, the clickspots do not work and require an X-Plane restart
3. In the LCF model, there is a floating light 

# Please provide documentation references:

Place an x to check the boxes:
- [x] Something found during a flight test
- [ ] FCOM reference included (issues are likely to be closed without this)
- [ ] checked [current](https://github.com/mSparks43/747-400/blob/master/plugins/xtlua/scripts/B747.68.xt.fms/activepages/version.lua) FMC revision ident 
- [x] Video included (where applicable)
- [x] Screenshot included (where applicable)
![X-Plane_o2sW8wY0Cl](https://user-images.githubusercontent.com/31467287/136962364-0d236f60-42d5-4fee-bbb6-e64ae4c6a5dc.png)

![X-Plane_PgTIrho6eb](https://user-images.githubusercontent.com/31467287/136962379-ac5a097f-8144-4bab-8e6f-ada0e2e630b3.png)

https://user-images.githubusercontent.com/31467287/136966827-7520a297-abbc-4740-81af-ef0970d330cf.mp4

https://user-images.githubusercontent.com/31467287/136966888-0f98b950-213c-4746-b63a-53b84123a7af.mp4

**Comment by crazytimtimtim** [comment]
1. @Matt726-S
2. Never seen this before...
3. Yeah. the LCF model is pretty broken and outdated. Nobody really works on it, and it may actually be deleted.

**Comment by srykho22** [comment]
The two videos were actually recorded on the regular model, so my version of the base (not LCF) model suffers from both issues 1 and 2

**Comment by mSparks43** [comment]
1 is probably SAM plugin, it tries to override the ground power.
2. never seen this
3. will fix today
