### ISSUE TITLE
VNAV PTH should not constantly work like VNAV SPD

### ISSUE THREAD

**Issue by oMrSmith** [mSparks43/747-400#718]
During descend 
**VNAV PTH** will pitch for speed
whenever the current IAS exceeds the target speed (magenta speed bug).

Infact VNAV PTH works like VNAV SPD which it shouldn't.
VNAV PTH ≠ VNAV SPD

The negative side effect of this behavior is
that the plane will constantly level off to limit the speed to the magenta speed bug
and by that fails to meet the target altitudes.

**Comment by mSparks43** [comment]
At tine of posting, VNAV descent is computed as:

In descent vertical speed is calculated and displayed on the VNAV DES page, it targets next altitude using idle throttle.

additionally flight envelope protection will kick in the throttles if airspeed falls to much below the bug, Im not aware of any instance where it will pitch for speed in descent, although if it accelerates the vs will increase to reach the target altitude on time.

**Comment by oMrSmith** [comment]
If the current IAS will exceed the target speed (magenta speed buck)
by only 5 knots,
the VS will be **limited** to 500 fpm by VNAV PTH!

![747-400 - 2021-12-11 22 22 02](https://user-images.githubusercontent.com/78870770/145692089-eb6f6551-8f2d-46c3-8308-2d1082bca9e5.png)

**Comment by mSparks43** [comment]
> If the current IAS will exceed the target speed (magenta speed bug) by 5 knots only (!), the vertical speed will already be **limited** to 500 fpm by VNAV PTH!
> 
> ![747-400 - 2021-12-11 22 22 02](https://user-images.githubusercontent.com/78870770/145692256-0260639d-7c70-4511-9d55-5fa075fb7ae5.png)
> 
> This behavior is hilarious as you always have to look at the DES page to find out what VNAV is actually trying to do.
> 
> _Limiting the speed or pitching for the vertical speed required to get to the next target?_
> 
> Then at the same time VNAV PTH will apply thrust if on the other hand the speed drops just slightly below the target speed.
> 
> It is completely wrong.
> 
> There has to be a tolerance area before VNAV PTH will apply thrust or limit the VS. Otherwise it is impossible to get a stable descend.

thats in here
https://github.com/mSparks43/747-400/blob/72c4d3cd77766c7275888cc9374bf645df289e2b/plugins/xtlua/scripts/B747.70.xt.autopilot/B747.70.xt.autopilot.vnav.lua#L29

255kts isnt more than 5 greater than 250kts.

**Comment by oMrSmith** [comment]
Aha! I'll try to change this number to something like 25
and see what happens.

**Comment by mSparks43** [comment]
pull the speedbrake if you need to restrict speed, anything over about 3.2 degrees fpa will make you accelerate during descent.

**Comment by oMrSmith** [comment]
I just changed the number. It caused some other issues.
However it solves the main problem.

Here's what I did:
I changed the number to +25.

I got into the descend and disengaged the A/T.
Then I added thrust to exceed the target speed on purpose.
VNAV would increase the VS accordingly to meet the target altitude.

No more speed limiting by VNAV PTH 
unless the target SPD is exceeded by more than 25 knots...

**Comment by oMrSmith** [comment]
The question is: Should VNAV PTH ever limit SPD
except when reaching 10.000 ft during descend?

**Comment by mSparks43** [comment]
> The question is: Should VNAV PTH ever limit the VS (to protect IAS)?
> 
> I thought it would only do so when reaching 10.000 ft.

My recollection is first it will put a drag required message on the fmc, then once its more than 5kts greater than the restriction it will revert to 500fpm to bleed off the speed.

i wonder if the issue is actually that the function i just linked doesnt return a targetvspeed on the last line.

**Comment by oMrSmith** [comment]
Hey Sparky, I'm not a programmer but trying to read your code.
Is that a comment too?
--print("oob deceleratedDesent upperAlt"..upperAlt.." lowerAlt=".. lowerAlt .." upperAltspdval=".. upperAltspdval .."

**Comment by mSparks43** [comment]
> Hey Sparky, I'm not a programmer but trying to read your code. Is that a comment too? --print("oob deceleratedDesent upperAlt"..upperAlt.." lowerAlt=".. lowerAlt .." upperAltspdval=".. upperAltspdval .."

yeah, -- makes the line get ignored. theres a few prints like that around, they print all the values to the console window so can more easily watch the values (and what its doing) while flying, then comment them out when not needed in case they are needed again in the future.

**Comment by oMrSmith** [comment]
I tried this, but the plane would not except my code ;)

However, the idea makes more sense to me

function deceleratedDesent(targetvspeed)
  
  local upperAlt=math.max(tonumber(getFMSData("desspdtransalt")),tonumber(getFMSData("desrestalt")))
  local lowerAlt=math.min(tonumber(getFMSData("desspdtransalt")),tonumber(getFMSData("desrestalt")))
  local upperAltspdval=tonumber(getFMSData("destranspd"))
  local lowerAltspdval=tonumber(getFMSData("desrestspd"))

  if simDR_pressureAlt1<=(upperAlt+1500) 
  and simDR_pressureAlt1>(upperAlt+500) 
  and simDR_ind_airspeed_kts_pilot>(upperAltspdval+5) 
  then return -500
  else return targetvspeed end
  -- VNAV will limit VS but only between 11500 and 10500 ft.

  if simDR_pressureAlt1<=(upperAlt+500) 
  and simDR_pressureAlt1>(upperAlt-500) 
  and simDR_ind_airspeed_kts_pilot>(upperAltspdval+5) 
  then return 0
  else return targetvspeed end
  -- If IAS still to high VNAV will level off

  if simDR_pressureAlt1<=(lowerAlt+1000) 
  and simDR_ind_airspeed_kts_pilot>(lowerAltspdval+20) 
  then return -500
  else return targetvspeed end
  -- VNAV will limit VS but the margin is higher then just 5 knots
  -- which will stop oscilalltion 

end

**Comment by oMrSmith** [comment]
The problem in the original code is this line:

if simDR_ind_airspeed_kts_pilot>(upperAltspdval+5) then return -500 end

It will keep on triggering speed limitation 
even below 10.000 ft.

So let's say your ar 8.000 ft and the plane gets a little fast , for example 246 knots,
VNAV limit the VS to -500 which will get you high on profile...

**Comment by mSparks43** [comment]
> So let's say your ar 8.000 ft and the plane gets a little fast , for example 246 knots,

its speed restriction+5 
so if the restriction is 240 and you let it get to 246 it will flatten the descent so as to stay below the speed restriction.
if you are 239 kts and it starts accelerating during descent, it should indicate "drag required" on the FMC - speed brakes are not automated, you have to do them by hand.

The way to keep speed under control and below the speed restriction when it needs to descend at a rate that will cause it accelerate is to pull the speedbrake.

The 500fpm is a safety measure so the current speed restriction is not exceeded by more than 5kts, because that is the only automated way the plane has to slow itself down during descent.

**Comment by oMrSmith** [comment]
I strongly believe that it doesn't work this way in reality. 
It is not the task of VNAV PTH to protect the speed throughout the descend.
The pilot can't sit on the speed brake the whole time!

I just tested it in the ZIBO mod. Take a look at that:

![b738 - 2021-12-13 11 48 12](https://user-images.githubusercontent.com/78870770/145799648-fa2f9544-6470-41f0-9586-785ef4eae8fd.png)

I uses manual thrust
in order to **exceed** the IAS on purpose
way above the limit of 240/10000.

You know what VNAV PTH did?
It would **increase** the descend-rate in order to stay on profile.
That is exactly what I believe VANV PTH is supposed to do. 

**It did not limit the descend-rate** in order to protect the speed!

**Comment by mSparks43** [comment]
Looks like the exact way this should work is
![image](https://user-images.githubusercontent.com/6773686/145803433-1713dcb6-eb26-4267-9b46-93d721bd85f1.png)

So basically, if you dont apply drag it will stop VNAV PTH descending altogether, and descend at 500fpm at 250kts.

**Comment by oMrSmith** [comment]
I'm gonna be honest: I don't like those manuals and I agree,
it seems to resemble your programming!

Interestingly it says, it would switch over to VANV SPD - which would make sense
as the pilot can then tell: Oh, I'm leaving the profile.

I'd be really curious though, how it works in real life.
Those manuals don't always tell the truth or are somewhat unclear.

747 by PMDG
![image](https://user-images.githubusercontent.com/78870770/145806589-888fd1de-f064-4efc-a7ad-07d980260fb2.png)
https://youtu.be/AyF5oNehqIk?t=2982

**Comment by mSparks43** [comment]
> as they are good in telling you what to do
> and often bad in telling how things work

Even then they can be misleading, like with the autothrottle issues. They are more like the outside pieces of a jigsaw puzzle, with the important pieces scattered all over the table.

Be good to know if there is a reference/timestamp for this issue in the CBTs, it should be in one of https://github.com/mSparks43/747-400/issues/671 https://github.com/mSparks43/747-400/issues/672 or https://github.com/mSparks43/747-400/issues/688

Pretty sure it will be one of many.

**Comment by oMrSmith** [comment]
Unfortunately it's not very detailed:
https://youtu.be/WRioj2s51IQ?t=791

I think you might have programed it quite right,
with the only difference that
the FMA should announce VNAV SPD
during speed limitation...

Found another interesting video:
https://youtu.be/_ezfyheQMYs?t=2232
