### ISSUE TITLE
[AP] Issue when switching from ALT HLD to VNAV

### ISSUE THREAD

**Issue by oMrSmith** [mSparks43/747-400#733]
During Climb Phase:

When switching from VNAV to ALT HLD and back,
VNAV PTH will engage instead of VNAV SPD.

**Comment by mSparks43** [comment]
just tested this during climb, couldn't recreate, there must be more to it than pressing hold then vnav.

**Comment by oMrSmith** [comment]
In my latest test I could switch back
from ALT to NVAV SPD, 
only the A/T behaved a bit strange
and took too long to regain N1...
