### ISSUE TITLE
Pitch angle on flare should actually be increased

### ISSUE THREAD

**Issue by MCCVeen** [mSparks43/747-400#758]
I just saw that the pitch angle on flare had been decreased in a recent update, so I tried it out and it should actually be increased by a lot. Normal pitch on final with flap 30 at VREF+5 is 2-3 degrees, and on flare it's 3-5 degrees

**Comment by mSparks43** [comment]
It should sum to probably that. It's setting the flight director to zeroratepitch + 0.5 (was 1.0)
Zeroratepitch is the average nose up during the last 800 feet that holds a constant rate of descent - generally around 2 degrees, the issue with 1.0 is that could/would make it start climbing again before it touched the ground. There are prints to the console available to dump out exactly what it is using.

The main reduction was setting the target to negative as it reaches touchdown so the nose doesn't stay up in the air.

**Comment by mSparks43** [comment]
Just did an initial test - not sure the rate of descent needs to be lower here?
https://www.youtube.com/watch?v=IjlbQ5mjmuI
