### ISSUE TITLE
Altitude oscillation

### ISSUE THREAD

**Issue by oMrSmith** [mSparks43/747-400#762]
Lately the plane oscillates 
in altitude quite a lot.

It appears to me that
the pitch reacts to slow
to changes in thrust.

So thrust changes lift the plane
and the pitch compensates too late...

**Comment by mSparks43** [comment]
see also #755

**Comment by paddyfr21** [comment]
This is Very Notable, as well, during a long flight the entire time I was going up and down around 100ft below/above my cruising altitude.

**Comment by mSparks43** [comment]
for further issues related to this create a new issues with the specific circumstances.
