### ISSUE TITLE
AP Issue: Disconnecting CMD will (still) delete LOC & GS

### ISSUE THREAD

**Issue by oMrSmith** [mSparks43/747-400#765]
This is quite annoying when flying an ILS approach without Autoland ;) ...

**Comment by oMrSmith** [comment]
Dear @mSparks43 do you have time to look into this?

**Comment by mSparks43** [comment]
I think probably the solution to this, is that now there is full flight surface override, is to have the AP disconnect just disconnect the AP portion of the override, but leave XP thinking the AP is connected unless its a full reset. I'll mark it for 2.3 but it will probably get pushed back to the release after.

**Comment by oMrSmith** [comment]
Hey @mSparks43 thanks for taking this into account! For now I'll just switch back to the latest official release 2.1, 
which is quite stable and doesn't have this issue...

**Comment by oMrSmith** [comment]
Maybe a (programming-) work around could be
to trigger the pitch and roll mode that are active
when disconnecting the AP. So it would seem as though
the modes stay active...

**Comment by mSparks43** [comment]
Hmm, except it seems to not break for the other modes, I suspect this is probably something else, I'll have a look at what.
