### ISSUE TITLE
APU problem

### ISSUE THREAD

**Issue by martinlest** [mSparks43/747-400#766]
**Describe the bug**

A clear and concise description of what the bug/issue is.

# Please provide documentation references:

Place an x to check the boxes:
- [x] Something found during a flight test
- [ ] FCOM reference included (issues are likely to be closed without this)
- [ ] checked [current](https://github.com/mSparks43/747-400/blob/master/plugins/xtlua/scripts/B747.68.xt.fms/activepages/version.lua) FMC revision ident 
- [ ] Video included (where applicable)
- [ ] Screenshot included (where applicable)

### Bug reports:

Hi. Great aircraft... but the APU can be a real pain to start in VR mode: I hold the APU knob to 'Start' with the handset controller for as long as possible and watch APU N1 rise on the EICAS.. the knob always flicks back to ON by itself after several seconds. Sometimes it has (apparently) been in the START position long enough and all is OK, I get APU power. Other times however, though APU N1 rises to 100%, the APU GEN lights do not come on at 95% and on reaching 100% the N1 then falls again down to 0.0. I have found no way to restart the APU after such a failure: I turn it off, wait a while, then try again.. but the APU N1 stays at zero. So no engine start (and ultimately I just close down XP11 in frustration). It would be great (especially for VR users) if the APU dial would remain at START when moved there, and only click back to ON, automatically, when the threshold point has been reached - and this failure is guaranteed not to happen. Having spent so long setting up the a/c, FMC and all, it is of course _very_ irritating to encounter this and have to abandon the flight altogether. Many thanks! :-)

**Comment by mSparks43** [comment]
https://www.youtube.com/watch?v=9Ss9dYNEYNM

**Comment by martinlest** [comment]
No problem in the real aircraft I am sure, as per the video, but my issue is in XP using (Oculus Quest 2) VR.  For now at least I have reduced the time taken for APU startup in the acf file, down to 15”: the only way I can be sure that the APU is under way before the starter knob automatically clicks back to ‘On’, (try to hold it at the ‘Start’ position as I might).

**Comment by mSparks43** [comment]
The start switch only needs turning momentarily.

But it is disabled until the APU door is open at least half way (takes 5 or 6 seconds after moving the switch to on)

If you follow the procedure in that video you shouldnt have a problem.

you can watch it spin up on the stat page of eicas.

**Comment by martinlest** [comment]
Thanks... but unfortunately, for whatever reason (may well be the Oculus VR), this works for me about 75% of the time. The rest of the time the APU dial clicks back to ON (presumably in just less than the 5-6 seconds you mention, though it seems longer), despite my efforts to hold it for long enough at START and (as I said), though the APU does then reach 100%, it then rapidly falls back again to 0%, and then I can't restart it. To avoid the frustration of this happening (when I have spent 20 minutes setting up the flight by then, only to have to abandon it) I have shortened the APU startup time. No 'biggie': less realistic, but far preferable for me to have an APU that I can successfully start in VR 100% of the time. :-)

**Comment by mSparks43** [comment]
> The rest of the time the APU dial clicks back to ON

It always does, its spring loaded. going to start begins the start procedure. Just do what he did in that video or this one
https://www.youtube.com/watch?v=1WkuwAZDFmY

It only needs to be over to "start" briefly to begin the procedure. But if the APU door hasn't hit the lockout switch it wont make the connection to begin starting, so you have to wait a few seconds between moving it to on (which starts the door opening) and moving to start to begin the startup (else it would suck passengers out the back of the plane)

**Comment by martinlest** [comment]
Thanks again for the reply. I can only repeat what I said before - I can hold the dial (yes, spring-loaded) on START for several seconds, but it flicks itself back to ON automatically, even if I hold the VR handset beam dead steady. I assumed that it turning itself back to ON was a signal that it had activated as required: indeed, often the APU does go on to start up OK, but other times I suppose it must have sprung back to the ON position a fraction early. The APU startup has definitely been triggered.. it reaches 100% on the EICAS/STATS display, but then it falls back to 0%. After that I can't see any way to get the APU to start up again... I wait for it to 'cool down', but turning the dial to START after that has no effect. 

If I set the APU spoolup to 20" I seem to be guaranteed a 100% success rate.. so I guess I will leave it like that for now.

**Comment by mSparks43** [comment]
> I assumed that it turning itself back to ON was a signal that it had activated the APU spoolup as required

It is just a spring loaded switch, there is nothing that "smart" about if.
If the APU door had opened when you moved it to start, the APU will begin to start
If you hadn't left it in on long enough for the APU door to open and enable the switch, it wont start.
