### ISSUE TITLE
Need Help please

### ISSUE THREAD

**Issue by badis1992** [mSparks43/747-400#767]
Place an x to check the boxes:
- [x] Something found during a flight test
- [ ] FCOM reference included (issues are likely to be closed without this)
- [ ] checked [current](https://github.com/mSparks43/747-400/blob/master/plugins/xtlua/scripts/B747.68.xt.fms/activepages/version.lua) FMC revision ident 
- [ ] Video included (where applicable)
- [ ] Screenshot included (where applicable)

### Bug reports:

Hello . I want to thank you guys for this awsome Plane . but i have an issue when i tried to start the plane from cold and dark state . when i press the battery button nothing hapend . No lights no fms i can't start the APU No ground power .can any one help me please . i am new to xplane 11 and i searched for a solution for this but "Nothing".

**Comment by 777joe** [comment]
Did you install the installers provided in the zip package? And also assign a key to 'Avionics' in X plane settings, try turning it on and see if that helps.

**Comment by mSparks43** [comment]
if you are still having this problem, please ask on the discord https://discord.gg/cStTXy5
