### ISSUE TITLE
No procedures in SBPA/ND items too small

### ISSUE THREAD

**Issue by maia911** [mSparks43/747-400#77]
First of all, thank you for this amazing project.
I was trying to do a test flight SBCT-SBPA, and for SBPA there is no procedure when I test this aircraft, but I tested several other aircraft and all went fine.
Second, the ND fonts are too small, I barely can read.
And last, how can I calculate TRIM and CG in TAKEOFF REF page? I tried to find documentation but no luck.
![747-400 - 2020-11-12 18 29 17](https://user-images.githubusercontent.com/74382180/98998511-0302fb00-2515-11eb-9dc4-6cc25cce6512.png)

**Comment by jmsantafe** [comment]
Post your Log.txt. Also there is a message right on the screen that might help.

**Comment by maia911** [comment]
[Log.txt](https://github.com/mSparks43/747-400/files/5533645/Log.txt)
I am aware of this message, but this is the only aircraft that shows this message.

**Comment by maia911** [comment]
The procedure's problem only appears to occur in this airport, so not a big deal.
But i cant manage to understand how to insert values on TAKEOFF REF PAGE(like the TRIM and CG), just a message saying KEY NOT ACTIVE show.
Also, when i press the keys referring to the V1/VR/V2 speeds, three boxes shows on the screen and the speeds shows up on the PFD.
![747-400 - 2020-11-12 19 54 29](https://user-images.githubusercontent.com/74382180/99006235-e53b9300-2520-11eb-8495-ea610e52132b.png)

**Comment by jmsantafe** [comment]
KEY NOT ACTIVE means it has not been programmed yet. Try using the default 747 and loading the procedure you hade trouble with. Also, do you use Navigraph?

**Comment by maia911** [comment]
I tried to use the default 747 and the problem persisted. Yes, I use navigraph. The problem is not in your end. Thank you for your reply and thank you again for the great effort that you guys put in this 747!
