### ISSUE TITLE
Rudder and Yaw Issues

### ISSUE THREAD

**Issue by paddyfr21** [mSparks43/747-400#770]
Notably when climbing or descending, the Rudder begins to sway left and right and fluctuates at different paces(sometimes quite rapidly). This is annoying as often I have to take manual control for the Autopilot to re-join the track. I had removed my Axis Binding for the Rudder and the Issue continues to persist, as a result, I believe that it is not a Hardware problem.

Video Is Attached:

https://user-images.githubusercontent.com/102894661/161416494-38c76a08-6d7e-4519-93c5-8b406c7b493d.mp4

**Comment by paddyfr21** [comment]
I also would like to add that I believe this has something to do with the RR engines, as it doesn't appear to be occurring on the GE's. Haven't tried the PW's yet

**Comment by PilotMathews** [comment]
I get exactly the same issue, and was just about to make a post. I also get it during clearer weather when the aircraft is banking. But in stonger winds and turbulence, it oscillates so severely that it passes the bank limit on the plane. Certainly a problem.

**Comment by paddyfr21** [comment]
Definitel, I've also noticed it so far on the GE and RR engines

**Comment by PilotMathews** [comment]
I've been getting it on my PW liveies too. Until it gets fixed, I can't really fly the 744. We have really bad weather here in Australia at the moment, and this oscillating nearly puts the plane into the ground...

**Comment by paddyfr21** [comment]
Yeah its stopping me from flying it unfortunately, since there are so many good routes that it can be used for. I've also had a few other issues that i've commented on recently but they were created a few months ago and seem to still persist

**Comment by PilotMathews** [comment]
@paddyfr21 I found a temporary fix for this issue by turning off the Yaw Damper.

**Comment by paddyfr21** [comment]
I'll have to try that out thanks, have you experience any other issues such as being unable to maintain altitude and varying between 200ft below and above?

**Comment by mSparks43** [comment]
for further issues related to this create a new issues with the specific circumstances.
