### ISSUE TITLE
Bug with Altitude Capture

### ISSUE THREAD

**Issue by oMrSmith** [mSparks43/747-400#776]
When climbing with FLCH 
ALT HOLD will engage before the
selected MCP ALT has been reached:

![747-400 - 2022-04-15 19 54 48](https://user-images.githubusercontent.com/78870770/163604596-97ffdcb6-9986-47da-90bf-448ca7eb7b37.jpg)

**Comment by mSparks43** [comment]
I dont have details on when exactly it should happen, but it now simulates
![image](https://user-images.githubusercontent.com/6773686/163710653-c3b0b47f-e9a7-4f9e-bc2a-656f2adf10f8.png)

-> It doesn't wait to reach the altitude (like XP default) before engaging alt hold, its currently set to within 1000 feet - only reference I've found seems to say it does this within 8000 feet for FLCH, but that seemed excessive.

![image](https://user-images.githubusercontent.com/6773686/163711013-6d372f10-0a3f-45c7-ad5e-b51ca1e62729.png)

**Comment by oMrSmith** [comment]
With the Boeing Addons I tested
Alt-Capture begins no more than 
200 ft before reaching the target altitude...

**Comment by mSparks43** [comment]
> With the Boeing Addons I tested Alt-Capture begins no more than 200 ft before reaching the target altitude...

yeah, so the problem I've been working around/on is that:
1. XP doesn't seem to simulate "alt capture mode" - just "alt hold mode". And I don't have much detail on alt capture mode. XP seem to just switch directly from FLCH/VS into alt hold mode, this has the side effect that if you are climbing quickly you blow through the +/- 200 foot window, end up in alt hold outside of that 200 window and XP gets confused.
2. I'm not clear what FMA the 744 should show in "alt capture mode", but it looks like it should be "ALT" - regardless of how far away from the altitude you are.
3. It should, afaict, only go above the altitude when using the alt hold button (in which case, from testing, it could climb 1000 feet above the altitude the button was pressed:
![image](https://user-images.githubusercontent.com/6773686/164156571-ea309933-c0ef-43e7-b3f6-c8e148c7b174.png)

**Comment by oMrSmith** [comment]
I get your point. So now you have to create an algorhythm for ALT Capture,
since XP 11 doesn't have one...
Maybe it could be something "simple" like this:
If you're 200 ft away from the target Altitude,
Alt Capture is triggered which limits the VS to something like 500 fpm.
FMA could show ALT with a frame around, so that it is obvious that ALT HLD is
about to be held.
