### ISSUE TITLE
Setting V2 in the MCP panel...

### ISSUE THREAD

**Issue by oMrSmith** [mSparks43/747-400#778]
![image](https://user-images.githubusercontent.com/78870770/163685820-70d9a9cc-079e-4bdf-aa02-dfb78ae504ae.png)

This has been taken from the FCOM that I have...

It implies two things:
1. The MCP speed has to be set to V2 and not to V2 + X.
2. The MCP speed has to be set manually and is not set automatically.

It works the same way in the 737 and 777.
You set the MCP speed to V2 and the pitch mode TOGA will pitch vor MCP SPD + X.

**Comment by PilotMathews** [comment]
I agree, and wish this was a feature aswell. However, in the current state of the aircraft, if you were to set V2 speed on the MCP, the autopilot will throttle-down on-climb rather than pitching up to maintain it. The autopilot is a bit screwed at the moment...

**Comment by mSparks43** [comment]
V2 + 5 is set automatically when you press the VNAV switch. But you dont have to take off with VNAV, so the proceedure is to always set V2 before pressing VNAV

Similar to the speed brakes, the procedure is to always manually pull them before engaging reverse thrust, but engaging reverse thrust will automatically deploy them if they aren't already.

**Comment by oMrSmith** [comment]
I suspect that it should rather work like in the 737 or other boeings...
In the Zibo Mod it works like this:
You set the MCP SPD to V2 (not to V2 + 20!) 
The pitch FD will then command pitch for a speed of (MCP SPD + 20!).
If you would set the MCP SPD to V2 + 20 in the Zibo Mod,
the pitch FD would command a speed of (MCP SPD +20 +20).

**Comment by oMrSmith** [comment]
![image](https://user-images.githubusercontent.com/78870770/163806484-0bab0aff-ea56-47be-8303-6396d4299614.png)

![image](https://user-images.githubusercontent.com/78870770/163806378-beeadd9d-aa82-4309-b43a-472748554d45.png)

https://youtu.be/K_yA456Q6B0?t=50

**Comment by oMrSmith** [comment]
"Pitch commands change to maintain the
IAS MACH window SPD + 10 knots." 
CBT:
https://youtu.be/zshGGhjFAqQ?t=284
