### ISSUE TITLE
Fuselage Needs to be Remodelled

### ISSUE THREAD

**Issue by ALiteralChild** [mSparks43/747-400#78]
Doing my first flight on the 747 right now, and so far its going very well, with only some severe fps stuttering, so well done on all the work put into this!

I wanted to bring back into attention a major visual issue that has, at least personally, peeved me ever since I first saw the Laminar 747 in-sim. The fuselage, from the front and top views, is very skinny, probably only 3/4 the width of the actual 747 fuselage. Here are some pics to explain what I mean.

![Evergreen_B747-200F_EDFH_img2](https://user-images.githubusercontent.com/59975275/99155999-4ed7b080-268b-11eb-873d-c10867bbc9f7.JPG)
![X-System 11_14_2020 2_06_16 PM](https://user-images.githubusercontent.com/59975275/99156008-62831700-268b-11eb-8844-23b65953e9a9.jpg)

As you can see the Laminar 747 is almost unrecognizable with the actual airplane, and while I assume some of it has to do with texturing, a lot is about the model itself.  Even with the new textures, the model looks sloppy in the sim. No blame on you, its obvious that you didn't make the model, although that makes the original model that much more outdated with modern X-Plane standards.

If a new fuselage was to be put into the pipeline it would definitely make my day, and it would put the 747 on payware level so long as the other improvements continue.

**Comment by jmsantafe** [comment]
I believe this is in the works (or maybe a new UV mapping). IMO the fuselage looks pretty good. The distance in the photos does make the sparks 747 look narrower but I think that if you zoomed in and matched the distance in the RL photo they would more alike.

**Comment by schillischote** [comment]
The big difference in perceived proportions lies in the difference of focal length of the virtual camera in X-Plane and the IRL one.
As you zoom in the sim you increase the focal length and bringing it closer to the photo that's attached. 
The fuselage is "fine" juged by proportions it's not a visual miracle either though.

**Comment by rKsanu2MMYvypWePtQWM** [comment]
I tried recreating the image and got this:
![747-400 - 2021-01-16 13 45 10](https://user-images.githubusercontent.com/35463654/104811024-66edbc80-5801-11eb-87f7-79e834b40487.png)

It does look slightly skinnier.
Also, the current UVs of the plane are comically bad. You can see the nose dome looks oval and not round, and even the windows cannot be placed straight with such crooked UV maps:
![747-400 - 2021-01-16 13 45 37](https://user-images.githubusercontent.com/35463654/104811049-93a1d400-5801-11eb-86bd-1c8b42d834de.png)
You can also see the cabin leaving the plane in the corner too, but that's unrelated to UVs

**Comment by crazytimtimtim** [comment]
I believe somebody just started remodeling. It will take a while though because there is a lot to do.

**Comment by rKsanu2MMYvypWePtQWM** [comment]
> I believe somebody just started remodeling. It will take a while though because there is a lot to do.

Hopefully the UVs will be actually usable after the remodel

**Comment by MCCVeen** [comment]
This is one of the reasons why in crosswinds your plane wants to yank to the left or to the right, since the landing gear is already modelled too close together PLUS the actual fuselage is skinnier than real life
