### ISSUE TITLE
[AP] Bug with AP & A/T during VNAV descend when opening the MCP SPD window

### ISSUE THREAD

**Issue by oMrSmith** [mSparks43/747-400#786]
When opening the MCP SPD window
during VNAV descend 
AP & A/T go wild:

https://user-images.githubusercontent.com/78870770/163889711-726b29c8-625f-4a03-927f-10cb2de8c878.mp4

**Comment by mSparks43** [comment]
got a recreate on this, looks like some speed logic needs disabling when the window is open.

**Comment by mSparks43** [comment]
Is this fixed now or does it still do it?

**Comment by oMrSmith** [comment]
I'm pretty sure, It's still there. I'll do my next testflight with next commit...

**Comment by oMrSmith** [comment]
I'm pretty sure, it's still there. I'll do my next testflight after your next commit...

**Comment by mSparks43** [comment]
please retest, lot of VNAV descent fixes went into one of the last pushes, but I only tested this quickly
