### ISSUE TITLE
[AP] Issue with FPM

### ISSUE THREAD

**Issue by oMrSmith** [mSparks43/747-400#788]
If you descend with V/S
with 500 fpm
ALT Capture, once triggered,
will increase the descend rate to 1000 ft.

This behavior is unbelievable.

I pretty sure the figure of 1000 fpm
for ALT Capture is meant **as a limit**
and not as the target.

**Comment by mSparks43** [comment]
hmmm, atm it targets reaching the altitude in 30 seconds once in ALT mode, with switching to ALT on a window scaled by current vertical speed.
Should be (checking calcs, asuming the code is working correctly)
500fpm actual would have an alt window of about 300 feet which it would set 600fpm to finish in 30 secs.

So was the 1000 what it targeted, or just what it went to?

**Comment by oMrSmith** [comment]
I believe in all my test flights,
ALT CAPT would always trigger 1000 ft above or below the target ALT.

When I descended with V/S set to 500 fpm,
the fpm would increase to 1000 fpm,
soon after ALT CAPT had triggered...

**Comment by mSparks43** [comment]
> ALT CAPT would always trigger 1000 ft above or below the target ALT.

Yep, that was the issue, some logic forcing it into alt 1000 feet from the target even though the window at 500fpm is 280 feet

**Comment by oMrSmith** [comment]
This fix makes ALT CAPT work much better!
