### ISSUE TITLE
[AP] Issue with target speed after passing T/D

### ISSUE THREAD

**Issue by oMrSmith** [mSparks43/747-400#792]
When passing the T/D
VNAV should immediately set 
a reduced target speed and idle the thrust.

However this is currently delayed...

**Comment by oMrSmith** [comment]
@mSparks43 just for you Info,
my usual test route is:
LGMK VARI1C VARIX R19 KEA ILS-Z 03L LGAV.
It's nice and short. I use to perform at least two level offs
before reaching the CRZ ALT of at least 14.000 ft 
to see how ALT CAPT works....

**Comment by mSparks43** [comment]
I'll probably tweek this by setting the next speed as a level below the current altitude.

**Comment by oMrSmith** [comment]
I think this is fixed...
