### ISSUE TITLE
[AP] VNAV SPD does not switch to VNAV PTH when reaching (/capturing) the CRZ ALT

### ISSUE THREAD

**Issue by oMrSmith** [mSparks43/747-400#793]
![747-400 - 2022-05-05 22 53 40](https://user-images.githubusercontent.com/78870770/167024838-69e85e80-436a-486d-b71f-b74c3ccb2919.jpg)

As a consequence VNAV will no longer initiate the descend 
after passing the T/D.

PS: It is not possible to reengage VNAV PTH during CRZ.
Instead, VNAV ALT will engage.

**Comment by oMrSmith** [comment]
I know what VNAV ALT means. It should however not trigger when holding the CRZ ALT.

**Comment by mSparks43** [comment]
Thing is, I'm not sure _why_ it triggered (depends what was happening in the run up to it), but once its in VNAV ALT it stays there until pressing the altitude button.

**Comment by oMrSmith** [comment]
I think what I did was this (CRZ ALT was set to 14.000 ft in FMC):
Climb to 8000 ft on VNAV
Climb to 11.000 ft on FLCH
Climb the last step to the CRZ ALT using VNAV.

Maybe this info helps...

**Comment by mSparks43** [comment]
this seem connected to #791 
XP alt hold is misbehaving, going to replace it with one bound to the new level off and altitude change code

**Comment by mSparks43** [comment]
please retest and close if working now

**Comment by mSparks43** [comment]
Quick update on this (and related) before I fix it.
missing piece of the puzzle was aircraft altitude in relation to the VNAV PATH and the 400 foot +/- window either side.
Keying off that I can fix these.

**Comment by prokopiu** [comment]
I can confirm this behavior in my test flight yesterday.

**Comment by oMrSmith** [comment]
This happens only when the T/D is "too" close...
