### ISSUE TITLE
[AP] No way to recapture VNAV SPD after leveling off with FLCH (before reaching CRZ ALT)

### ISSUE THREAD

**Issue by oMrSmith** [mSparks43/747-400#794]
https://user-images.githubusercontent.com/78870770/167292873-cd418ffe-5133-49d7-8a64-17eaf5592dc8.mp4

**Comment by oMrSmith** [comment]
When I clicked the VNAV button, VNAV SPD should have engaged immediately 
as I had already increased the MCP ALT to the CRZ ALT.

**Comment by oMrSmith** [comment]
Could it be that the plane switches the flight phase before reaching the CRZ ALT?

**Comment by oMrSmith** [comment]
Update:
On my last test-flight, this happened when I tried to re-engage VNAV SPD:

![747-400 - 2022-05-08 21 07 38](https://user-images.githubusercontent.com/78870770/167312397-6e8ef4b4-f4f2-4af7-80f9-707d9c9ad643.jpg)

**Comment by mSparks43** [comment]
Are these with the new ALT HOLD logic?

Most of these seem to be related to bugs in the default alt hold system.

**Comment by oMrSmith** [comment]
I think so. Before I test, I always check GutHub ;)

**Comment by mSparks43** [comment]
Right, so there's a few things that can happen here. It will only VNAV to cruise alt if it isn't in the initial phases of descent, some of that is legs page issues (#724) - when I'm on short hops, what will often happen is the TOD for the current altitude is after a waypoint altitude (e.g. I'm at 17000 feet, there's a waypoint alt of 19000 feet 55nm away and ToD at 17k is more than 55nm away - in this instance it will level off at 19k to ToD, the pic in the video looks in the OP looks like it might be like this)

There is also #713 and a couple of related issues which is now fixable when I can find out when/why it happens.

**Comment by oMrSmith** [comment]
But couldn't the algorhythm be easier like:
If the current ALT is below the FMC CRZ ALT and the T/D is still ahead,
pressing VNAV will engage VNAV SPD?

**Comment by mSparks43** [comment]
Theres about 4 or 5 different cases as you get close to ToD, at cruise, too low, too high, climbing/descending/holding altitude.

Currently it's set (bugs excluded) to hold altitude until its time to descend once you are in range of the airport.

**Comment by oMrSmith** [comment]
I will try something different on my next test. I suspect that this issue conly comes up,
if I level off inbetween take off and Top of Climb.

**Comment by oMrSmith** [comment]
So here is the situation:

![747-400 - 2022-05-10 21 24 42](https://user-images.githubusercontent.com/78870770/167707190-3ae8027c-fea5-48e4-b461-8b5df42a5ec0.jpg)

Yes it's a short trip. But I don't see any reason
why the plane should refuse to climb to the CRZ ALT of the FMC.
It used to do so in earlier versions.

**Comment by mSparks43** [comment]
Currently defined against these
descent phase starts from within 50NM of T/D, otherwise it uses the current altitude when it gets there as the cruise alt
![image](https://user-images.githubusercontent.com/6773686/167765613-d10cf1f1-e049-4e2e-ab87-9612df8fe712.png)
![image](https://user-images.githubusercontent.com/6773686/167765873-0468130b-5eb4-4625-b8ce-fa528b137798.png)

**Comment by oMrSmith** [comment]
Is this FCOM somewhere available as PDF? Seems I have another version...

I understand this differently:
If you are within 50 nm from T/D you may start an early descend, but you don't have to.

**Comment by mSparks43** [comment]
this should be fixed now
