### ISSUE TITLE
[AP] LOC does no longer capture

### ISSUE THREAD

**Issue by oMrSmith** [mSparks43/747-400#797]
![747-400 - 2022-05-08 21 20 53](https://user-images.githubusercontent.com/78870770/167312501-d6aaee2f-4288-4eb2-9a13-3f2ab2c8fff8.jpg)

Is there like a maximum SPD to capture the LOC?

I know I was a bit fast on approach, but I flew right on the LOC
for quite a bit and it would not capture. Never had this before...

**Comment by mSparks43** [comment]
One of the things I've seen kill the loc, is if it "part" captures in a turn but then loses it when the turn is to wide, XP also simulates different ILS which have different reception ranges, CAT III you can capture from like 15 miles away, CAT I you almost have to be on the runway before it will engage.

**Comment by oMrSmith** [comment]
On my last testflight it worked again. Also: LOC & GS got no longer lost after disconnecting the AP.
The AP seems to be kind of stable from the descend phase on.
