### ISSUE TITLE
IRS Alignement too long

### ISSUE THREAD

**Issue by kontroland** [mSparks43/747-400#80]
Would be great if we could choose the alignment duration in the fmc

**Comment by mSparks43** [comment]
Will implement 
![image](https://user-images.githubusercontent.com/6773686/101162474-af2a9400-3632-11eb-9e1b-4daf94944543.png)

**Comment by rKsanu2MMYvypWePtQWM** [comment]
> Will implement
> ![image](https://user-images.githubusercontent.com/6773686/101162474-af2a9400-3632-11eb-9e1b-4daf94944543.png)

That's not the same thing as he requested, but having this is even nicer.
It only works when you already have aligned IRS, and is used to remove the accumulated tracking error after a flight, while he asked to speed up the regular align that happens from cold and dark.

**Comment by Stratocruizer** [comment]
Probably another idea for future plane options, in the maint menu of the fmc.

**Comment by mSparks43** [comment]
> > Will implement
> > ![image](https://user-images.githubusercontent.com/6773686/101162474-af2a9400-3632-11eb-9e1b-4daf94944543.png)
> 
> That's not the same thing as he requested, but having this is even nicer.
> It only works when you already have aligned IRS, and is used to remove the accumulated tracking error after a flight, while he asked to speed up the regular align that happens from cold and dark.

#161 also made it a simconfig option
