### ISSUE TITLE
Invalid Gross Weight PERF Entry

### ISSUE THREAD

**Issue by THEONEANDONLYPLANE** [mSparks43/747-400#803]
In the PERF page of the 744's FMC, there are two accepted formats for the GR WT entry- XXX or XXX.X. 

Thanks to a wonderful test subject, it was discovered that formats outside of the noted formats are accepted. In reality, the FMC should reply with "INVALID ENTRY", instead of accepting the flawed values

FCOM Reference:
![20220529_144241](https://user-images.githubusercontent.com/55368409/170887296-ca99e939-4421-4b5f-a36d-71e58865baa4.jpg)
.
Flawed Screenshot: (NOTICE GR WT ENTRY):
![unknown](https://user-images.githubusercontent.com/55368409/170887372-6d4a5e23-6d7b-4510-a786-c54625131484.png)

**Comment by ToastedNoodleFan** [comment]
WOO! I'm the test subject, and yes, I did get it fixed thru the work of some expert simmers.
