### ISSUE TITLE
747-400-master.zip archive is currupt

### ISSUE THREAD

**Issue by oMrSmith** [mSparks43/747-400#804]
The archieve is less than 400 mb small and can't be opened.
Seems like most of the files went missing.

**Comment by oMrSmith** [comment]
I can't test... :(

**Comment by prokopiu** [comment]
I had the same problem. I cloned the repo and added the files manually.

**Comment by oMrSmith** [comment]
Nice, it seems to work again!

**Comment by oMrSmith** [comment]
@prokopiu looks like the download works again.
