### ISSUE TITLE
Upper EICAS - ENG - Throttle indicator line already almost up with idle throttle (v2.3 cloned from repo)

### ISSUE THREAD

**Issue by prokopiu** [mSparks43/747-400#805]
On the display of the N1 bars the white line for the throttle position is too high on idle. When I move the levers up it moves out of the display. This is during preflight and startup.
![image](https://user-images.githubusercontent.com/68238857/174400647-f676a4e9-7730-4335-b157-01f593940ea4.png)

**Comment by prokopiu** [comment]
Same for EPR. the lines move into the EPR field
![image](https://user-images.githubusercontent.com/68238857/174425824-4cc1152d-7859-4d43-97cd-77fa7a98e883.png)

**Comment by mSparks43** [comment]
which airframe is this?

**Comment by prokopiu** [comment]
see https://youtu.be/BzQ0CUDZhak at 00:17:27 actually only a third of the way....

**Comment by mSparks43** [comment]
fixed in https://github.com/mSparks43/747-400/commit/e61e52c79895cc082d8fcac1ee4449a75600e636
