### ISSUE TITLE
EICAS Flaps white bar missing (v2.3 cloned from repo)

### ISSUE THREAD

**Issue by prokopiu** [mSparks43/747-400#808]
The white bar on the flaps display showing the position of the flaps is missing. On the picture the flaps were fully extended outside and flaps text was green but white bar is missing.
![image](https://user-images.githubusercontent.com/68238857/174404486-d1401eec-0ed9-45d1-a2d2-407b21c0d6b1.png)

**Comment by mSparks43** [comment]
going to need more detail on how to recreate this one - which airframe? on F-GITJ/HQ-AJ I get
![image](https://user-images.githubusercontent.com/6773686/174677029-060e7a21-072b-4213-97e7-147df1fea09d.png)

**Comment by prokopiu** [comment]
Hi, I updated stuff yesterday pulling the master branch again and it works now + I have a new 4 bar display :-) :
![image](https://user-images.githubusercontent.com/68238857/174718117-4d8921f3-7e2c-4cdf-8b91-bcebce3ccd36.png)
![image](https://user-images.githubusercontent.com/68238857/174718188-eba10d86-1d63-462e-9d83-a92f06ba8d16.png)

**Comment by CalibraNR** [comment]
Latest version seems that at Flaps 1 and 25 the white bar is missaligned. Do not know if it's only visuals or the flaps indeed aren't at their selected position.
![Screenshot_54](https://user-images.githubusercontent.com/125405575/219961175-cadd47b8-7f27-427c-84c6-4b0490597a17.jpg)
![Screenshot_56](https://user-images.githubusercontent.com/125405575/219961176-66f17d0e-d2ff-4367-be93-7c44f08ed927.jpg)

**Comment by mSparks43** [comment]
oops.
kinda, the flaps position was changed recently to more accurately represent the aerodynamics at different flaps settings, but the display didn't get updated to match it.
