### ISSUE TITLE
FMC - POS INIT - REF AIRPORT INOP after IRS POS entered (v2.3 cloned from repo)

### ISSUE THREAD

**Issue by prokopiu** [mSparks43/747-400#810]
As long as I have not entered the IRS position I can enter my reference airport.
![image](https://user-images.githubusercontent.com/68238857/174426095-e15f4c13-6684-4664-b6c8-722779cf49cc.png)

Once I have entered it the reference airport is INOP
![image](https://user-images.githubusercontent.com/68238857/174426119-55661b13-a4f1-4067-80d2-5dad2c5477ce.png)

**Comment by mSparks43** [comment]
Need to switch the IRUs from NAV to ALIGN to erase errors. (that REF airport is just for getting an entry for SET IRS POS)

![image](https://user-images.githubusercontent.com/6773686/174439357-6ed54ae8-ed07-43ee-a1d4-7fdfb662db28.png)

**Comment by prokopiu** [comment]
Could not recreate the issue on my second flight. I think we can close this one.
