### ISSUE TITLE
Request to banish switch over to MACH SPD (for now)

### ISSUE THREAD

**Issue by oMrSmith** [mSparks43/747-400#812]
Currently it is impossible to have a normal CRZ flight
without opening the SPD Window and switching to knots
due to the bug with the flickering SPD bug.

I want to propose to simply banish MACH SPD for now'
and let it stay with knots, if possible...

**Comment by mSparks43** [comment]
I'm not seeing this - it must be something to do with trying to cruise at a low altitude?
If 0.81 cruise speed is to high you can set a custom one on VNAV cruise page 2, line key 2
![image](https://user-images.githubusercontent.com/6773686/174435690-dc51dacd-f805-491f-938b-f4aa9522b7f9.png)

**Comment by oMrSmith** [comment]
> it must be something to do with trying to cruise at a low altitude?

Yes I admit. LGMK - LGAV (CRZ 13.000). But I don't think it should happen anyway.
Thanks for the tip though! This might be a work around for my issue.

**Comment by oMrSmith** [comment]
So it looks like the issue is: The CRZ speed is set too high during low altitude CRZ.

**Comment by mSparks43** [comment]
> (CRZ 13.000)

So the flicker here is maybe because it is expecting climb speed (272kts) between 10,000 and the 18,000 transition altitude

**Comment by oMrSmith** [comment]
duplicate of #777
