### ISSUE TITLE
[AP] Changing Mach Speed on CRZ Page has no effect

### ISSUE THREAD

**Issue by oMrSmith** [mSparks43/747-400#816]
... Therefore it does not solve the issue with the flickering speed bug during low altitude CRZ.

![747-400 - 2022-07-03 12 18 22](https://user-images.githubusercontent.com/78870770/177035368-fd79e931-d49c-4064-9dcb-86bb4699cf1a.png)

It would be awsome if this could be fixed.

**Comment by mSparks43** [comment]
This is going to be something to do with the low altitude again, VNAV is currently missing these atm:
![image](https://user-images.githubusercontent.com/6773686/177129151-836a2934-e018-4a1d-8de1-66a4fcfff3d1.png)
![image](https://user-images.githubusercontent.com/6773686/177129302-58b684b6-25b3-4975-923a-c3bff3934491.png)
![image](https://user-images.githubusercontent.com/6773686/177129556-8042c693-f582-4f79-9b9d-dcc51a110ae9.png)

**Comment by mSparks43** [comment]
please confirm you didn't have a cost index set (doing so disables manual cruise speed entry)

**Comment by oMrSmith** [comment]
Ahaaaaaaaa! I had a cost index set. I'll retest this without CI.

**Comment by oMrSmith** [comment]
Maybe it would be better for the FMC then
to deny changing the ECON SPD if a CI has been entered before. 
Because if you can enter it but it is beeing disregarded, it seems like bug.

**Comment by oMrSmith** [comment]
So now it works. Just have to leave the CI blank. Cool! Thanks for the tip.
In the latest version, it seems like VNAV does no longer automatically bug for appropriate speeds
after crossing 10.000 ft. But that's ok for me. ;)
