### ISSUE TITLE
flight - data (jdat) reports some events in wrong order and other events that did not happen at all

### ISSUE THREAD

**Issue by oMrSmith** [mSparks43/747-400#818]
{"time":"2022/06/26 21:23:16","keyPress":"AP ON"}
**{"time":"2022/06/26 21:23:38","keyPress":"FLCH"}
{"time":"2022/06/26 21:23:42","keyPress":"VNAV"}**
{"time":"2022/06/26 21:23:44","flightData":{"simDR_ind_airspeed_kts_pilot":239.93264770508,"radarAlt":5190.90625,"roll":-19.801652908325,"pitch":9.4483079910278,"simDR_groundspeed":130.62716674805,"simDR_vvi_fpm_pilot":2882.8605957031,"simDR_longitude":25.313814163208,"simDR_pressureAlt1":5154.3359375,"simDR_true_heading":329.92098999023,"simDR_latitude":37.50651550293},"acData":{"simDR_fuel":52085.09375,"flaps":0.16699999570847,"simDR_GRWT":270882.25},"fmaData":{"active":{"pitch":"VNAV SPD","roll":"LNAV"},"armed":{"pitch":"NONE","roll":"NONE"},"AT":"THR REF","status":"CMD"}}
{"time":"2022/06/26 21:23:54","keyPress":"HEADING SELECT"}
{"time":"2022/06/26 21:23:59","keyPress":"LNAV"}
{"time":"2022/06/26 21:24:01","keyPress":"AP ON"}
**{"time":"2022/06/26 21:24:04","CASDATA":[">AUTOPILOT DISC warning"]}**
{"time":"2022/06/26 21:24:09","CASDATA":[]}
{"time":"2022/06/26 21:24:14","flightData":{"simDR_ind_airspeed_kts_pilot":238.89562988281,"radarAlt":6737.783203125,"roll":-20.027284622192,"pitch":9.7114582061768,"simDR_groundspeed":133.41516113281,"simDR_vvi_fpm_pilot":2971.1469726563,"simDR_longitude":25.279273986816,"simDR_pressureAlt1":6700.1899414063,"simDR_true_heading":286.11611938477,"simDR_latitude":37.527431488037},"acData":{"simDR_fuel":51932.796875,"flaps":0,"simDR_GRWT":270730},"fmaData":{"active":{"pitch":"VNAV SPD","roll":"LNAV"},"armed":{"pitch":"NONE","roll":"NONE"},"AT":"THR REF","status":"CMD"}}
{"time":"2022/06/26 21:24:19","keyPress":"HEADING SELECT"}
{"time":"2022/06/26 21:24:21","keyPress":"LNAV"}
**{"time":"2022/06/26 21:24:36","keyPress":"FLCH"}**

I never pressed the FLCH button and the
AUTOPILOT DISC warning
occoured right after I pressed HEADING SELECT.

**Comment by mSparks43** [comment]
keypress is probably a bad name for it - its a FLCH command, so with VNAV switching on VNAV SPD - next line on the FMA output - "pitch":"VNAV SPD"

Those are "at the time", whereas CASDATA is just recorded from the CAS display, which can take a few seconds to actually show up on the display and be recorded.

**Comment by oMrSmith** [comment]
Ah I see, thanks for your explanation. I'll close this one then...
