### ISSUE TITLE
AP doesn't function with both FDs off on takeoff

### ISSUE THREAD

**Issue by mSparks43** [mSparks43/747-400#820]
**Describe the bug**

AP doesn't function with both FDs off on takeoff

Place an x to check the boxes:
- [x] Something found during a flight test

Airframe: Any

(possible workaround; switch at least one FD on before takeoff - but unclear if this actually works)

**Comment by prokopiu** [comment]
In X-Plane the A/P and FDs are tightly linked as far as I know. Turning all FDs off ususally prevents the A/P from functioning. 
I think that FD1 is usually sufficient to feed the XP A/P.
Why would someone not use any FD on takeoff?
