### ISSUE TITLE
BetterPushback failure

### ISSUE THREAD

**Issue by gregmorgansen** [mSparks43/747-400#823]
When starting BetterPushback, the screen goes white and the airport detail disappears.

# Please provide documentation references:

Place an x to check the boxes:
- [x] Something found during a flight test
- [ ] FCOM reference included (issues are likely to be closed without this)
- [ ] checked [current](https://github.com/mSparks43/747-400/blob/master/plugins/xtlua/scripts/B747.68.xt.fms/activepages/version.lua) FMC revision ident 
- [ ] Video included (where applicable)
- [ ] Screenshot included (where applicable)

### Bug reports:

Many remaining issues are likely airframe specific, please provide the livery this bug happens with

Airframe: Northwest Airlines________ 

The livery folder will also contain a jdat file of various data recorded during the flight, please attach it to the report if the issue occurs during a specific phase of flight

Please replace this line with a detailed description of the issue

**Comment by mSparks43** [comment]
this is a bug in betterpushback, afaics there is nothing can be done here to fix it.
