### ISSUE TITLE
[AP] A/T issue during descend with VNAV SPD (still present)

### ISSUE THREAD

**Issue by oMrSmith** [mSparks43/747-400#829]
When VNAV initiates the descend after crossing the T/D,
the A/T will go to N1, if the MCP window is open, causing massive overspeed.

"HOLD", which is shown as the current FMA, is not actually active.
Thrust changes by itself even if the hardware throttle has been set to idle before.

 (Just tested with the very latest fix.)

**Comment by oMrSmith** [comment]
@mSparks43 So I just retested.
The issue can be solved by pulling back the thrust.
However: HOLD increases thrust to N1,
even if the position of the throttle is lower inside the plane and on the hardware throttle.

So it looks like HOLD reads an old throttle position
whereas it should read the actual position of the throttle inside the plane
since the purpose of HOLD is to hold the throttle and not increase it by itself.

**Comment by mSparks43** [comment]
> Besides that: Shouldn't the A/T go to IDLE first, before it engages HOLD?

That's the plan :0

**Comment by oMrSmith** [comment]
It is strange, but I still have the issue in a certain situation:
If I open the SPD window shortly _after_ passing T/D
VNAV SPD will engage and the thrust mode changes to HOLD.
Then, although both hardware throttle and throttle in the plane are idle,
the thrust mode HOLD will increase thrust to N1.

So it seems as though HOLD does neither read the position of the hardware throttle
nor the position of the throttle in the plane, which I think it should.

Besides that, everything works way better than before since you latest fixes...
