### ISSUE TITLE
can only collect 1 auto pilot option not all 

### ISSUE THREAD

**Issue by riderecon** [mSparks43/747-400#834]
**Describe the bug**

# Please provide documentation references:

Place an x to check the boxes:
- [x] Something found during a flight test
- [ ] FCOM reference included (issues are likely to be closed without this)
- [ ] checked [current](https://github.com/mSparks43/747-400/blob/master/plugins/xtlua/scripts/B747.68.xt.fms/activepages/version.lua) FMC revision ident 
- [ ] Video included (where applicable)
- [ ] Screenshot included (where applicable)

### Bug reports:

Many remaining issues are likely airframe specific, please provide the livery this bug happens with

Airframe: ________ 

The livery folder will also contain a jdat file of various data recorded during the flight, please attach it to the report if the issue occurs during a specific phase of flight

Please replace this line with a detailed description of the issue

**Comment by mSparks43** [comment]
This is according to the fcom aiui.
Only way to change autopilot is to disconnect the current one then connect a different one.
Only time more than one is active is when all three APs engage automatically at ~1500 feet agl for Land 3.
See #656
