### ISSUE TITLE
URSS ILS NOT CPTURING 

### ISSUE THREAD

**Issue by kit-v-kapushone** [mSparks43/747-400#838]
I made flight from UUEE to URSS
But on approach i got this (check FMC)

(repost from discord)
![49A1F78E-F4EF-4CE0-9D52-ADDED9A79F36](https://user-images.githubusercontent.com/82118818/203627691-fe2f5a25-7e1e-428f-90f9-a2a07419a9ef.png)

**Comment by mSparks43** [comment]
I got a recreate on this URSS manually entering the frequency/course and hitting the approach button, looks like maybe an issue with manual tuning logic, but also need to check with respect to distance calculations - could be related to not having a full flight plan (or both)
