### ISSUE TITLE
Macbook Installation

### ISSUE THREAD

**Issue by federicopesce** [mSparks43/747-400#843]
Hi guys,
I'm trying to add this fantastic plane to my Xplane 11. Unfortunately, even if I tried everything, I can't find a way to see the plane in my list.
I have downloaded the plane, extracted the file into the airplanes folder of the simulator. I see that I should execute a command into a folder but since I'm not super tech I don't know how to do it.
I opened terminal app when the aircraft fold was opened, copied and pasted the command and pressed enter. tried to check if the plane was in the in-game list but nothing.
Can someone help me? I didn't find any tutorial online
Thank you

**Comment by robsjw** [comment]
Hi, did you ever find a solution to this? I'm not super techy either and can't find any solution online. Tried typing the code they give into the terminal app for the xplane folder but nothing happens

**Comment by mSparks43** [comment]
for xplane 11 you need to extract the backport.zip over the XP12 version.
see the latest readme.
