### ISSUE TITLE
fmc message 

### ISSUE THREAD

**Issue by Giankynav** [mSparks43/747-400#846]
Buongiorno a tutti, ho provato il 747, su xplane 12 ma ho notato che durante la quota quindi con autopilota inserito, se nell'fmc compare un messaggio, l'aereo comincia a picchiare e a perdere i dati di rotta ,  ho notato che se si preme il tasto clr sull'fmc tutto torna alla normalità sicuramente pubblicherò il video sul mio canale visto che lo porto come argomento, ma vi faccio questa segnalazione per correggerlo, un altra cosa, che ho notato che con l'atc di world traffic, non va molto d'accordo, anche se una volta limitate le iterazioni , tutto procede bene. ho notato anche che consuma molta cpu durante le fasi di stallo in aeroporto e movimenti a terra. spero che queste segnalazioni vi siano utili. 
vi ringrazio per lo splendido lavoro che state facendo. 

Hello everyone, I tried the 747, on xplane 12 but I noticed that during the altitude, therefore with the autopilot engaged, if a message appears in the FMC, the plane begins to dive and lose the route data, I noticed that if he presses the clr key on the fmc everything goes back to normal I will surely publish the video on my channel since I bring it as a topic, but I make this report to correct it, another thing, that I noticed that with the world traffic atc, it doesn't get along very well, although once you limit the iterations, everything is fine. I also noticed that it consumes a lot of cpu during airport stalls and ground movements. I hope these reports are useful to you.
thank you for the wonderful work you are doing.

link video : https://www.youtube.com/watch?v=henPYm1ewDc

**Comment by mSparks43** [comment]
> I also noticed that it consumes a lot of cpu during airport stalls and ground movements.

This is/was an issue on early XP12.06 betas. I think it should be fixed on the latest.

>if a message appears in the FMC, the plane begins to dive and lose the route data, I noticed that if he presses the clr key on the fmc everything goes back to normal

Could you let me know the timestamp in the video of this behaviour.

**Comment by mSparks43** [comment]
please retest
