### ISSUE TITLE
Default FMS

### ISSUE THREAD

**Issue by T4J737NG** [mSparks43/747-400#853]
**Describe the bug**

# Please provide documentation references:
![Scherm­afbeelding 2023-08-25 om 21 25 23](https://github.com/mSparks43/747-400/assets/143220247/17d021b8-d521-4207-aab3-104c24a0ee98)

Place an x to check the boxes:
- [x] Something found during a flight test
- [ ] FCOM reference included (issues are likely to be closed without this)
- [ ] checked [current](https://github.com/mSparks43/747-400/blob/master/plugins/xtlua/scripts/B747.68.xt.fms/activepages/version.lua) FMC revision ident 
- [ ] Video included (where applicable)
- [X] Screenshot included (where applicable)

### Bug reports:

Many remaining issues are likely airframe specific, please provide the livery this bug happens with

Airframe: default

The livery folder will also contain a jdat file of various data recorded during the flight, please attach it to the report if the issue occurs during a specific phase of flight

After installation found FMS to be the default X-plane one and not the updated that came with the previous version. 

Using the latest version of XP11 on Mac

**Comment by T4J737NG** [comment]
Attached log file for diagnostic purposes.

[Log.txt](https://github.com/mSparks43/747-400/files/12443041/Log.txt)

**Comment by mSparks43** [comment]
you opened the default 747 rather than the one you downloaded.
Loaded: /.. Support/Steam/steamapps/common/X-Plane 11/Aircraft/Laminar Research/Boeing B747-400/plugins/xlua/64/mac.xpl (com.x-plane.xlua.1.0.0r1).

probably missing the backport to xp11
