### ISSUE TITLE
APP LOC button doesn't work

### ISSUE THREAD

**Issue by snipercable** [mSparks43/747-400#856]
![344289649](https://github.com/mSparks43/747-400/assets/142358343/ed104b2e-605d-498c-8565-89271f0d1ce1)
**Describe the bug**

# Please provide documentation references:

Place an x to check the boxes:
- [x] Something found during a flight test
- [ ] FCOM reference included (issues are likely to be closed without this)
- [ ] checked [current](https://github.com/mSparks43/747-400/blob/master/plugins/xtlua/scripts/B747.68.xt.fms/activepages/version.lua) FMC revision ident 
- [ ] Video included (where applicable)
- [x] Screenshot included (where applicable)

### Bug reports:

Many remaining issues are likely airframe specific, please provide the livery this bug happens with

Airframe: All

The livery folder will also contain a jdat file of various data recorded during the flight, please attach it to the report if the issue occurs during a specific phase of flight

Please replace this line with a detailed description of the issue

**Comment by mSparks43** [comment]
You need a ILS (auto) tuned on the NAV RAD page before you can use it.
Either by selecting an ILS approach or manually tuning it on the NAV RAD page as per the FCOM

**Comment by mSparks43** [comment]
Can't recreate this issue.
