### ISSUE TITLE
Engine RPM increases at the moment "LAND3" appears on PFD

### ISSUE THREAD

**Issue by toadlife** [mSparks43/747-400#857]
**EDIT:** After watching the two videos more closely, I've updated this description:

When descending towards the runway on an ILS approach, when "LAND3" appears on the PFD, the engine RPM increases significantly, causing the plane to rapidly accelerate and float over the glideslope. The engine RPM increase does not correspond to an increase in the position of the throttle levers.  The auto-throttle immediately retards the throttles to try and compensate and the autopilot tries to recover, but can't in time to recover the glideslope before the threshold.

I took videos of two landings.  Timestamps of when the phenomenon occurs are in the videos' descriptions.

One into KOAK RW12:

[https://www.youtube.com/watch?v=O0XVVjlaxjQ](https://www.youtube.com/watch?v=Or0oJoz6itE)

One into KSFO RW28R:

[https://www.youtube.com/watch?v=O0XVVjlaxjQ](https://www.youtube.com/watch?v=O0XVVjlaxjQ)

Both approaches, the plane had a ZFW of 507-521 with a light fuel load. Up until the "LAND 3" apears on the PFD, the autothrottle is able to hold both the speed and the glideslope. I saved the logs and flight_data.jdat from each flight and also included the fms plan used for each flight.

# Please provide documentation references:

Place an x to check the boxes:
- [x] Something found during a flight test
- [ ] FCOM reference included (issues are likely to be closed without this)
- [ ] checked [current](https://github.com/mSparks43/747-400/blob/master/plugins/xtlua/scripts/B747.68.xt.fms/activepages/version.lua) FMC revision ident 
- [x] Video included (where applicable)
- [ ] Screenshot included (where applicable)

Airframe: 747-400
Version: https://github.com/mSparks43/747-400/commit/723fced7944330b869f89b72ec94ff96cde3d425

[Sparky LAND3 AT BugReport.zip](https://github.com/mSparks43/747-400/files/12644809/Sparky.LAND3.AT.BugReport.zip)

**Comment by toadlife** [comment]
After watching the two videos more closely, I've updated this descriptions. I did not notice that _the engine RPM increase does not correspond to movement of the throttle controls_.

**Comment by toadlife** [comment]
After flying a few more approaches, I'm wondering if the issue might be the VREF speeds reported by the FMC being too low and plane simply losing too much lift. I flew an approach yesterday with the speed set to VREF+10 and it was a little long, but otherwise smooth automatic landing. I will fly more approaches but with the physics model display turned on to see if that's the case.

**Comment by mSparks43** [comment]
Nice, you beat me to an issue report

Absolutely phenomenal find. Here's what was happening

When the engines mode switches from CRZ to GA, the max allowed EPR changes, and target EPR was being set based on a fraction of max EPR, fraction of max wasn't being changed, resulting in an increase in target EPR, and the engines spooling up.

I'll add some code to hold the target when the mode changes should fix it.

This issue will auto close when the relevant files are updated.

**Comment by toadlife** [comment]
Glad I could help! I'm generally not into to more complex/study level aircraft so the whole time I was afraid I was just doing something wrong.

**Comment by toadlife** [comment]
I don't think this issue is fixed. I'm still experiencing it - sometimes to a lesser degree, but it still happens. 

![sparky_744_EPR](https://github.com/mSparks43/747-400/assets/1184777/14bda1b7-cf74-4f8c-a6f2-071edee8ae58)


At 1:05 of this video, I'm setting the EPR to 1.00, but it doesn't show on the screen after I input it. I noticed that if I set this value to 1.00, to increase in RPM when LAND3 activates is not as pronounced. I should have set the recording so that it shows the mouse cursor. I will make another.
https://youtu.be/Eb7zeHCUBDc?si=mU3CmJbRDrLp--Pr&t=65

**Comment by toadlife** [comment]
In the same video I linked to in the last comment, at around 26:47, you can see the subtle RPM increase when LAND3 appears.

https://youtu.be/Eb7zeHCUBDc?si=GyGvg56t-7bfr-mK&t=1607

**Comment by mSparks43** [comment]
> In the same video I linked to in the last comment, at around 26:47, you can see the subtle RPM increase when LAND3 appears.
> 
> https://youtu.be/Eb7zeHCUBDc?si=GyGvg56t-7bfr-mK&t=1607

I would expect some seeking when the mode changes. When it switches thrust mode to GA, the throttle lever to thrust gets remapped to a greater range, before it wasn't taking this into consideration as was keeping the throttle in the same place, the "fix" moves the throttle to its new position so the thrust target is the same as it was before the switch over.

There is a gap here, as this doesn't happen when the ECC is in alternate mode,
https://www.youtube.com/watch?v=iwJqG-OXCKE

and ALTN ECCs are not particularly to spec
