### ISSUE TITLE
Captain's VR Hotspot is several feet behind the captain's chair

### ISSUE THREAD

**Issue by toadlife** [mSparks43/747-400#858]
This looks like a simple typo. The captain's teleport hotspot is several feet behind the captains chair.

https://www.youtube.com/watch?v=9QVc0bZHrh4

Changing the "z" portion of the "PRESET_XYZ" in the vrconfig.txt file so the captains "z" matches the copilot's "z" fixes the issue.

I'm attaching a fixed 747-400_vrconfig.txt file.

# Please provide documentation references:

Place an x to check the boxes:
- [x] Something found during a flight test
- [ ] FCOM reference included (issues are likely to be closed without this)
- [ ] checked [current](https://github.com/mSparks43/747-400/blob/master/plugins/xtlua/scripts/B747.68.xt.fms/activepages/version.lua) FMC revision ident 
- [x] Video included (where applicable)
- [ ] Screenshot included (where applicable)

### Bug reports:

Airframe: 747-400
[747-400_vrconfig.txt](https://github.com/mSparks43/747-400/files/12721313/747-400_vrconfig.txt)

**Comment by mSparks43** [comment]
merged in next commit
