### ISSUE TITLE
T/D distance on FMC

### ISSUE THREAD

**Issue by rKsanu2MMYvypWePtQWM** [mSparks43/747-400#86]
![Screenshot_20201119_195837](https://user-images.githubusercontent.com/35463654/99704886-a9b14380-2aa1-11eb-8cab-2028e5624b57.png)

The distance to T/D does not match. Also, at one point the planes' CDU T/D value (in green) started going up, instead of down. The default FMC CDU was decreasing as it should.

**Comment by mSparks43** [comment]
This seems to be related to vector legs in the flight plan. work around for now is just to delete them.

**Comment by mSparks43** [comment]
after quite a bit of testing the new FMC is the correct one, VNAV is custom and its recalculating for current flight conditions.
