### ISSUE TITLE
Tail strobe light flashing on windscreen

### ISSUE THREAD

**Issue by MoonRocket2023** [mSparks43/747-400#863]
When you lower the view enough out the windscreen over the nose, it looks like the tail strobe light is flashing in front of the view.

# Please provide documentation references:

Place an x to check the boxes:
- [x] Something found during a flight test
- [ ] FCOM reference included (issues are likely to be closed without this)
- [ ] checked [current](https://github.com/mSparks43/747-400/blob/master/plugins/xtlua/scripts/B747.68.xt.fms/activepages/version.lua) FMC revision ident 
- [ ] Video included (where applicable)
- [ ] Screenshot included (where applicable)

### Bug reports:

Many remaining issues are likely airframe specific, please provide the livery this bug happens with

Airframe: ________ 

The livery folder will also contain a jdat file of various data recorded during the flight, please attach it to the report if the issue occurs during a specific phase of flight

Please replace this line with a detailed description of the issue

**Comment by CalibraNR** [comment]
Would like to second that @mSparks43 
![747-400 - 2023-11-27 09 11 43](https://github.com/mSparks43/747-400/assets/125405575/45a3f942-1d27-4586-81cc-44dc6072a1dd)
This was observed in XP1206-2023/11/05 04:38
