### ISSUE TITLE
Why does the airac on the B747-400 from sparky not work? 

### ISSUE THREAD

**Issue by egortop4554** [mSparks43/747-400#865]
Like, he writes that airac  itself has been updated, he does not want to enter points. Writes not found
![20231128160657_1](https://github.com/mSparks43/747-400/assets/152284288/cead3b3e-1047-4f5c-ae28-6ac17bda2a72)
![20231128160553_1](https://github.com/mSparks43/747-400/assets/152284288/11e59641-d792-45e0-b24f-ca696fce09eb)

**Comment by mSparks43** [comment]
This should be recreatable in the default 737.
assuming it is, please file it with LR against the 737.

https://www.x-plane.com/x-plane-bug-report-form/

(navdata loading is native xplane functionality)
