### ISSUE TITLE
game breaks when after using mSparks 747

### ISSUE THREAD

**Issue by ariamm1** [mSparks43/747-400#868]
after using the 747 , when i load another plane none of the surfaces work i move the yoke but nothing happens.
the issue goes away after i close and reopen the game.

**Comment by mSparks43** [comment]
This will need filing with LR bug report, the 744 enables control overrides, afaik there is no way to switch these back on when you change aircraft. 

You can use the form here:
https://www.x-plane.com/x-plane-bug-report-form/
