### ISSUE TITLE
Altimeter bug moves beyond altimeter scale

### ISSUE THREAD

**Issue by airfightergr** [mSparks43/747-400#87]
The altimeter bug moves[ beyond altimeter scale.](https://i.imgur.com/WppFb1n.png) 

The correct position is [this](https://upload.wikimedia.org/wikipedia/commons/2/2d/Primary_Flight_Display%2C_Boeing_747-400.png)

Proposed solution:

- Custom dataref to drive it, so if the difference between current altitude and AP altitude is greater than 500, the custom dataref to stop at 500.
- Use clipping in planemaker, so the portion beyond the altitude scale is not drawn.

**Comment by mSparks43** [comment]
a lot of clipping broke when adding the screen selector animations.

The other one of these is the speed tape showing up on the right hand side radio leds.

I like the custom dataref idea the most, this also applies to the speed bug as well I guess.

**Comment by rKsanu2MMYvypWePtQWM** [comment]
Also the heading bug/line on the ND goes all the way to first officers display if turned to the right of the screen.

**Comment by mSparks43** [comment]
this should be fixed
