### ISSUE TITLE
Throttle Indicator line on upper EICAS not showing

### ISSUE THREAD

**Issue by marty90** [mSparks43/747-400#875]
The Upper EICAS does not show the Throttle Indicator white line. See the below figure:
<img width="400" alt="Screenshot 2024-02-07 alle 12 34 34" src="https://github.com/mSparks43/747-400/assets/11349259/233470da-a155-4a7c-82b6-55c9a034d8bc">

However, looking for example at [this](https://www.youtube.com/watch?v=qZJl4Yb7l_E) video on YouTube, the white line should be there, as in the below figure
<img width="400" alt="Screenshot 2024-02-07 alle 12 42 29" src="https://github.com/mSparks43/747-400/assets/11349259/c5b6e215-4c2a-41b0-8b80-dcbc67fb6cf1">

This bug seems similar to [this](https://github.com/mSparks43/747-400/issues/805).

Specs:
- 747 Version 3.2:
    - 744.XP1206_2023_08_12.zip
    - Sparky744.XP11.backport.zip
- Xplane 11.55
- Mac Book Pro - Apple M3

Note: trying version 2.4, I see the line, but it goes at only a third of the way, as said in the [aforementioned](https://github.com/mSparks43/747-400/issues/805) issue.

Place an x to check the boxes:
- [x] Something found during a flight test
- [ ] FCOM reference included (issues are likely to be closed without this)
- [ ] checked [current](https://github.com/mSparks43/747-400/blob/master/plugins/xtlua/scripts/B747.68.xt.fms/activepages/version.lua) FMC revision ident 
- [ ] Video included (where applicable)
- [x] Screenshot included (where applicable)

**Comment by marty90** [comment]
After some chat on Discord, I found that the line is shown only if certain engine models are selected.
For example, if you go on FMC -> Menu -> Aircraft Config -> Page 4 -> Engines, and you select e.g., RB211-524G, then the indicator is shown.

**Comment by mSparks43** [comment]
which engine is not showing?

**Comment by marty90** [comment]
That's the default one: CF6-80C2-B1F

**Comment by mSparks43** [comment]
I can't get a recreate on this
![image](https://github.com/mSparks43/747-400/assets/6773686/6d113c48-a08e-4383-a4ba-162f9ab78f1d)
what exactly (from opening Xplane) did you do (and which livery) to get to this state.

**Comment by marty90** [comment]
I am just making a new flight flagging "_Start with Engines Running_", starting the flight on a Runway.
Actually, the default engine is different with different liveries (sorry for not specifying, but I completely ignored liveries could affect aircraft's settings)

- When using the `Default` livery, it starts with the `PW4096` and the bar is there
<img width="400" alt="default" src="https://github.com/mSparks43/747-400/assets/11349259/c72507ed-a2a1-408f-ab56-c2910b304a2b">

- However, if I manually change the engine, setting it to `CF6-80C2-B1F`, the bars disappear:
<img width="400" alt="default - cf6" src="https://github.com/mSparks43/747-400/assets/11349259/65c28c84-768b-41d8-a348-bf85da0bac54">

- I the first post I was using `rpc777-Lufthansa (Old)`, which uses by default the `CF6-80C2-B1F` engine:
<img width="400" alt="lufthansa" src="https://github.com/mSparks43/747-400/assets/11349259/b12581bd-ad9c-4268-951e-7597fdd26f3d">

- This when using `British Aiways`, which by default uses the engine `RB211-524H2`
<img width="400" alt="british airways" src="https://github.com/mSparks43/747-400/assets/11349259/1060a423-3839-4ebc-9838-96656bab8d2e">

Observation: with the `PW*`engines, if I give maximum throttle, the white line does not arrive at the end position of the engine's rectangle, thus the white area overtakes it. Is it wanted?
<img width="400" alt="default - PW - max throttle" src="https://github.com/mSparks43/747-400/assets/11349259/a5b8520b-2ebb-4019-b201-3bc684db838e">

**Comment by mSparks43** [comment]
I'm not able to recreate any of these on the latest builds, so I'm going to close it for now as already fixed, if this behaviour persists after the next release please reopen (or ping me to if github doesn't give you that option) and we can dig deeper into what might be causing this behaviour.

**Comment by marty90** [comment]
Thank you.
I can try to reproduce my self.
To use the last build, I only need to clone the git repo?
Which X-Plane 11 backport files should I use?

**Comment by mSparks43** [comment]
same backport as in the release.
yep git clone, good to go.

**Comment by marty90** [comment]
I just tried.
I cloned the repo and copied in the directory the backport file.
Same problem (no throttle indicators for `CF6-*` engines).
Can be this due to XP11.55? O Mac?

**Comment by mSparks43** [comment]
its possible its xp11 specific

**Comment by mSparks43** [comment]
since this seems to be limited to XP11 there isnt much that can be done. either that or something in the old XP11 acf. if soneone wants to try importing the latest panel code jnto an XP11 acf i can add it to the backport.
