### ISSUE TITLE
Unactive lines in Takeoff reference/little ND symbols

### ISSUE THREAD

**Issue by DenchikGushchin** [mSparks43/747-400#88]
Good evening, mSparks43. Thank you so much for your project. But i want to mark two problems in my issue.
Firstly, it's takeoff reference page. There are many unactive keys
![fmc747](https://user-images.githubusercontent.com/74779479/99812258-44b82500-2b57-11eb-896c-3717befb0d1a.png)

Secodly,i think you should make changes in ND.  The symbols there are too small. 
![ND 747](https://user-images.githubusercontent.com/74779479/99813553-e0966080-2b58-11eb-99b0-b91ff2af831a.png)

**Comment by jmsantafe** [comment]
The 'Key not active' means the function has not been coded yet. I would not necessarily call this an issue. 
As for the ND fonts, they have already been addressed in #70.
