### ISSUE TITLE
Engine 4 on the CF6 variant giving GEN CONT OFF even when the engine is running normaly 

### ISSUE THREAD

**Issue by FelipeGasp** [mSparks43/747-400#888]
You start the engine as routine, then the engine 4 gives reading of GENERATOR OFF in the eletrical page and in the overhead

# Please provide documentation references:

[
![747-400F - 2024-06-16 17 52 02](https://github.com/mSparks43/747-400/assets/160244036/502ebaa6-00b3-4bee-be2d-15acde9cfadb)
](url)
Place an x to check the boxes:
- [ ] Something found during a flight test
- [ ] FCOM reference included (issues are likely to be closed without this)
- [x] checked [current](https://github.com/mSparks43/747-400/blob/master/plugins/xtlua/scripts/B747.68.xt.fms/activepages/version.lua) FMC revision ident 
- [ ] Video included (where applicable)
- [x] Screenshot included (where applicable)

**Comment by FelipeGasp** [comment]
Maybe the issue is in this file :

plugins/xtlua/scripts/B747.03.xt.electrical/B747.03.xt.electrical.lua

**Comment by mSparks43** [comment]
looks like a normal XP failure simulation
![image](https://github.com/mSparks43/747-400/assets/6773686/0741bd5e-d30d-45e6-ad04-ca3a4e411797)
![image](https://github.com/mSparks43/747-400/assets/6773686/18d44eb3-64ea-444e-85e9-fa9aac2ef823)
