### ISSUE TITLE
[XP11] ILS is fried and won't lock on.

### ISSUE THREAD

**Issue by TheSystemGuy1337** [mSparks43/747-400#891]
**Describe the bug**

# Please provide documentation references:

Place an x to check the boxes:
- [x] Something found during a flight test
- [What the hell is FCOM?] FCOM reference included (issues are likely to be closed without this)
- [ ] checked [current](https://github.com/mSparks43/747-400/blob/master/plugins/xtlua/scripts/B747.68.xt.fms/activepages/version.lua) FMC revision ident 
- [ ] Video included (where applicable)
- [x] Screenshot included (where applicable)

### Bug reports:

Many remaining issues are likely airframe specific, please provide the livery this bug happens with

Airframe: ________ 

The livery folder will also contain a jdat file of various data recorded during the flight, please attach it to the report if the issue occurs during a specific phase of flight

ILS is completely fried and refuses to lock onto proper ILS frequencies. Couldn't find a COM panel so I used NAVRAD menu as per #856 but don't understand what FCOM is and how to access it. Any attempt to insert ILS information from AviTab causes the FMC to load random ass data and will either cause the plane to divebomb into someone's house or just spin around in circles rather than lock on. This screenshot is from my attempt to land at JFK, runway 13L. Typing the information in instead loads data for KDTW.

![image](https://github.com/user-attachments/assets/aaa852e1-667b-4710-925e-69a3afb6ba54)

**Comment by TheSystemGuy1337** [comment]
Also, for whatever reason the Master Caution and Master Warning lights are extremely dim. Two issues for the price of one!

![image](https://github.com/user-attachments/assets/341f0a56-70e3-44f7-a1bb-08463ef690a7)

**Comment by mSparks43** [comment]
There's lots of issues in XP11, many of which are fixed in XP12. XP11 support is now minimal at best, I'll do what I can to fix things that were working if they get broken, but other than that XP11 support is minimal.

FCOM stands for Flight Crew Operating Manual, you'll find them online, or via materials linked on the discord.

The ILS autotunes, so just enter an approach and then press APP and you should be good to autoland, you need to be 50nm from the airport and receiving signal before it will activate.

**Comment by TheSystemGuy1337** [comment]
> There's lots of issues in XP11, many of which are fixed in XP12. XP11 support is now minimal at best, I'll do what I can to fix things that were working if they get broken, but other than that XP11 support is minimal.
> 
> FCOM stands for Flight Crew Operating Manual, you'll find them online, or via materials linked on the discord.
> 
> The ILS autotunes, so just enter an approach and then press APP and you should be good to autoland, you need to be 50nm from the airport and receiving signal before it will activate.

Since XP11 isn't even properly supported anymore, I'll revert to an older version and just put up with the issues. I don't have any PC that can even run XP12. We should also consider dropping XP11 support fully at this point.

**Comment by TheSystemGuy1337** [comment]
Even then, where do I enter the approach infomation?

**Comment by mSparks43** [comment]
> Even then, where do I enter the approach infomation?

https://m.youtube.com/watch?v=9D4fdV1sBKw
