### ISSUE TITLE
Pack sounds dissappearing after engine start

### ISSUE THREAD

**Issue by schillischote** [mSparks43/747-400#95]
After engine start and disconnecting the apu it gets really quiet in the cockpit and all the sounds from the packs fade away.
Meanwhile in the cabin all the air conditioning sounds can still be heard and create a great soundscape.

Maybe this is connected to this issue:
While the engines are in idle, only engine bleed 2 is shown as "on" in the overhead panel (no ecam message) although all 4 are switched on and connected just like bleed no. 2. If you apply about 30% N1 the all bleeds kick back on and don't show the yellow "off" sign.

Unfortunately I have no idea why this would happen or how to solve it. Love the project, keep improving this great plane!

**Comment by jmsantafe** [comment]
Seeing as this is a sound issue and the sounds were not created by mSparks, I recommend you take this over to x-plane-sound.blogspot.com (FTSim). They made the sounds and should be able to help you. The pack included with the aircraft is the Pratt & Whitney soundpack.

**Comment by schillischote** [comment]
Is it really? The engines modeled are CF6's though!?

**Comment by Matt726-S** [comment]
a new soundpack had been added, and the fans no longer disappear. cabin sounds may be a little quiet but it’ll all be fixed. download the plane again, and you are free to close this issue

**Comment by crazytimtimtim** [comment]
yep, you or @mSparks43 can close this issue.
