### ISSUE TITLE
Save sim config

### ISSUE THREAD

**Issue by ymnoor21** [mSparks43/747-400#96]
I was wondering if there is a way to save sim config to a file. So that depending on livery selection, it will automatically select the correct units, transition alt/level (if available), etc.

**Comment by flfy** [comment]
@mSparks43 a per-livery JSON-based configuration would be a great idea.

Possibly formatted as such:

```json
{
  "baroUnit": "hpa",
  "transAlt": 5000
}
```

Upon aircraft loading, read the JSON file from the livery folder and set the values. Defaults of course would need to be programmed in case parsing fails or an incorrect k/v pair is provided.

**Comment by Marauder2882** [comment]
This is on the list for the next release.

**Comment by crazytimtimtim** [comment]
Doe. @mSparks43 can close.

**Comment by Marauder2882** [comment]
Curious as to what “Done” means?  SimConfig currently already does this so are you saying it can just be closed or are you making additional changes to do something?

**Comment by crazytimtimtim** [comment]
> Curious as to what “Done” means? SimConfig currently already does this so are you saying it can just be closed or are you making additional changes to do something?

I mean simconfig already has this, it can be closed.
