### ISSUE TITLE
Some issues

### ISSUE THREAD

**Issue by Abdullahniazy** [mSparks43/747-400#97]
I just did three flights with this nice aircraft but i have some bugs i would like to report.
1-after pressing TOGA i was unable stop the throttle to reject takeoff i tried turning autopilot off and switching auto throttle off nothing worked.
2-the autopilot doesn't catch the ILS.
3-animation problem with  landing gear lever when i press the landing gear down button the gear dose go down but lever doesn't move .

**Comment by mSparks43** [comment]
please retest, all these should be fixed 

there is a custom command for the landing gear lever, 
lots of A/T fixes since november, 

also
![image](https://user-images.githubusercontent.com/6773686/116785355-75eb3880-aa99-11eb-967b-400022c83a45.png)
