### ISSUE TITLE
Glideslope overshooting

### ISSUE THREAD

**Issue by cabsdekris** [mSparks43/747-400#98]
Hello. First of all congratulations and thank you for your efforts to make this aircraft contributing to our hobby.
I did a couple of short flights and the plane works very well, of course there are some things here and there but I'm sure they will be addressed in the future. The only thing I would like to point out is that my aircraft didn't catch the glideslope after using the APP button.  probably it's something wrong with me and the handling of the aircraft. If not, you have something new to look into.
Thank you again mSparks43. Great work....!!!!

**Comment by mSparks43** [comment]
There's a (now) known bug in the current release if you press the LOC button before the APP button.
This should be fixed on the current master branch, but for now if doing an ILS with a glideslope dont use LOC first.

**Comment by cabsdekris** [comment]
> 
> 
> There's a (now) known bug in the current release if you press the LOC button before the APP button.
> This should be fixed on the current master branch, but for now if doing an ILS with a glideslope dont use LOC first.

Thank you. I'll try it...!

**Comment by mSparks43** [comment]
closing as fixed
