### ISSUE TITLE
Autopilot issues

### ISSUE THREAD

**Issue by rKsanu2MMYvypWePtQWM** [mSparks43/747-400#99]
When turning, the autopilot often is too slow to turn, which results in wide turns, and then it cannot straighten out in time, so it overshoots and then oscillates left to right to get back on track. While this isn't a huge deal in cruise or climb, it's practically impossible to align yourself with the localizer in time if you are not coming in straight-in.

Also, it's hard to make VNAV active - sometimes the throttles go into HOLD and then you need to play with the MCP for a few minutes to get it working.

**Comment by mSparks43** [comment]
>it's practically impossible to align yourself with the localizer in time if you are not coming in straight-in.

I've actually done a fair bit of testing on this issue over the last few months, and even had a couple of chats with LR about it, so worth mentioning a few of the aspects to it.
Firstly, in terms of actual "issue", a lot of STARs actually have different turns depending on the weight class of the plane, the 744 is large and heavy with a large turning circle and can't make the same turns as say something like the 738 - default LNAV doesn't seem to take this into account, so you may have to for the forseeable.

Secondly, even if you are on the correct approach, but heavy with fuel, the turning circle may still be to large to make it, you have to adjust the fuelling such that you are as light as possible before reaching final, if you are light you can probably make even the tight turns, too heavy and you may well end up stalling in the turn.

Lastly, watch for catching then loosing the approach localiser if you dont make the turn, if this happens it will almost certainly mess up the approach, there is a fix for this in the release, but it caused issue #98 


>Also, it's hard to make VNAV active
Please review the the FMA video
https://www.youtube.com/watch?v=sDa1ukA3CUo

And be more specific about which part is isn't abiding by.

**Comment by rKsanu2MMYvypWePtQWM** [comment]
I viewed those videos already, just so I would know if it's me who is causing the problems.
I guess I would need to record some videos, since I don't know how better describe it atm. I also found it hard to enable manual speed window in MCP with VNAV engaged while keeping autothottle actually follow the speed inputted (staying in HOLD or IDLE).

Actually there is something else I've forgot to mention - from what I understand, the current VNAV is simplistic in that it descends to a precalculated altitude (via V/S I believe?) inside a virtual altitude "window" like in the MCP, and sometimes after passing a waypoint, it doesn't set the new altitude into that virtual variable, meaning that if I don't click the altitude knob, it would stop descending completely.

**Comment by mSparks43** [comment]
>record some video

Grabbing something like this on video is by far the easiest way Ive found to pick apart and then fix issues like this (and playing test pilot is also fun)

This is the one I did to close out the beta
https://youtu.be/gRIOStViwEI

Trying to describe it can easily go round in circles because the logic and normal/non normal operations are pretty complex, so without a video of everything leading up to something unexpected there's no good way to remember what was done or not done to make it happen.

**Comment by Ziko-cmd** [comment]
I was flying from KJFK to EGLL and my LNAV was refusing to engage. If I clicked the button it would light up for 2 seconds and turn off again.

**Comment by mSparks43** [comment]
> I was flying from KJFK to EGLL and my LNAV was refusing to engage. If I clicked the button it would light up for 2 seconds and turn off again.

This generally means the FMC does not have an active waypoint or a discontinuity, generally resolved by going direct to the next waypoint.

Closing this issue as non specific, the entire AP has been rewritten since this issue was opened anyway.
